apiVersion: v1
kind: Secret
metadata:
  name: forgejo-env
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  FORGEJO__database__PASSWD: {{ .Values.secret.FORGEJO__database__PASSWD | quote }}
