apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-ml
  labels:
    app: immich-ml
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-ml
  template:
    metadata:
      labels:
        app: immich-ml
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      terminationGracePeriodSeconds: 30
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: {{ $.Values.global.failover.fastTolerationSeconds | default 60 }}
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: {{ $.Values.global.failover.fastTolerationSeconds | default 60 }}
      nodeSelector:
        kubernetes.io/hostname: jubilife
      containers:
        - name: immich-ml
          image: ghcr.io/immich-app/immich-machine-learning:v3.0.1-openvino@sha256:7e112847c5ed2c55d4296d9dcb575f5de69f5dd836faab87db9fd870ab260c6b
          imagePullPolicy: IfNotPresent
          env:
            - name: MACHINE_LEARNING_CACHE_FOLDER
              value: "/cache"
          ports:
            - name: http
              containerPort: 3003
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
              gpu.intel.com/i915: "1"
            limits:
              cpu: "4"
              memory: 4Gi
              gpu.intel.com/i915: "1"
          volumeMounts:
            - name: model-cache
              mountPath: /cache
          startupProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: immich-ml-cache
