apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-uploads
  labels:
    app: immich
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - jubilife
  hostPath:
    path: /mnt/Data/immich
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-uploads
  labels:
    app: immich
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-uploads
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-ml-local-cache
  labels:
    app: immich
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - jubilife
  hostPath:
    path: /mnt/Data/immich/ml-cache
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-local-cache
  labels:
    app: immich
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-ml-local-cache
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
  labels:
    app: immich
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-data
  labels:
    app: immich
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
