{{- range $key, $app := .Values.apps }}
---
apiVersion: v1
kind: Secret
metadata:
  name: forward-auth-{{ $key }}-env
  labels:
    app: forward-auth-{{ $key }}
type: Opaque
stringData:
  SECRET: {{ required (printf "apps.%s.signingSecret is required" $key) $app.signingSecret | quote }}
{{- end }}
