apiVersion: v1
kind: Service
metadata:
  name: forgejo-svc
  labels:
    app: forgejo
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: forgejo
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpTargetPort }}
      protocol: TCP
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: {{ .Values.service.sshTargetPort }}
      protocol: TCP
