apiVersion: v2
name: forgejo
description: Forgejo (gitea fork) — git hosting
type: application
version: 0.1.0
appVersion: "15"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
