apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-creds
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
    - name: tailscale-operator
  interval: 15m
  releaseName: longhorn-creds
  targetNamespace: longhorn-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./k8s/charts/longhorn-creds
      interval: 15m
      sourceRef:
        kind: GitRepository
        name: cute-haus
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cute-haus-global
      valuesKey: values.yaml
