apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 15m
  releaseName: longhorn
  targetNamespace: longhorn-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: longhorn
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.12.0
  values:
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 3
      replicaSoftAntiAffinity: false
      replicaZoneSoftAntiAffinity: true
      replicaAutoBalance: best-effort
      concurrentReplicaRebuildPerNodeLimit: 3
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      allowRecurringJobWhileVolumeDetached: true
      nodeDrainPolicy: block-for-eviction
    defaultBackupStore:
      backupTarget: s3://aly-backups@us-east-005/cute.haus/longhorn
      backupTargetCredentialSecret: longhorn-b2
      pollInterval: 300
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
    ingress:
      enabled: false
