# just is a command runner, Justfile is very similar to Makefile, but simpler.
############################################################################
#
#  Common recipes
#
############################################################################

# List all recipes.
_default:
    @printf '\033[1;36mnixcfg recipes\033[0m\n\n'
    @printf '\033[1;33mUsage:\033[0m just <recipe> [args...]\n\n'
    @just --list --list-heading $'Available recipes:\n\n'

# Generate {ci,edconfig} files.
[group('flake')]
gen target:
    nix run .#{{ if target == "ci" { "render-workflows" } else if target == "edconfig" { "gen-files" } else { error("unknown target: " + target) } }}

# Update flake inputs.
[group('flake')]
update *inputs:
    nix flake update {{ inputs }} --commit-lock-file

# Update all nixpkgs inputs.
[group('flake')]
update-nixpkgs: (update "nixpkgs")

# Update caddy-tailscale plugin to latest commit (also refreshes hash if stale).
[group('flake')]
update-caddy-tailscale:
    bun scripts/update-caddy-tailscale.ts

############################################################################
#
#  Servers
#
############################################################################

# Build a NixOS host locally without deploying.
[group('servers')]
build host:
    nix build .#nixosConfigurations.{{host}}.config.system.build.toplevel

# Deploy hosts with nynx.
[group('servers')]
deploy jobs='':
    nynx --operation switch {{ if jobs == "" { "" } else { "--jobs " + jobs } }}

# Reboot all servers.
[group('servers')]
reboot:
    ansible-playbook -i ansible/inventory.ini ansible/playbooks/reboot.yml

# Ping all servers.
[group('servers')]
ping:
    ansible-playbook -i ansible/inventory.ini ansible/playbooks/ping.yml

# Queue offline deployment & reboot.
[group('servers')]
deploy-offline:
    nynx --operation boot
    just reboot

############################################################################
#
#  Secrets (sops + age)
#
############################################################################

# Derive this machine's age private key from its ssh ed25519 key, install
# at ~/.config/sops/age/keys.txt. Run once per machine. The corresponding
# public key (age1...) must already be a recipient in .sops.yaml.
[group('secrets')]
sops-bootstrap:
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ -f ~/.config/sops/age/keys.txt ]]; then
        echo "~/.config/sops/age/keys.txt already exists; skipping."
        exit 0
    fi
    mkdir -p ~/.config/sops/age
    ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt
    chmod 600 ~/.config/sops/age/keys.txt
    echo "wrote ~/.config/sops/age/keys.txt"
    echo "this machine's age recipient (must be in .sops.yaml):"
    ssh-to-age -i ~/.ssh/id_ed25519.pub

# Regenerate .sops.yaml from keys/*.pub, then re-encrypt every
# secrets/*.yaml. Run after adding or removing a .pub file.
[group('secrets')]
sops-rekey:
    #!/usr/bin/env bash
    set -euo pipefail
    shopt -s nullglob
    user_pubs=(keys/aly_*.pub)
    host_pubs=(keys/root_*.pub)
    {
        cat <<'EOF'
    # Auto-generated by `just sops-rekey` from keys/*.pub.
    # Every recipient can decrypt every secret. To add or remove a
    # machine, add or remove its .pub file and re-run `just sops-rekey`.
    keys:
      # === user keys (aly@<host>) ===
    EOF
        for f in "${user_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#aly_}
            age=$(ssh-to-age -i "$f")
            printf '  - &user_aly_%s %s\n' "$host" "$age"
        done
        echo "  # === host keys (root@<host>) ==="
        for f in "${host_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#root_}
            age=$(ssh-to-age -i "$f")
            printf '  - &host_%s %s\n' "$host" "$age"
        done
        cat <<'EOF'

    creation_rules:
      - path_regex: ^secrets/.*\.ya?ml$
        key_groups:
          - age:
    EOF
        for f in "${user_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#aly_}
            printf '          - *user_aly_%s\n' "$host"
        done
        for f in "${host_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#root_}
            printf '          - *host_%s\n' "$host"
        done
    } > .sops.yaml
    echo "regenerated .sops.yaml"
    for f in secrets/*.yaml; do
        echo "rekeying $f"
        sops updatekeys -y "$f"
    done

# Edit a sops-encrypted secrets file. Usage: just sops-edit vaultwarden.yaml
[group('secrets')]
sops-edit FILE:
    sops secrets/{{FILE}}

############################################################################
#
#  Kubes (k3s + helmfile)
#
############################################################################

# Run all consistency + flake checks.
[group('kubes')]
check:
    bun scripts/check.ts
    nix flake check --impure

# Bump a digest-pinned chart image to its current upstream digest.
# Usage: just bump <chart> | just bump --all | just bump --check
[group('kubes')]
bump TARGET:
    bun scripts/bump-image.ts {{ TARGET }}

# Bump tranquil-pds to its current atcr.io digest. Separate from `just bump`
# because atcr.io is private — `skopeo --no-creds` can't reach it.
[group('kubes')]
bump-tranquil:
    #!/usr/bin/env bash
    set -euo pipefail
    VALUES=k8s/charts/tranquil-pds/values.yaml
    REPO=$(awk '/^image:/{f=1;next} f&&/repository:/{print $2;exit}' "$VALUES")
    TAG=$(awk '/^image:/{f=1;next} f&&/tag:/{print $2;exit}' "$VALUES")
    FLOAT_TAG="${TAG%@sha256:*}"
    CURRENT_DIGEST=""
    if [[ "$TAG" == *@sha256:* ]]; then
        CURRENT_DIGEST="sha256:${TAG#*@sha256:}"
    fi
    USERNAME=$(sops -d --extract '["username"]' secrets/atcr.yaml)
    PASSWORD=$(sops -d --extract '["password"]' secrets/atcr.yaml)
    UPSTREAM=$(skopeo inspect --creds "$USERNAME:$PASSWORD" \
        "docker://${REPO}:${FLOAT_TAG}" --format '{{"{{"}}.Digest{{"}}"}}')
    if [[ "$UPSTREAM" == "$CURRENT_DIGEST" ]]; then
        echo "tranquil-pds: ✓ up to date"
        exit 0
    fi
    echo "tranquil-pds: ${CURRENT_DIGEST:0:19} → ${UPSTREAM:0:19}"
    sed -i "s|tag: ${TAG}|tag: ${FLOAT_TAG}@${UPSTREAM}|" "$VALUES"

# Scaffold a new app chart under k8s/charts/<name>. After running, edit the
# values.yaml and add a release block to k8s/helmfile.yaml. See k8s/charts/README.md.
[group('kubes')]
new-app NAME:
    #!/usr/bin/env bash
    set -euo pipefail
    DIR="k8s/charts/{{ NAME }}"
    if [[ -e "$DIR" ]]; then
        echo "$DIR already exists; aborting." >&2
        exit 1
    fi
    mkdir -p "$DIR/templates"
    cat > "$DIR/Chart.yaml" <<EOF
    apiVersion: v2
    name: {{ NAME }}
    description: TODO
    type: application
    version: 0.1.0
    appVersion: "1.0.0"
    dependencies:
      - name: common
        version: 0.1.0
        repository: file://../common
    EOF
    cat > "$DIR/values.yaml" <<'EOF'
    replicaCount: 1
    strategy: Recreate

    image:
      repository: TODO
      tag: TODO@sha256:TODO
      pullPolicy: IfNotPresent

    resources:
      requests: { cpu: 50m, memory: 64Mi }
      limits:   { cpu: "1", memory: 256Mi }

    ports:
      - name: http
        containerPort: 80

    service:
      type: ClusterIP
      ports:
        - name: http
          port: 80
          targetPort: http

    probes:
      readiness:
        httpGet: { path: /, port: http }
        periodSeconds: 10

    ingress:
      enabled: true
      className: traefik
      routes:
        - host: TODO.cute.haus
          tlsSecret: cute-haus-tls
    EOF
    for kind in deployment service ingress; do
        echo '{{{{- include "common.'"$kind"'" . }}}}' > "$DIR/templates/$kind.yaml"
    done
    helm dependency update "$DIR" >/dev/null
    echo "scaffolded $DIR. next: edit values.yaml and add a release to k8s/helmfile.yaml."
