_default:
    @just --list

[group('opentofu')]
fmt:
    tofu -chdir=terraform fmt

[group('opentofu')]
validate:
    tofu -chdir=terraform init -backend=false -input=false
    tofu -chdir=terraform validate

[group('opentofu')]
plan:
    tofu -chdir=terraform init
    tofu -chdir=terraform plan

[group('opentofu')]
apply:
    tofu -chdir=terraform init
    tofu -chdir=terraform apply

[group('secrets')]
sops-edit FILE:
    sops secrets/{{FILE}}.yaml

[group('secrets')]
sops-rekey:
    #!/usr/bin/env bash
    set -euo pipefail
    shopt -s nullglob
    user_keys=(keys/aly_*.pub)
    host_keys=(keys/root_*.pub)
    {
        cat <<'EOF'
    # Auto-generated by `just sops-rekey` from keys/*.pub.
    # Every recipient can decrypt every secret. To add or remove a machine,
    # add or remove its .pub file and re-run `just sops-rekey`.
    keys:
      # === user keys (aly@<host>) ===
    EOF
        for key_file in "${user_keys[@]}"; do
            host_name=$(basename "$key_file" .pub); host_name=${host_name#aly_}
            age_key=$(ssh-to-age -i "$key_file")
            printf '  - &user_aly_%s %s\n' "$host_name" "$age_key"
        done
        echo "  # === host keys (root@<host>) ==="
        for key_file in "${host_keys[@]}"; do
            host_name=$(basename "$key_file" .pub); host_name=${host_name#root_}
            age_key=$(ssh-to-age -i "$key_file")
            printf '  - &host_%s %s\n' "$host_name" "$age_key"
        done
        cat <<'EOF'

    creation_rules:
      - path_regex: ^secrets/.*\.ya?ml$
        key_groups:
          - age:
    EOF
        for key_file in "${user_keys[@]}"; do
            host_name=$(basename "$key_file" .pub); host_name=${host_name#aly_}
            printf '          - *user_aly_%s\n' "$host_name"
        done
        for key_file in "${host_keys[@]}"; do
            host_name=$(basename "$key_file" .pub); host_name=${host_name#root_}
            printf '          - *host_%s\n' "$host_name"
        done
    } > .sops.yaml
    for secret_file in secrets/*.yaml; do
        sops updatekeys -y "$secret_file"
    done
