repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: longhorn
    url: https://charts.longhorn.io

releases:
  - name: traefik
    namespace: kube-system
    chart: traefik/traefik
    version: 40.0.0
    values:
      - deployment:
          kind: DaemonSet
        service:
          type: ClusterIP
        ports:
          web:
            hostPort: 80
          websecure:
            hostPort: 443
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        priorityClassName: system-cluster-critical
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true

  - name: longhorn
    namespace: longhorn-system
    createNamespace: true
    chart: longhorn/longhorn
    version: 1.11.2
    values:
      - defaultSettings:
          defaultDataPath: /var/lib/longhorn
          defaultReplicaCount: 3
          replicaSoftAntiAffinity: false
          allowRecurringJobWhileVolumeDetached: true
        persistence:
          defaultClass: false
          defaultClassReplicaCount: 3
          defaultDataLocality: best-effort
        ingress:
          enabled: false

  - name: aly-codes
    namespace: default
    chart: ./charts/aly-codes

  - name: watsup
    namespace: default
    chart: ./charts/watsup

  - name: morsels
    namespace: default
    chart: ./charts/morsels

  - name: uptime-kuma
    namespace: default
    chart: ./charts/uptime-kuma

  - name: vaultwarden
    namespace: default
    chart: ./charts/vaultwarden

  - name: external-routes
    namespace: default
    chart: ./charts/external-routes
