apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-env
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  DB_CONNECTION_STRING: {{ .Values.secret.DB_CONNECTION_STRING | quote }}
  ENCRYPTION_KEY: {{ .Values.secret.ENCRYPTION_KEY | quote }}
