apiVersion: v1
kind: Secret
metadata:
  name: audiobookshelf-rclone
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  RCLONE_CONFIG_B2_TYPE: {{ .Values.secret.RCLONE_CONFIG_B2_TYPE | quote }}
  RCLONE_CONFIG_B2_ACCOUNT: {{ .Values.secret.RCLONE_CONFIG_B2_ACCOUNT | quote }}
  RCLONE_CONFIG_B2_KEY: {{ .Values.secret.RCLONE_CONFIG_B2_KEY | quote }}
