{{- with .Values.pullSecret }}
{{- $auth := printf "%s:%s" .username .password | b64enc }}
{{- $cfg := dict "auths" (dict "atcr.io" (dict "auth" $auth)) | toJson }}
apiVersion: v1
kind: Secret
metadata:
  name: atcr-pull
  labels:
    app: {{ $.Chart.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $cfg | b64enc }}
{{- end }}
