apiVersion: v1
kind: Secret
metadata:
  name: tranquil-pds-env
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.AWS_SECRET_ACCESS_KEY | quote }}
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  DPOP_SECRET: {{ .Values.secret.DPOP_SECRET | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}
  MAIL_SMARTHOST_PASSWORD: {{ .Values.secret.MAIL_SMARTHOST_PASSWORD | quote }}
  MASTER_KEY: {{ .Values.secret.MASTER_KEY | quote }}
