apiVersion: v1
kind: Service
metadata:
  name: tranquil-pds
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: tranquil-pds
spec:
  type: ClusterIP
  selector:
    app: tranquil-pds
  ports:
    - name: http
      port: 80
      targetPort: 3000
