title = "watsup"

[[sections]]
type = "widgets"
columns = 4

[[sections.widgets]]
type = "weather"

[[sections.widgets]]
type = "search"
span = 3

[[sections]]
type = "widgets"
columns = 2

[[sections.widgets]]
type = "lobsters"
title = "Lobsters"

[[sections.widgets]]
type = "hacker-news"
title = "Hacker News"

[[sections]]
type = "services"
title = "Atmosphere Apps+Infra"
columns = 3

[[sections.services]]
name = "atbbs"
url = "https://atbbs.xyz/"

[[sections.services]]
name = "morsels.blue"
url = "https://morsels.blue/"

[[sections.services]]
name = "haunt.at"
url = "https://haunt.at/"

[[sections.services]]
name = "snarled.at"
url = "https://snarled.at/"

[[sections.services]]
name = "aly.social"
url = "https://pds.cute.haus"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/bluesky.png"

[[sections.services]]
name = "slingshot"
url = "https://slingshot.cute.haus"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/bluesky.png"

[[sections]]
type = "services"
title = "Webpages"
columns = 3

[[sections.services]]
name = "Aly Raffauf"
url = "https://aly.codes/"

[[sections.services]]
name = "Switchyard"
url = "https://switchyard.aly.codes/"

[[sections.services]]
name = "Morgan Tamayo"
url = "https://morgantamayo.com/"

[[sections]]
type = "services"
title = "Apps"
columns = 4

[[sections.services]]
name = "Pocket ID"
url = "https://id.cute.haus/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pocket-id.png"

[[sections.services]]
name = "Plex"
url = "https://plex.cute.haus/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/plex.png"

[[sections.services]]
name = "Ombi"
url = "https://ombi.cute.haus/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/ombi.png"

[[sections.services]]
name = "Immich"
url = "https://immich.cute.haus/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png"

[[sections.services]]
name = "Navidrome"
url = "https://navidrome.cute.haus"
healthUrl = "http://navidrome.default.svc.cluster.local/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/navidrome.png"

[[sections.services]]
name = "Paperless"
url = "https://paperless.cute.haus"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/paperless-ngx.png"

[[sections.services]]
name = "Vaultwarden"
url = "https://vault.cute.haus/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/vaultwarden.png"

[[sections.services]]
name = "Uptime Kuma"
url = "https://kuma.cute.haus/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/uptime-kuma.png"

[[sections.services]]
name = "Grafana"
url = "https://grafana.narwhal-snapper.ts.net/"
healthUrl = "http://10.254.0.4:3010/api/health"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/grafana.png"
