replicaCount: 2
spread: true
dnsPolicy: Default

image:
  repository: ghcr.io/alyraffauf/watsup
  tag: latest@sha256:d78e2fb9f3af126c317f074a0da11ba9839b30b79b3361f3afde114fe02684ab
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

ports:
  - name: http
    containerPort: 3000

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000

probes:
  liveness:
    httpGet: { path: /, port: http }
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    httpGet: { path: /, port: http }
    initialDelaySeconds: 2
    periodSeconds: 5

ingress:
  enabled: true
  className: traefik
  routes:
    - host: cute.haus
      aliases: [www.cute.haus]
      tlsSecret: cute-haus-tls
