apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: morsels-data
  labels:
    app: morsels
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
