apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ombi
  labels:
    app: ombi
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "ombi.cute.haus"
      secretName: cute-haus-tls
  rules:
    - host: "ombi.cute.haus"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ombi
                port:
                  number: 80
