replicaCount: 1
strategy: Recreate
terminationGracePeriodSeconds: 30

image:
  repository: ghcr.io/advplyr/audiobookshelf
  tag: 2.35.0@sha256:89276ff2e0b3d2f07dd334b641f27a34ab7f02e1047c60b7b8a30126cb0813a5
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "2"
    memory: 1Gi

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80

persistence:
  enabled: true
  storageClassName: longhorn
  size: 30Gi

env:
  TZ: America/New_York

secret: {}
envFromSecret:
  - audiobookshelf-rclone

failover:
  fastTolerationSeconds: 60

rclone:
  image:
    repository: rclone/rclone
    tag: 1.71@sha256:3103526c506266a9ecdf064efe99bf3677d92ef6407af124d8c56b4f49cbaa51
    pullPolicy: IfNotPresent
  remote: b2:aly-audiobooks
  mountPath: /audiobooks
  vfsCacheMaxAge: 168h
  vfsCacheMaxSize: 5G

ingress:
  enabled: true
  className: traefik
  routes:
    - host: audiobookshelf.cute.haus
      tlsSecret: cute-haus-tls
