apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  labels:
    app: seerr
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
