apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: switchyard
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: switchyard
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: switchyard
