apiVersion: v1
kind: Service
metadata:
  name: switchyard
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: switchyard
spec:
  type: ClusterIP
  selector:
    app: switchyard
  ports:
    - name: http
      port: 80
