apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluesky-pds-data
  labels:
    app: bluesky-pds
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
