apiVersion: ENC[AES256_GCM,data:5Cc=,iv:NL3ZVPhTMnkkQbT00JUZMHbPIUjeXND1nk7erlwgrSo=,tag:UDmzVL1vUTGK3mDDmWL00g==,type:str]
data:
    RCLONE_CONFIG_B2_ACCOUNT: ENC[AES256_GCM,data:9qClao1kLprD11YgYhAJr8Hz/6khtNSewSL+7NoqUFKBiQK6,iv:utm1F0w6VX61njjY9TBirJAhd8gpLj+p5ZFXUQieXmk=,tag:9623zbUba0NHE81qhfKjFg==,type:str]
    RCLONE_CONFIG_B2_KEY: ENC[AES256_GCM,data:PFgZ5Fcb1rPm4V5W3+Rn4A1wKxw5AsVd9llns1Yve1m/zuiBZSkrL0nLthM=,iv:zQ5n3bN95cQqMvqvF/xX7swKc8fa8rMtXY9kLz2cn0g=,tag:/GlyV6bWEHKRCwp8NKivvg==,type:str]
    RCLONE_CONFIG_B2_TYPE: ENC[AES256_GCM,data:wY/ttg==,iv:/FWhaZRvjh/NERVOk6PzbyhNEn2goMnYRCqy6HUbmqs=,tag:g+tpf1nGjGwUFZSkeN0qpw==,type:str]
kind: ENC[AES256_GCM,data:tO52Wu+Z,iv:TtVXzMZC1Ihf2+heFPqwC6nUXI7TVDwhBZX8UMUe/OM=,tag:q2KzK7RDlo82qKVjCW10Qg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bjk/w3WQqGyfCLXE2FH8b/5oxTTf,iv:cCai7g81FHf+vxDGS4PGQhgdIxiofHoGC7T4c3c9Kq0=,tag:gYTA3QAJusnW4sx5/g7UoQ==,type:str]
    namespace: ENC[AES256_GCM,data:HjVVny6YNA==,iv:lYhsqrHbxvmz5LXxBel8O2Yrj2eINMTcgdRQMIJ+w5k=,tag:va1tHn12V6ibwGviYH39TQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYlc4NjZ6RzBtSExyaHZ4
            bjJVaVUvd3N6dDNMYmNiV0dQZXFRZGxwWnpJCkkrUTlpY2dYbjR4Y3BXcmorVTY5
            QVI0blArMDhKM0c2eXRIajV1b2F5aFEKLS0tIDZVaXdjM1RuZ0trN0ZrZWZjUXJn
            aWtHSGFJUTVzeloxU05wYXM1YWFTWGsKMFQcDZg1piIBmZeafhu2enNRqoHc/yiv
            abRs4/tt7tXlRODcpgA5+5nO77OC/TFlBTuMlgHcmNPLyiDWTYAyFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWGVlaE01SDJWcnJnMTdS
            S3pTK0ZNdGs0MXNnZmwvK1hzdVc3T0ZtbkdJCkJpeWwzOUlUK2tVV3h2aVVmcmxq
            ZXRBYW5MQTh3Vlo3Yk9tRXBWZXdvVm8KLS0tIHlFR2pxOURaQmRsTmwyYng1ZVlC
            T2hkcko1ZlFPbG10M3VQZ0RmSnhiMGMKKaHO4tqadYOATZzsB5hCBCIKdX+AJ7GX
            stpBPlC3c+X6rRRwOkbid6GLZCG5bPiSKDtBlDdyNTylvoaceRKonw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UVN0ejhmdmxZOXVNdnF3
            VWkwVEx5TXc3TDgwYWMzZ2JKQWg1anUycXpBCkUvam11NFZXSTBnVy9nRTV5cUx5
            bTBnYVllZjN4TWtNMlkzdXFTMFdnZncKLS0tIGZzSXBRTEhpRDdGQ0ZncnNFTzdQ
            c3VXcnlrU0w2bTZRMktwS21YdGJramsKR8qI99EdDk91Ktkt1Ip6280S9gzFSqEk
            EdJXWIZnKOEeCkY0bZRHc3ZuWn19u8aMMcdVOilEyHgCKJlxviBGfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV1paUmx5SmZhSlYvMVpQ
            YzE3eCtURmVXRGpsNVVHdnhQc2puMTRUYUVvCnNJclhFSlpjVUZmRWlOUkdvRDdC
            WGdBOFNQU21vR2FQNXkvdkExYVBkYnMKLS0tIDhGRWhiRVNIUWU3UW1VVmFwSEFT
            dm1XKzVnYm1QNGVhLzVQbkE2NXYzWEEKMbyMkbt2HYON/Xh2Md53DryQe5HOeVe5
            iAuwYPm8dpSq+LS9YswxpEnsvK1XP17F4SFn8ax8t5VGw8lFL9L2/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcFpya2VSNzZIbXhaWjVn
            SWFNcnVjOFE3cUpWT25oaWRSZEozbGV5TlIwCkxYOSs5UkloRWhJL3puVk5TVDVH
            eDBsSzhIRHFjZ1RZZmZiZGwrOGJURHMKLS0tIFlEL0VZWFhZeFBaeTNsYlJBY1NQ
            V1RmT3NNQjZML1RUOU0rdkJseitoWlEKJfsgrMGJJzE9PKmLfb3LpMXNSa4BRRm0
            +T+kIPrOOYD7hJOi9VG6IxxSPTdOUZYV1Qg3FWlef55ANlrpqpCA7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UlptWjJ4dTZIa2ZyaGRi
            V2pUMExuS1FWUGRIVkE4VzE0TDUvSUFZZ2dBCjB0ZDZMSmRxT3hhdW1Ha0dnUWc4
            N0R1RmYwazFaZFVsbEJmWjNwQ0dOWFEKLS0tIG45eW0xQWhRVGJoaU90OUpuWHZx
            aGZ4NHg5QkpRNmhJcFJiRFAvZDc3TDgKKyoo+QhVLiJh5m/aBsUHeiTC/BcJC8Yn
            O1LnyeLem3vMvBq7dEb5zozZYCtZNYeIxj1seZk5r5WRMOBQkQvYEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RVpJb1hBbU5FNTFRaEMw
            bXN3WHF0YllwejhtUW1UajZaUndlMUxmcmlzCnNmQTJKaDNDaVkzQm9UQW9yM1lL
            MVYweGY1Q1U2aWx6Uk9CZlJkZ2svRjgKLS0tIFlnWEdZOVBvZTN0V1VPTHd1ZmpK
            OFd4dzNCR0dMSVJxWXl2ZXZGUlBQRkUKFh8Anq9pCal8Q2OfNTAkQ7/LGGAZDe0R
            LEZupuAV4CxmzUdXtaZ3mpGzEEWQ9a0qE7wZwfdi2pJ4LojIgsAUZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRHVUUytFZTdWQkU5N0JQ
            cERIU0xjU3JyRW4xYURQcS9tbE5MRlpZZW1VCi9UaVdkQk1jZHdORjFjVjB6ZS9H
            UUprV2pPNnpCTlhiOUtUaldLSktabkkKLS0tIDZHdzIvSWxRbFZHcWVsVG5zVmV6
            aHdOV21xeFU0cnFBcFBZQUFrdjVGdGMKDYuw+Sll/Gb/+Y950fV8IEaXfrJoa0zX
            VkS0e+fjxoCycKpWC4Qsl8+3VDDDEFv4mPuOdLnLuczjpmY1U9YwQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RnhSTVFvbm01MUdYWkZ2
            cHhIL3Q5S2ZTNjlyRlI0UWpoY2sxUWhBYkdjCnNJdkdlclh2NGFlbjBCa2ZxL3Uy
            VDNpY3RJUCtiMFc2K09VbmlvemlpeEkKLS0tIEhGTWk2SHlab3hlR0hsRmFtcEto
            c0dtc0RLVUJNcnZ0a3B1bHpaUlJzREkKg8Jq2Y9nxK3pdlbAdIaJ+2VZelGFfSgR
            yOQ0BVQTD5aJ32Ve8iQOtUimub1EGbdZy8rjwZ6+BpPTw5jyPpmCwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoekZ5YWFlaW9uYURiWDA0
            bHZEYXdGZTJaOWpMSnYxMHYwTzFSZWdLdFZ3CmFlVDU2eDJkcjhQcFJXT2ZycEdU
            Wm5zSTRzNS9majhEeTdSRjBWeVdVbUEKLS0tIHZYSGpVNzZxV0JtdUlXRk5sTWR6
            dVVTbWtsNmlCM281L3JyMWpIT2dHK0EKaT95azJll4OWfR1bK1z99bH85sNYZGdo
            s7tkh6sZHEIfNdwGbjEzFlK4sEOs+tmUqNGVqBPIqPi8MwCPUZXXlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMVRZRUY0QmJZbEk1c0ZC
            NFNMWXBabkJ4Y3BXenZ6MnVBL3QvOGxmWjFNCk0xMzg3Mkd2Z2c4MXRQM2dOOGMz
            cG4weUN4WUhXUE40SnVxUTZkUlc1bW8KLS0tIFNaNlBGakw0eXVRLy9qUUxUZm5F
            bTZsMy9ERGpjNTFIdXY2Ri96UlZxbFkK+/vqi66+H1UU7zdKgDHX6zEDocypsUCf
            RndNoGqW3TRGgcA+BCJJMpUaHqE3XI9V9Q6cM+CzI4d/cZHi+mN9Kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMHNtZGZtNGtZSG12QVNX
            eFVPR2xYOW1xa1JJVVNYY2g4WC80dHdvMkVVCmZZRVU0Rm15VmF4Sk9LWjFlNmU0
            VS9ySmdMbnlhMnVCNHFSc21Bc3RoZWMKLS0tIGpkZExyODcrcm9vWXE4YURFYmcr
            UzArNlRnODYzOE1ObHpxRjd1M3hZUkUKHijCPV2g5FdoQ/5artwqaG8eR/EohQWk
            bfHhatrSz/CLRhp5h+YGkCVtnaPB+gCH/gsNmYBjHuLCMkHXeu0TuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWi9kZkJYK2k4L1h1Skox
            dVJrY05aZkU5NlJ5RENMTEpiY01GamxnNVRJCjhoclBCZklTRkJCVUNZaTdqb2Fh
            bm83ODBHa0RtY0MxMkxyMTRpd0tXcVkKLS0tIFYvK0h6NnAzWE9aTThXc01ndWJB
            WnBlcEMySk1mM1AyeHRpem9yaDZ4WjgKZzTVhQGhdstOOpihrcykvUctTKgukDCY
            mv7j6o//xkq+ikILOfCR+xSGhANolrcGuDfKMC0actNN988pW5WTqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0a2Y2S2tIUmZuZy9rOXQ2
            QXZ0aDJPb1dWbythYXZJZnFlUUJhakJIcjBNCkhBdnZ3VVErVG1Xb3JFSkJMNVZw
            WGlOUHZieHpFVUlKMUpBTkRSSUpNL0UKLS0tIHdTK0hBODBOR1hlUGs4ZUlhKzRP
            TjNCcWJocmdxR2xKNEIvQjhoSmZrdEUKGO0oFrEP1B8iGWCVJGkLbutbCg0u7u8o
            RW1eu6NLJB1ObcfsgSDXPmWWlgaCQHOgTqLYneZUbnWd+sdGdGX2dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:zfbhijoaEtYagO2vthhbFZnh/BsTXEYxEZOppee/CTC/zp2WyFBH+P57nOuQLRTQVHCcKuKFBtmb2aTkLR+jeJ08aoWxwdSyMupA9V8AF7wPRJHzt6otQgATEn9qkMQCqMGK1xPNKmqlbL7/Dev+NpBzonddErF4QfW0Nxhwhx4=,iv:8FREpVr1BmrCQ67+76edPa0gWpAxtQ2Gh4dY0kzZuSo=,tag:viYIGa9/i5NsuCG29a7TkA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
