apiVersion: ENC[AES256_GCM,data:GaY=,iv:2sJ4+zFe0Z0gB0NRCvv89je2n6rr5SCW7L43sQViV7Y=,tag:4EMNASmZ5cUq49ei/DDLvA==,type:str]
data:
    api-token: ENC[AES256_GCM,data:JQ6Zs8q6wddJB7yUrXBqCKMjM66YP6SP9OMUhI3g1pyrNV1CNGP+QW1LOV4SWsSfyTMa09Evgm0lN4X8MEHv3fvMcoLMOakq,iv:OMtyeOt043Bl6IuOJlVFsR7l9IUyuFQkWiL8OamMC90=,tag:EFkja/Q7ww4CigIOzx5Bmw==,type:str]
kind: ENC[AES256_GCM,data:aFZ6gNhw,iv:BbBVKPpnpGu4XWdB3RQ/4rOPnNHAyCp9iPZJC0NvjDU=,tag:x4XBwZryR+JSWyAwgLpDRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dWpTZRAUmWYrc6YBFsESwWJBzsQ=,iv:ij2e3HXy2Ra7s48HocOZ7J7NZwmProZdO+nGYMWNq5s=,tag:K3i3ap0SlFykRCNEy9lHMg==,type:str]
    namespace: ENC[AES256_GCM,data:DpTEoqd6eJ5+MAjZ,iv:Eld0oAp/NJ+dLMEi+lLW2r0QG4FZqyBoePB6BgmMcYs=,tag:v7OZBmGRI6N94rbmfC1P4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMGY0TmZ5QWE1MWJnVG8y
            ZWx5bjZTYXJVU21yRVNhMlRITmYwRFEzUlJJCjlUTHR6a2xyUjd4K2NTNGpqRnU1
            MHRIbVFYd1hFYlUraHRpbGk1cVNTaG8KLS0tIHFqMjBCYWNkVVUyeHVIUDhTWkVT
            bm9OYzlIWmVxMTRRQmk0Y21HOWpZZ00Koaqicv66k6VALaGH3YEASU6B7nufdTik
            I2ht5RPuTf2sjqdpktTmsUVIk8lAYGoGK7JoFhVkkjDnw2B4Hy27ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUVvYkRmSmJkL0RJSGVh
            ZFhnT2oveFBzaFlOT3Q0ZnRVNTZINHp5RTNzCjFyR1JhQXdoSEVlYzNwTzJKR0Rk
            QWdyUnh4czFHWVdWTFhWWnFlSjZQTlEKLS0tIHUxcmkzMURiSnRaVXBDeUNHNWl1
            Z2VkQkRBazVJcFBtWTlpcTBvUUNLOVkK2cyYVcoK1Odf33G4uK+/KbQjrMxJf4Mv
            K00LHiqekLvTDXm33qIWecO3EcD1kJUwtGquY/wJdY4bt0eOm4ObIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTWpMcWhmUk9aR1JBZ2l2
            a2t1TkZnV1lFVCtjWTY5RUVlZmlmUTRZbWl3CnI3K1ZPRHhzODNsM3lIa1ZTbHlG
            RFd2enBrNXJ3ODJleFUyT09TN0lEcTQKLS0tIHBpbndzUUdNRTNQeStWZ2JYdEYy
            MitGUllpOWtkb2NjeGVaS1NMYWplZHcKy/SMk3RnoR9GeqzZkl9mzkS+M3plPh7J
            cYtXnxI99V5b4rAMuoOiGLC7/4gohpygssSnqKvxWUOo6BbPEDGG0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NHd4cUJzNGxRcXpuMTVr
            aWp6NzlyMjRPckplYngzWmRyVU8ydzNlWXlrCktqT0N5SmhXZUZsWWZKVmJPaHBS
            OUlyQy93dzM5QnFZZ2Jka1dFNkRabXMKLS0tIGNuaDd6WUJ6aitlbG5PU1JJL2FJ
            NkZkNzlQeUwzYXlhYy82QWtpbEpHT0kKL+kEa0xcq6P4GwNRaCPl5bLHZlqBvxpA
            cHcWPpgcFk7ho7VMf7uObqsNhIHkuxxo2+Iz4zs5GX0zJWp0BoAn0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWGxVTUVYNVh6eW94R1lQ
            bEd3VzRPUThGcjVxRWV2RlVYaHUrUGFtaEVRCnJxdUVFRTBwRFpORkhyVndiYUpT
            bE0rdFRneThaNzlvcUkwMzFOMEFBNHMKLS0tIFIvLzVoTmVmdkFLb0wybU5IMDI1
            YzVRbGg5SzJEUEZlYUptaUx3dUZCS2cKFKrlD1GHwqHnzOLX5JIkdGcvP8dOiELj
            ubBO3Llo7rEsbXILfPMCCzvwXqKVZhXkXTN9MPRhXIQ80Q7/YbrDGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUGR2aEdtczVZMlB3cHdm
            T2VTcG85d3gzYjFiTmdETjZ4NVFKVzhjVFJjCmVCUC8yL2Q5RlR1SjdzVkxXSXln
            SW5LRndRZ1Q2bTMwS2FIYzNGREZNY3cKLS0tIHpWSzRlTGlzQmlmWjAzci9nTlda
            eDdsZkJDdnBEallqOXVlWmJpU2QzeEEKzJtHJagqiuLidpqlbvCmLcF9y8UWi2Wi
            Wee95+cPCWMVRvR6Su/8srqOPMbrGw3d4mqzjF5j8VDhgn+8+t6zyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuai9hd0RxS3dZNERoTTBU
            NElra2paeFRUVVJzVTZkYUUwYnpiVUxkd2dRCkFCZmhSd2JNTjlnbjJsRVcvSE5q
            V2VrU1ZpTzJ1UFRkVWFFNnErOG1taUkKLS0tIE9CT1V4NjlhaWM5ZnF1VmNIY2xp
            b2hGWk0wdngvNzRwQ1Q0UnZsZnRNMUkKxuwbjX2do7JbHeTh8N2Mge56DpozHI0u
            bn5yXocEDM+TLDUcm4I+6tDK3zj1Ch1q9z+5IQbHJ2OS8lJtwC2F1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMajR2dGtYeGdFU0FCaWJG
            T1pzelY4cHR1OHJ0MFBtTHhHRkZUTTZ5dFJVCm42eURRSnlmc01NUnJLWmZTQmdD
            WG02U3YyRnRoTHdvMWVXbzl3LzV4eWMKLS0tIFIyU0lJQU53VkF4Q0VoT3VDWSs1
            Rkl3YmZpL3ozL3dHMTVaeGVMejFVYTQK08P/biTQC/+5TgF030vSIkSC0PV2w81a
            Mw08MpN9tM4V+8cZANPGLCghdw5Q5sEXJfpYY0Zpl9/rg5XFY5/9Ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUVVZM2I3TzhDL0hKUkdp
            dk93WCtlTjRWVG1WaUFOU21UKzdrUUx1cnpjCi9yQ0Y2VHNoeXFTM1EzSGJHZlRH
            Z0FncStOSlVqWStZMW5heVNrRG42cXcKLS0tIGNvdmp1QlNscGlLaEplenA5RVhp
            S2R1WWdnUjhsc2hPQThPeWltU0VWak0KXLwx1u+tnX4hWWH1YXhrraq5VRas9k6O
            +DjecB6L6NvLv5X2Ln0tHG9mQ+JhYa7y9dShI05kNIHg+Nht2Ywp0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bm8wK2VjaGYwR3hERU1D
            VFFoTE9rRDlZbjZSS1NuQVNBZGg4UmRsYlVVCnBPSVNRZ0lUMjRDb290U2RjUEFz
            ZU1zaTFKSEVtSmJRTUt2WWpScGJsY3cKLS0tIFNpTzB4cE1ueDFCVEJzU2ozeFVk
            c0hMSElNQnEydDZ2T0V6N3FWUTB2Zk0KtsuU1A8qApUn8XwPyT3dM9D9jDa53u9q
            VptKt/AytM8HTk7huiTOafs/mEFXrLz1jPqX7/qgXay3iQi0Y2wN8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaUpIQlBuQ0hBdW4xRkpv
            dVpkb0JyUXdVNk5VQVpESlBEWVd5Z09ZcVhrCmZrVTY4VG8yVEZBMFRMSktHVk13
            K3NrWDhScG1WbkJQMmx0N09XZVhyN1UKLS0tIFpXVzE0Y3VFdDhIUk05RGxoOHI3
            WlJ4UkR6ZzlZVUpJMmtobThIQVFqbTAK6uLnrOgbjA2FQ41ALy4/y0FH4yNHJnHR
            snUaJRyDhKr2/Fs6/JOYdNKN+pp55wlsUYFdVNBDuHFjG65zk0Ui/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdDNDZ055WXJzMUt3S0xK
            ZVJYVEE5UGx2aE5iNkVGU25Xb1JQb3ZnRFNrCnNiWkZLK283R1VIK3B0a0xmQW9K
            Mk9XNngzaiszZ0c5QTVtKzh6ZDJBem8KLS0tIHJwNVVHTVA0SUlzeEMyaHZwb29E
            SzdaWVVaNkVWRzhVUDM3WnVtOGM4T3MKRLZym97qDi0uA4Ysycm3vMQ7OBhD1M+6
            Dvf2A5gR+wOh76hKTUAnjrHMaq+6cRl7OuoEc0Zj+6sKleGVn7WYKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SDVjY1hMZURlckZDVmlM
            eVNteGUyV1VkRG1EOEE5V3M1M1VCbjI3cTFRClFjN2pZU1F3NFpETncxWnhFcHBp
            Z0NyNFcwQ3FkSVNPZWcwVG8ya1RraUkKLS0tIHNZVXZIRisvQUwzV2E3TCttY2lQ
            ZDN6bkp6bWordzIvbE9kZk1uSjhsS3cKyy/7h589t4bQSkoo6bysbF5cNVxVtVRP
            S7hQlqsARDzjWsWvCW74kWLGo/5WhVYpDZCrOaLs5yPgDdlEU+pahA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdWNMS3Vvemxtc1gwWk5P
            RWZ6eTZTeFkzaTdoT0dpYVZCdk1IWmlmR1VvCjRSTFFocVVGRmYzU3gyQXBuMkR1
            SXNBK1NMYTdJRlBzY2ZMOElDM2Y3UnMKLS0tIFB2Y3dCTjBzOGIrY2J6Z0VzczV4
            TG5ueko5ZWZZeUpjbUFJUS9YUHdicmMKN/2JcVH/dTjIyQ5IvTFPDWakLZBqF2yc
            bzrELNPQ2D6G1P5SlKLYHcSXwz6/O0BVkMVeW2wwpWwXTJRcjaaYAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:24:47Z"
    mac: ENC[AES256_GCM,data:h7oBPRXh7kolfgs7nV588bPLbW1IDvEWObglBTT6yDydxnJVKr210jNMPCLvcS2FNvMDSSU1uZRUB8r7Pb2D9C0JZYpS/FBR2A+oDsuY+/lVsgS8WrK+MB4IX0Fof+RUN4FjWkMsyz8YpJrN4HBYybCbTKh4IDEx6ZeG9E5TP44=,iv:GhFdtpXFQlJ7qBXpK08mctXOH8UENuTwwLjimWJSIz0=,tag:NUm1R1Jti7iE8C60la1byg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
