apiVersion: ENC[AES256_GCM,data:GaY=,iv:2sJ4+zFe0Z0gB0NRCvv89je2n6rr5SCW7L43sQViV7Y=,tag:4EMNASmZ5cUq49ei/DDLvA==,type:str]
data:
    api-token: ENC[AES256_GCM,data:JQ6Zs8q6wddJB7yUrXBqCKMjM66YP6SP9OMUhI3g1pyrNV1CNGP+QW1LOV4SWsSfyTMa09Evgm0lN4X8MEHv3fvMcoLMOakq,iv:OMtyeOt043Bl6IuOJlVFsR7l9IUyuFQkWiL8OamMC90=,tag:EFkja/Q7ww4CigIOzx5Bmw==,type:str]
kind: ENC[AES256_GCM,data:aFZ6gNhw,iv:BbBVKPpnpGu4XWdB3RQ/4rOPnNHAyCp9iPZJC0NvjDU=,tag:x4XBwZryR+JSWyAwgLpDRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dWpTZRAUmWYrc6YBFsESwWJBzsQ=,iv:ij2e3HXy2Ra7s48HocOZ7J7NZwmProZdO+nGYMWNq5s=,tag:K3i3ap0SlFykRCNEy9lHMg==,type:str]
    namespace: ENC[AES256_GCM,data:DpTEoqd6eJ5+MAjZ,iv:Eld0oAp/NJ+dLMEi+lLW2r0QG4FZqyBoePB6BgmMcYs=,tag:v7OZBmGRI6N94rbmfC1P4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NWlEWWw4UmJOOTIrelRj
            L1RvSkVtV3IrbkEyM0hINHBKNjJlQStydDBBCmlsdVpmek9oT0pEaEZrbWMwUHBD
            aDNFKzRrblAzbnpuSjRuT2xCVms3S1kKLS0tIGV0WkpjckliTlcvQURNQmpzZ09x
            Yis3c0pCWU52b2tXSCtzTlQ0aWorLzgKbo9jBuA8PXOAmt3sOm9vit+LJ+hfYPRV
            4n2/1uhW+2kBN3Ti5qmPokRSdcKjKzEwztU21VToed/CCWuCre1YkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbFE5d0JLWVBDcWVUMi9C
            Z0FmeXlUWjR6R0ZPR0xWUUdVOEQ5ZUF5S2w4CnJ1QmVJbDBkN0k3ZW0zcHB4NnM0
            MEc5RnFQUi8wdUw5bVFrUTRQekZKS0EKLS0tIFFTOVJsa2ZlaUUxUzJndzVpZEZ3
            ZTBsakUvTkM0VDlwUitTNWxSMmowd3cKKWneUo9n1c1PyS16q8uDc0hW/uhJvVv8
            p1TpGGZZPSZIftg3NkcxBOGcLFZYlv0HRgZPs3wCwTYARH2fnZ/3pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnemRoQmdiSDZBYWJxZXh5
            c251cnZrV2JJSVltQ0RNWFZMMUhnOG1JZmtjCjdqZmRmTHNXUG8vaEtjNWg0VCt0
            cHMxRFNZc0hMMnhrSDJZYndpWjRwd0kKLS0tIFliUEhNS3F5Z05kSUJVcEdmdFNZ
            QkdiV2RwOGt3bDNxdGowQytuRTluVmMKXZtTZJNDqPyH7PcQIM1MgSU53DvTpyTk
            saMKC+j3v2izbkCiKJA95Vr6/WL8rAjzyjyY6mToWLGvm1gRQm473w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ0k2a3dQMWRMMEExaVZj
            SjRVWWR4b25oMkhhOWJLYzRaRlp2ZXJFQWhVCk5sYmkrWURoZU5tWTU4SjEweUM5
            aDVEMmR3UGlDc09GMFpZZnFZTHlKWWcKLS0tIDJWYlBBb1hhTk1TNVZPampsTk1G
            a3J1aUpSaW4vb2Vnckc1ZmRrV3dSMkEKrXu67jpy4d3o/C146P3HrK8JMD5N0kzM
            waHgP/Y/Zt4obScyHZH0ZEiHHVF/D0M8MHuNbCC+9u6CHScn0MF8yQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWkZ2dGxPODZreXUvVERT
            VTBBMkZXNmVZWDF3UzdoMzdNY3dBcVlxbUdBCmpIUmhRay83U0R1c3Z5ZGRrZTBI
            N09lTytYTFBHQW55OURGKzM0Y2g5QWMKLS0tIEFuNlZ2Ky83cHU0U2dvOXFVS2Vn
            K3IrWHdNNXh2dmdDNVBDVDJJU1hZeVEKNLK0El23vP6QJud/jCKgpWDXPOpwaIP0
            436lygQ7c9Wh6HghPEHUhwNAyH6r1aQRS3iKqK2/hoeQUYNFenF5ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNWpyMlhXU3ExVGV0WEZt
            UUlJQ3NMc2tmbS85QnZBSmphVGh6THhacDFzCktlTkdNMDBOa0VVbUQ4dUlkejRz
            Q2lFL3BjYWM5VGhGU3NqLzRBQVBFV2MKLS0tIEppTXUxUWhydXpTNDNtV2FaOXh6
            bXRlZTBSL1dnNXppL0NFVVFMZ3NIUUUKy1cswMChLunI7AneVhAOsxpSS0NkISel
            lZItdkjv/upRXyxgfracASLfxjEdWhGFkT/7m+wFaBR0MHxhuS2wJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNUp2TlQyM0ZOcHRvMDhD
            YndoZzVobjZjOThmQURhcXBEWTVlVjRJV2tjCkwwZXRGcG5XcXlRcGhCN0NUTllB
            QVpPK3FORjU5dzFUYVl4ZGRiSVJOZWcKLS0tIEpkQVZCbFVlZHZ2d21kRWdBTndR
            Ri9KTUw2OFJIYis4Y0kyZ2E2bmNIdTAK/t5RsM8HRKcp/Vvv69jq6j9tLHQc923/
            N+uAFWwmTZTK3UqHn8RQuNq8DppK92HKOlUWL9RcB09aDBJrHunw5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib0ZGa0VmNVV1TVQ4WHN5
            L21iaXhYMUhVV2ZnSzZMZEdUODZTOFhSeXdJCm1TZEk0bTZKQzJLYzBmbG1Ca0lW
            QUJVeFh3SHpBVlhHZVRFemRjTlQwdGMKLS0tIGVMc252dHN0ZTE3TGtuTGU5N1Nu
            ZHhYOHhRaVBJU3pob3lDTTUzNGVpNzAKeuAD9+HIcKH5Od/+pBg8zYQWtmIPf+Cw
            oRRpR82TzP4n7/T/xvWGt3JliIoJKznwZcvkaTuiwFih3x/WDfVZ2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc2lMbWhpZE9ETmhHcWNL
            ZGs5Y3VHb09jZmQrSkJhYVpOU293RjZiMUdFClNPSTJGREJMejVXdVQyL2RVYmRV
            N2ZlUkg1NHVxYnVoYldmTmNWZWdpckEKLS0tIGpNMHlTVXRjajJJa2lhaGN4by9w
            Q1BXVkpLWUJvVGkzem1nVmczMW5NYncKMKJj0+qniEmw5czSmX1rchK8MpVgzrnJ
            2TXVkMN4GBc9Vfs9xwdiNHsYShBSi5BCy5hYJ4/6mnR/QW32Tk4g1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbXNxaE56VWhnTFFWL1l6
            U3JTOUdjamQvNGxiMTJZTW5CMUJCVDdESHp3Cm5PNFJsSFJ3dE9EUWk3SFlMQlBM
            NDF3OWhWczhUNEVWTGk2U0VCbTBORzQKLS0tIFp1MUlXQmc3RDN6Z0o5aytCZlRz
            K1ZMZ3AwN3YrdFVDOGVwU2d5Y3kyencKAoR2QWiVgndVOPopQ/jOxS/9jVefLHRB
            PhNNgFSGSNHpiur603kB5ADBaLjCWVX1wYUsHrxbmdhQQ6TUX+6gMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVlV6WTNZN2lCU1FLcEMy
            UmNPZU81eTlsTUJOblZWZi9Wc0JJQWRrYVJFCm5CbE9vVEJOb0Fabm5QWkpzYWVQ
            M093c1laQW9pdnArTU9LVkZud2RwejAKLS0tIHpLUkVua2dzMVJaMjNUTWNyZHhB
            U3hveGVqSUpFSmh4RUlFbHpHWTIrTDQKk3R6/bw+W18Jlynb0PZahXbQhvewo57u
            C7NDMtc+JeONQak1GZSWIk6kWWg0IhEDtfUejg4Zx0ryQjIN1GRZTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VElNOFJROXY2N001UCtj
            VmpuK20xR0xzd3RkNjZseUduOXloS1dwZDFBCjBCd2hXNUd3WGhTKzFrYU9pL3Ev
            SVEzV1pEMGFHTWNzdmloN0xUbis3L1UKLS0tIDE2NVRWUUJzaXBnYjJYT29MUzlP
            VnpxOGZSRjBaaDJxRWltVE91aVE1TDAKnZzHNPiBuQUmPdj6hAJ4ubJwzXnwdJz6
            7c+1WD3GnGxJlxuaksiMowbEsWOrmbiFDz1pW2GrIFKRTCR69Nz7pA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:24:47Z"
    mac: ENC[AES256_GCM,data:h7oBPRXh7kolfgs7nV588bPLbW1IDvEWObglBTT6yDydxnJVKr210jNMPCLvcS2FNvMDSSU1uZRUB8r7Pb2D9C0JZYpS/FBR2A+oDsuY+/lVsgS8WrK+MB4IX0Fof+RUN4FjWkMsyz8YpJrN4HBYybCbTKh4IDEx6ZeG9E5TP44=,iv:GhFdtpXFQlJ7qBXpK08mctXOH8UENuTwwLjimWJSIz0=,tag:NUm1R1Jti7iE8C60la1byg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
