apiVersion: ENC[AES256_GCM,data:JxE=,iv:rqRXjXE4S0T4X+wQ4UUVFwSMfuMSYyWTHLmiapoefIw=,tag:TFoCM8T7RURfWm1/72dNvA==,type:str]
data:
    password: ENC[AES256_GCM,data:Px22utUQEHwBrolHug6PwY5z4SkNk/bh/n9X+cayAln3zmIFAVEpfkGyfEE=,iv:tbyoDTeDli5OIjjx+DRq8wzk0mJMuIUflPylklbBfkQ=,tag:P+w5s1i1WgL8tomttk0k8A==,type:str]
    username: ENC[AES256_GCM,data:4jtw0NZ3KMo6ednP,iv:Mjheb/3jedQejhlJOilbNZgi11P/Mtsa2nr9VHXP/ww=,tag:cgP75qW7GfNJcvwxUKYOIA==,type:str]
kind: ENC[AES256_GCM,data:jH8YsWyD,iv:+lIa7X2dywhnBGBbUr8ti5h/LXka5X2M0BRL6gWUrGE=,tag:JNnnsPt35CGz5tJINRaNjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4K7tfJSLVAMcwOCIU4flEA==,iv:t4ntn26+lAnJ0qCWRPihWaNgyLEP3qEHEo3gwrkvKAc=,tag:f5OwghHtKKkAP6z2qdx4Gw==,type:str]
    namespace: ENC[AES256_GCM,data:Rd+Q453qBNBurHY=,iv:pU7RcUEUF+sFVY21ek3P/mgernir1Lmjkf8AclirefI=,tag:1GR71+WQPawMfVXRoypBWw==,type:str]
type: ENC[AES256_GCM,data:Yanckl8APFjE/FHldhP8quDDC6sF60IB,iv:13I/TCCVnxtJv2nnlG/09oO05XLjq78gF2ZFqxqg1RQ=,tag:opwr5UR0y3o+FfOiDnvYmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSnkzU3BVbFA2Mmg3Nld1
            L0IzaDdkOFJPQmQxK3lGY0JOVUNsNk9RNVV3CnZFWEthVCtXV3dVaHNWYWx1TEtT
            ZnNpR0hmQ2YvdVBXNXVRYkxaSEVRT2MKLS0tIER1YW5nSFl2NHVYdHBNdURzd2pR
            d2JZZlprUjhzL2x3akpQODVEZ2thMjQKduijMFWvnGw6hzi7OEq257/u1K9OY3vC
            j6gpZmCGaBkRd2KWaCUIFIdKjJ02X5x7qnegmYiO5iTu9Nr6PpnvfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YUx4dzFtK1hxOGxhN0My
            QjlhNGtOV0hPd0pJR2FBUFpLVTVvdWdVS2xnCllrQmRUNisvVE10OW45Vy9Cc1F4
            WjQ3bEhBSUVEalA4RU82MlZHcTlicFUKLS0tIENpRk53U1FIR2FpdFlXSUtWWTM0
            NWpQT2NTdWtqbk94WmxqWmRyRUpBYjgK6wiqteEfvmWUv6zSP9rb3VyESzOIM2sM
            geJJ4t4Bl7m0MvT4tFqkJKx2Z6llYlvg0TiZelXcSiswoK0C5+VNmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK211QzNOTHRkcDZyYWl6
            OVVsQ3Q3WmUyUTEwYkhxbU9jQzVFczcxc0JBCkhNWUVqZlRpTUdZYlhzN1pIZ09h
            aVg0Q1ZudkRWUkgwaU1ScUlwNGNTQXMKLS0tIE5nMktQT3hGUmVLUnFYczZtc1A0
            VzlhQU4zd1JhK3F1L1pFeEIwNEFJZXMKuToAcAm6zXgyAMTNpyV19tSBB5nTkU4U
            NX5KfhGsin6yt2NEpHYt9MXwPNnmw3XX78+fpL2wgMQLHdIm7h6VcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTjFtQ0ZTb05ETEVHakVD
            c3lReW5oSzd4WnZJcXpScUhES2pEelNmaEFrCk9jdzJhQVRNYVUrMUdLcTN3WGRK
            ZnhlVERKbGp2aUFrSGVzSU10ZzlnNFkKLS0tIDNuQ2tMUENZR3NuVlBsbjZkeHls
            ajBRY2ZUazBVbm9uN0EwRFp4SDcrUzAKmu3iU5ZC2Mw+t0xOejYGl24kC9Zt9tSX
            /6V4fO7UrjQbfCkrJlcsOExZ+5eKQEQ9WVPh+onVW3NRqGJzJ/kRwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQS0x5UHY0SURqdFhNdGNt
            YWc0cnFIMXFPb1lIcC95L2gzdUo5OEtHVFhNClRtYnVmdmhUV0dkMGdsVVk0RXRP
            U3JxVmkrb09LMEVhMi9pS2MzQ0NlSzAKLS0tIGV4dFZVeVhMVnZZKzJVTHVmSWta
            czJ2TkZRc2orQXo4cCs1YmN6S1ZwQzQKLOt39tBY6dlENM0Io2AA3WkiCzjbcRcb
            6gqpuAjOLbvoYZrBL17j6ddl1xTnghk7KDO2RvDCi3IW61d2StaUKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bVdFbERPRkxHZmRHU2w4
            Z3BMZzRPcXpnNzJKdE85dE1CZC8vclZPdkNjCmVIVFhiK2M1N0lCV2o1MUZqRS84
            TGxEaEZZMTZDSDEyODNuenhnbVJnc3cKLS0tIDJyS3Z4Q1NYMU4rNEd5UHRHR0Zp
            dHd0T3dQRGMzSFdCbTczaWNQV2Yrd2MKepJfAofCAu5mQl0sCbpp63D72cRmAJG5
            Wp0FKH87yvG7OZgFggRgGuaasr04RkCn7MALkwmtiPbUDCdx4dS+tQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU3Fab0ZpZWhCM05RaTNl
            a3hxRXF2a09NRXdzTXNvWFhMMkRQRjdhcUg0CkxUdmp2SzRoTVFTRHR0QnZGZ0dB
            V1NDYmZVRlRaclcrZXM4dmp6VjcvWkkKLS0tIExCa2VmSlY1a2FqazlsUHNqcXJy
            Y3Iza0FtOGIrL0FIT1NRd3BnakwwVUkKy4Yr5janXQga8HbspjiwwX+S1XQF6A5C
            aNLnehHR1WgS1SkSfMai1yBfKww6ye5gmOT/LogSFlCMby/V3/FWYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRDRSWVdtNHBVYzhaYjhR
            c2EvKzczbWVibHpDQ0ZxdW1iYXZLZDdIaDFvCk10WHBlSVkxVHV1K3I5SGt2S0Nj
            MUZWRXNNTmJIMytoSkhiWVpZQjdTSU0KLS0tIEVUbnptTFlrUVhObGpTVmxCQzRE
            TWlBcjFMWFkrUGthY0h1ZTNLTU4vY2cKIY8iv2i4qV+S0G3BvJ7Jcn8co4GhxUju
            UQAKHwWiZ5Eoe0XQZz30EL1lmLjHgzv2rDkf0mEZCcKD0Nq2hgUZUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySTVocEZ3NW10V3BUWVlD
            RURDQndhTzUvY1RWbHZZbEJ0WXFjc0lHaUVBCktWYndZT2U4MzRaKzlzWnlwbG9i
            WHZzM0ljYld2R1NuSytkZkg5OGZ6cVkKLS0tIFJFYVlJWVlOZGFPOW96OWxCMXEx
            d2Y4WkU5ZnNseHkvOXNKUkk2dXNQS3cKxz/j50UzWUVPnOzgJiBvE4jP214Uq0VX
            egwPkRNkIO6FRXMcvSBCgbBTzckTnuLWmxQKNIEOHBW2kFTiRpGeGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeTBkV05KZVlqTk1NUm1G
            dzE5VzBId29mQThaUm5aZjMvRFZ3VkFRVURjCm1MYmpDcWs2NE5DSU5CaFhxMmU4
            ZDhxMER2UkpYV0pNeDdZTTRDVkVJTDgKLS0tIDZFYjhBY3oyMU8wcHlsNVNHSUIx
            UnNlZ0JUVzJvUm4yMWpLYXphYUIxaEUKNlrnqZZAQ9G8HH8xDX8kqH6+ntGkpWzc
            l5qWCHoZIlB+SJJaTqUVzzGa6DKYGq6jpcAKTz0IkVMmBnjFPaooDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TDBPZ1JqSHRsWTgyZGdQ
            bVNzYURXZ0hsLzJkakxtc1NHaDE5akpMeEFBCkNZTHliY0pXSFJES1pja1BJUkls
            dGVIWHVKSEd0R2tOeHBWakR6ZHJvQ00KLS0tIExOTXFZTk4vTzIvRTk0bW94OTVY
            VUlYZnZlMkl6TnlRSTMvb3pHb24zcmMKJHYasYFBYHlkPgIuYVHuh9Lx77w0KY1A
            fidqQ4GFHOR4ooQaP0/tQHF91Q0Fqm+NoQMuHWaiKdygAyiJXjqcUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVWxRNzhzTmpLbC9USlJt
            NW9WbHhaM1AyVzdoMUJ1MGM5T3RLWHE5TzBjCnVGZjNMMURtQlJtSjFtditxc1lz
            VElIYk90dTlTQkhuVE1lMEpTdmo0NE0KLS0tIHVaYkNBcmNQN3BCQi9SUkRmeGg5
            dGMrNE54cDRvN3B1Myt2SllxZFVnNEEKN0f4s7gDxSvC2Bbbz4LbtsenH2XOGM4Y
            tU6i28U/lm/FB+04fu0MQKKTeb3jObqnBUBG0mMHoTm6fCt92YG34g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:32:43Z"
    mac: ENC[AES256_GCM,data:OEFdMmyeffs/CxyPVSRttsjikzqCYyoUsWDkZ53oaa6OAzJCxeJ62PpvOnQdoIbLvoVOwdefuO5fHkXxReme5BW1ASOxhccmpgjzbs+tHPD+4JFP4V2dKPS0bLEtZ+f/+/orrf47zrnI4Di9eCqb9qlEECLbCIY+J/RICHTNrNo=,iv:V24IODTWXhDp+mB5lZbUeusayoG17n8dDUMiBKHtqz4=,tag:mHDyaQH7KyHFDNt3AtOC+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
