apiVersion: ENC[AES256_GCM,data:64Y=,iv:F1ot354emJ9WLJpPzuwsBjTz8UNnuV8+edD5dNoRkdk=,tag:MH8ztKXyuCELaKeqTGxs3A==,type:str]
data:
    FORGEJO__database__PASSWD: ENC[AES256_GCM,data:e53NflxulBOpBb+yORtTwCnchIY4v1iNqqjmm6KSsvQc3byWxlwlprjcZrc=,iv:jpxyRxqmqfuV5P1bueetnEYZdzNiaXVoHRomZMnvpHU=,tag:slN/a4nMA9gVt2U2ZVC14Q==,type:str]
kind: ENC[AES256_GCM,data:tHmVMDCU,iv:Lh84BCNh3bcHZ32PculHN0ebqQ344Q9RzfuMIiCJooI=,tag:BQE4waPKPWBLnYfGAVtkwg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zh4FrdUdIErLkG4=,iv:vtJNSUYAYHaabGL13gSfQ3C1Jqf5XtuhGeuOtJwhXys=,tag:GjtKHKsYTDZJ7wIYqn/kHw==,type:str]
    namespace: ENC[AES256_GCM,data:J1CIWk/5uA==,iv:Xcj4MZbbQ4rN/PqNx6+K6l7N5j9ic6eIZ3LqGlROJwE=,tag:e2MIZu71WxyeMonPoucyBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsc3kzZ1JnYlFnanhQNzRu
            TGFOazJvamIzczhhUzNRNHBEY1BGejArOEhVCnhXNWMrVHpyR0d4L25PdlVwWTlj
            ZkwwMnFtd1lUZFhTQmpHVExhZkd3VVkKLS0tIFNaeVhIRmJFUVNSL2hEdHBJMThj
            RDdRTlJDL1ZlNjFLWjBKY1VibXYyODAKY9OWkfOLquE7Mt3lFISumfsHnLA88FH0
            d6eVaJTNWaQQQ6qKVqem543IKCMIRUIHbOb6pBZT94zjjyoXzXzzBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUHVRL1p6N3VvT1R2TWsw
            ZGF0VXJMWUtjengrazMyNXNpY2grR0pWakZNCjBrOTFYbUN1Ti9WaWxtTnBsSTJp
            NENwNDM4ODJCUzBYa3p6N1czOGd2VUEKLS0tIFJBNkpNQ0NCUnpoZkdjdWlHNWlj
            LzMzYTBvZElyVTlaRmVHWW1INzByYVEKtaTz5i+ikbsH+TnlSh5ik8OiOYlnoZX8
            eLgi2zvg5Qsgm9wQvL069NmD8niOAtRZ4q/tuHyDy2By3KeceWhbwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeTFDaU1EcHlRWFdyR2Jv
            ODJBQXBkRXZMUElMV09zWk5OMmJDSWVKd1NJCmJ0SWVuNDkyOFZkVkZaS2kvVHQv
            TlFpKzRQbktTQ01aOVFyTVpSZkd3RzAKLS0tIEk2SVVFWnFvVmVpOWpxOFRhYVFv
            UFd0YUQ2WTU1NDhKbDNRelhUTkNJTDQKfwNLm5xKbBrigmVumG092ZjDZcWDw/XE
            ONoJsICHJrHvJmj/O80WkdIVL/y5imVI5B8A/GPG2hgnaxdtMFQQaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bzBvQ0lMYjlVMlVFK3lu
            Y3R1eUZoK0F4YzdzaTBsK1BPQ0RKQTNMODBzCmFlcFJvY3doMTZBQVZsbWZ2dEZl
            cERKdGRhWHVYbUd1QlFUY3hvVy9QQzQKLS0tIHI2MXowc0lIWkNab0Y4WkN2L2No
            VWJueXlXK0xLZGduSWg3Wml4VjdkSTAKfIUQv2o6981WUgtFLIkPbKb6sNkiPnLa
            dDlwNWEajEpymyetagwg805vg1KUzJGlKIvCQQKad/oXrCDbmZ6Uzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRHBISVpVVzNQbWE1OFI3
            YVpSaG9yOTRNUHFINGxJT0ZlelM5bTRROW5NCkNuYW1QWVlkcXg4azdldFg3dnhW
            RDhHNmhqeTlrOE1LYTd4VzhJTE5RdWMKLS0tIEUrOUF2N0pGOGJPT2hqeHZlUEhw
            a3g5eE1KNEIyY2s5WW5jdHZOQTFTdWcKcY90nDbbRB2Y0gju8Mx5QeVW1Z6nrYmY
            RGA0BKVGwaGLF1FElOl8XQx8Ctla1Hgg9OZTwNkZHL98JZXMa2EOkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSE5IbEs5VklYc2RaMDhm
            Y3V4UCtWZU8rRGVDK1VzMzlMT3VBMUtDOXlvCkZZditKOHlmY1RBWXppOUNFM0tN
            NjY3bjlzUUg4VnBUWWxRajBKZGY2dUEKLS0tIG03em1LazVEWE5TT01XWVZaUEhi
            ZS9HaThNK21VQUN4TmlIeEk0UVY4aEUKsGhRGcetfDNcxgsXAO6xPuttzIG6HSxm
            x7kHas6adM3WuBBANEHw+A9h8RnPTID9x5x9FAr5qmfct472lUcqqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQmIvSHVYUmdBRldNMkdn
            VUh4VFVRTjJnTGQwWklCQldwR0xnN3QvQzEwCnN3aFJMVVZPQmo5RXJuS0IwNm90
            WkRSMXBWVDBNL05SdWhqbHRGcDlJdjAKLS0tIEp6SGJ0aWRmM1pIcW03WXVHck9P
            emhoUXo1cUk5N3k0YXcrRGw1TUhwRTAKez6fBFpiv68Qqo00FiRHoGVIbBs1reTv
            hiS3WKuXEyduSQSIBZYs2rYVKZNFwRuE+XR70Q0HQn8q02eCqoXWdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYkJWaEZuNUR3OFl2bmJh
            dHVyaEJYVjkxNnQzdUdUOHcyejFEUThOdnpVClVjTVdlRXc3TExPMThWOEVET1Fl
            M3JKczR6OXNFV3p0ZnFaWlVlSDVPYXMKLS0tIGR4WVFwNFlUVEtGemIwRHhVRVdj
            V3crNVVkMW5hUGFxRzBNUmdvYTlYWGMKAdo897Z2rTG2nEg4dUGc7X6GMR4KZCDm
            UjGnh6gmI/hmkweOw0z0sP6G4FfnrWspkdQRSLjs8jAPJzAPZ5kx7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRHBLODkzelU5OEtTZ3FZ
            TFRnNXIxSTF6eFF3RzRZUGs3ZElqb3ZSVlVJClJPMlR6aTFCNFd0Q1l4bnI4eG9I
            b1VlTWZzTXJObTQvTEg0RDAzTmtDSmMKLS0tIE1tVlh1M1ZJbCtXWCt5ZXhzMERH
            M0dSaGgzSG9kRUp6clZMK2pBVnJNTUkK0vWyzjIcZxseMMdWC9yO0ZuHsF73+KFR
            kO4F+jQcOg/Dzhzq6hs9eM+CnMT/2rVi1TqZiFVcFOPV3aacTewBtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc05uU2hpcGU2SEtHMlVp
            cEppcWpBWlhqUHRoV3N6S05hZTBKSmRFdGhFClRPZlp5TEU4RlFBLzZPN2dhZ3c0
            ak4wVkxsZUdqRkVibzU4NXBwK1g0SWcKLS0tIGlOam1nZS9XSFI0WFNJb250Tk5z
            MENORmE5cjhESDRzdjQvZjNYWExnSmMKVKKUbfrVg5wgWj99jYe8jctG10lgEvN1
            98QABU2FG+ZrbCx3yYVwqiFkmyHkraHszkX+xMf5RLN1068XJS70rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHK0RvcWVMN3k5eHpJT3Vv
            bmdFUTRvR201alRHVVNRUS9kend3aU8rRjM0ClNiaVRESllkWjhiRi93K1NWYU1a
            UHg5TGprZzlaZGJGYWt4emI0RlZVY2MKLS0tIEovcWdJOWJUa1VXYU4zQThqTTdG
            bGY5YjFJMkNUejd5bUVPU2RUYVk3dHcKgYQr3i9aF7cg5jbzPiSx1nJ7j4dmhJ67
            qk9M9PqdI6UH0w+fax6pnK7IZw/Mnf6al0GNkhJ7sHU7FQ3q3imImg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWldSYnF0RjYzczYwNks1
            cDdlSTByTWxSRmVGQm8yM3NnV3Z6Y1hzdW1rCmx2emd2ZG4zUGVZcmFkbktzakhM
            aDVBUDFnbmw4WlZ6cWZsZXl1UmtCTE0KLS0tIFV2d0h5OUk0b2RLTDcza05seEtn
            RFlkKzZESDFPNU0rSUF2SHFNQmFDU2sKx0qdofJ+3x297m3ZrzPl4NjV/bleTJJL
            J99ZuAXEFD0aa/dnuQ8/dB/LLjjQZnTCVl3mTc+rE/MHYb3Xy4ji6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:s51cZG+74+W6EyuF3w+SeyDFr8Ui49lusTC7grzNjJ5U7vaJ61a1zwzRuudd+nUPfo46xA7DZ8ifUFTxEy+wl8DrX3h6COJU+PtlrMsHjDts5wQ8Pa9TkJtCSguD2OBPYWdxZcBdYuxkvvtgOHTn0gdVJ40Lw8vZBJbiC3f3NbE=,iv:Pakzlcd23lZDLGAQV/O/9PysUs0i1xBk4BGp7ZF3kvI=,tag:1UreMQG5+VTRm6Tv1PrPdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
