apiVersion: ENC[AES256_GCM,data:JxE=,iv:rqRXjXE4S0T4X+wQ4UUVFwSMfuMSYyWTHLmiapoefIw=,tag:TFoCM8T7RURfWm1/72dNvA==,type:str]
data:
    password: ENC[AES256_GCM,data:Px22utUQEHwBrolHug6PwY5z4SkNk/bh/n9X+cayAln3zmIFAVEpfkGyfEE=,iv:tbyoDTeDli5OIjjx+DRq8wzk0mJMuIUflPylklbBfkQ=,tag:P+w5s1i1WgL8tomttk0k8A==,type:str]
    username: ENC[AES256_GCM,data:4jtw0NZ3KMo6ednP,iv:Mjheb/3jedQejhlJOilbNZgi11P/Mtsa2nr9VHXP/ww=,tag:cgP75qW7GfNJcvwxUKYOIA==,type:str]
kind: ENC[AES256_GCM,data:jH8YsWyD,iv:+lIa7X2dywhnBGBbUr8ti5h/LXka5X2M0BRL6gWUrGE=,tag:JNnnsPt35CGz5tJINRaNjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4K7tfJSLVAMcwOCIU4flEA==,iv:t4ntn26+lAnJ0qCWRPihWaNgyLEP3qEHEo3gwrkvKAc=,tag:f5OwghHtKKkAP6z2qdx4Gw==,type:str]
    namespace: ENC[AES256_GCM,data:Rd+Q453qBNBurHY=,iv:pU7RcUEUF+sFVY21ek3P/mgernir1Lmjkf8AclirefI=,tag:1GR71+WQPawMfVXRoypBWw==,type:str]
type: ENC[AES256_GCM,data:Yanckl8APFjE/FHldhP8quDDC6sF60IB,iv:13I/TCCVnxtJv2nnlG/09oO05XLjq78gF2ZFqxqg1RQ=,tag:opwr5UR0y3o+FfOiDnvYmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVFZjZjVjZjc2WTVoNkZS
            MlpCM1lOdUVERE8vai9ubEhUWXJ4Yk5PQms4CkorTWV2THYwY3dsbmtvdzE3a2JM
            OVVvaWV2cHp4aitObU43RmVMM3dzZFkKLS0tIGlYSTN6RTV5R29wK010TTRQWjlo
            dTNrbTdiUGk1Z1kwVFFpaTZHSnlmRDgKm5BEOxXK9pHznj1D5QoD6QiCV56Y4iMH
            r9Fh1h2VmB00SD20xqurJoJUvOdYwVFgnt2J2nZWy/a7y1GgiuplQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZ2pUQ0lmNVNpSTlzOG5p
            Z2NxOG1KNGx0b3p6SXVNRXFrMHEwcGFUK2hjCkZYTFhGRWxpQTQwekhoQUhDQUI3
            b01XejB0VTlCdjJHNXZQbGNQSU5pNncKLS0tIE9BNllURzdJUldkUWE3Y05PYWZa
            dnNubXhFbzJoeW0zSWpGbGJxODRKTGsKHKKtWFJVwF7jtyPGrr2YhcL11/Vlw3wv
            L5QiAdhCBVoZIbRvHIvdZzCfC6O2qoiDDK0zuXGEweSnB7XqBBMVVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWc3RUUmRybnJ1aGtvbmdO
            ZGxOM0tJZkxTY2RibUkweXdlbUZaRVN2enhvCnQ1NiswTDVhOGJOd1p1YkZaNFVu
            QmJxc2Z5eE94eTJ5NXVReUFTWTdGcTAKLS0tIG9FRHNwUkNoOEd2aWhIT1VvQkFi
            d1lhSGQ0RG9UYjcwcFNlWGJNWmJwOXMK1FmN1zQeb9LXIpB7EJy1eMT0M4Ua9rTu
            yUzQUcRo8nBpCXL5YXXz0O5tVQ5KzLjQhDrrwmM6tJbBGscQt6/HwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLb0dvbGhqYktxSndsNFJt
            eWlMOTdZNGpuWEtGSmxid2I5SVVKUm1uQ1dnClQzWU4rMC9RT2NUZGd1ZjhwVUFN
            UUFhQ2haTWVsYzFua0JMWEtSUkZRaEUKLS0tIGV0U0FuczZWcDFJNXZkeW93NVJJ
            NDA1Wmp1ckt2c3ZWOCtyMlQxTHB4MDgKTtgzAjxl2Uxw/p99prtstzLt9ajmQsLk
            JtwsCLZDjjblI0j9HCQKQIbRWNugHFi+Darqbr0kUP7byTxc9ZPX1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eENjTXNDL2tSeHNwanpP
            US8wbllHNzNsa3J4c0lFRUNQcFhDODlIUmtnCjRaN0hXY3cxWUFpQnJYTnZNQkwz
            MjNRS2N3K3FGN2pvcTF3SGZaVGN6V3cKLS0tIE12aVg0TVpSSTFpMnhzenFxTzJj
            MUlCalZpM3dwY2FIZXF2bmZXa0I5NTAKixdnyP51VTcG79BFQG04U/ssIPihDL7c
            ntZRgYn/741Gab+4kxULqgjrB7fQazXaDrNOR88oxAoKhidf0gqSQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcG9xclYwNjlkSVlPYU5o
            YTAvdDcrLzZzajEvRlZCVkZpcGVuNWNOS0VnCit6UEtla25wbWlrRnUvOUI5b3NN
            LzlkQWc5eksyZHpvUmVGdG1nem5vMGsKLS0tIGdlS2NvV1krOS9IMmMvdWRyUWR3
            VEt3RDVkVEMyQUtKQ0plYjBwMDZWdmcKctd1XswslFfr7jzp6wda8342ZlKqpnH/
            Tr4Ki5c5Wh1k3oYjcMFTza34f0+pPWAw2lvik10oYPFngOHPm8j/KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRd1hSU2VBYXc0RFF1bzRn
            NTFZRXRzQU1LcEtLTkNFV0gzV0VtMm1xVXo4Cm5ZYlU1TDlqRGZHOTY4czV2dUxY
            UlFySGd0V0xtVi90RTJXRFhGb1RVRkEKLS0tIEVyZWVTcWs1OHF0cHQ1OVJNVkNY
            NzNiMEd4VjJ5cnA2elhIMnZCUjBhSmsKxxZN9ep8TJEjA1+JX3u5SvcGXll/Vral
            ATHvi0Pw5lAIg1QRR5NKbl/d/3Ey0ipZfgAqp2uhlIW0EknEE0pFMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQjJ4bUFYdDZCbXZ0dzNp
            NGdldzJDdG12YnlSMHpRS3NzK0U0Y0hmQ1RZCmZ4NE9XUzB4cVRZUHkrei9hYVV1
            UllZNjZGRS9mbmNQZnFqL0tlSWRCVGsKLS0tIDNXYm9NVVF2eEg4LzNqR0wyZzFN
            eEJrbmoweDkvQkM2eEJoOFBUVjVVemcKnbixIMFpviMt8N0vxd9iV2e1zDeWPY3E
            UWOwH8hJkQcjSzwCA2YUAuCVHGpdZxlM08yvTa4FotCshQWKgJ2wBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZFhKUThRKzRsSmZDenps
            RHlsZEg2eEdFMXBuVGFMampqa2daalhoenk4CjJNODZVL0JEclhZTjRxeUljZTRx
            TkZNN085OU1rb3NLZ3NHcjQyZmdmaDQKLS0tIFBoMjhZWllDUEVTN2ZLU21QTjNG
            UkpvdVJTeDVNbkNzNVBFN280azRVUFEKr49cbmZ6cYG2pwqICuVDOgla/5OwGo87
            Xc1rZiFutTkidbEKGYUZZLG72QThPB5fmSlX0ypIKrs3xyVu5qNDpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NkhGbnNzTGxhemttMnZC
            aU1FK0c1WlBqMlVDZW9pZi9kbnF1WnRrS0VjCm5PbzVTR0MrbzV4dlRyVUxpYXQ2
            QWhDaGZOQWJmY2lLMmROZk4vQmExUTAKLS0tIGdFZzNxWFV1blVvdDd1OGpNL1dl
            eHdMUXBJS3Z3NlBTd1JLNCtxdiszeEUKM0KY3gDHILi8BjXGwBBqL+/nDPMd/F+t
            BaNRraMj6GQjJNFxtI/S9sRa+KZpKBisnknfmg/e4s8Dkhba1iB33g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L2lIekJ3NkdWcmlrTUR4
            aG01ZCtKWStyMEQrNXo3bzJNWGlrdFZab1FJCm9ZbE5jQTF4amYrSGJobmU0TktP
            dXArZGZUTElaN3M5RXE5anlWWXRCemsKLS0tIFh2b08wUkRtazdyeEdjaFc0akxi
            ZUpCQ0JoTmova1BJTGo4NmY2Um9HQkUK0aoeCXCsWDyIf+ZIc+fIm/CiQZmk6HZ2
            mQNGCMFt+W0TRPZifsosKUG+zRsEy5AGbzGM14bXs7YWSSAX+Jvo+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaHp3RmY3SFl3MlBVcnBw
            MU94RjNXQ3ZMS0JUL3B3b1RDQlpMbVNMQkQ0CjJFYWxMangra01jNjVoNkxDSUVj
            eFhmaWhTTWFJWXhJVmRGejRFcmorOFEKLS0tIEg0L2xpQkZNRG1heVpENVI0bjlJ
            UU5WWk5MeU1YMGJXUUVpNlF2Y253YzAKlAswJuG2B27Oo2Xs5SbOkfZ8yTLHkViF
            R04Kncw/pXK+Q9i859D5Gf84J57dTWBANKG5QrXD70AYh1ZiMmfMMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWXpDbkxNUit4NUpFM3Jn
            a1FMQlRNK25OMlVJaStCTVM1UXc4bCttUmhBCkFJWEVYOWxGdFVxOStyaWVFV3NU
            Z3VId2pTQXVhcXVaS3VTbFNOVU9ISGMKLS0tIEg2ek9lOGZiNXB6c3NjWTZRNGI1
            by85TndwdkxlUTFqV29VNjlmdWhrdGcKZWYIjE4tZ7kSyD/mXOGGSimVNTNGxfyt
            Q1150zN8DAbRk6Ji3xnfy7jHmFFbklkiUIjcp30V009eiEl2fi/0dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2LzQ1aW1oRHdkZXdSVFpT
            cXVmZ2xKWnJJUTl0ZTVwSlNKVnQ0dGx3WDBZClJwbFFjMFEwT2ttVmRVVXlLWEZk
            ZXV6eWtmWWM5OUEzaGdrTGtYc2J1WjQKLS0tIFh6YytEWjRiSFplcW8wQlFkQjRx
            UCtEcjZZNk56QUtXaFE5VUx5eDJvQmcKml0D9adxAcaDZmgByw3pBZSxlzlW9uc/
            +dluT2d8M1jgP+b0wbOEdcK0ED/owUnEuocemRtm/X3DDsDK+r0ohg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:32:43Z"
    mac: ENC[AES256_GCM,data:OEFdMmyeffs/CxyPVSRttsjikzqCYyoUsWDkZ53oaa6OAzJCxeJ62PpvOnQdoIbLvoVOwdefuO5fHkXxReme5BW1ASOxhccmpgjzbs+tHPD+4JFP4V2dKPS0bLEtZ+f/+/orrf47zrnI4Di9eCqb9qlEECLbCIY+J/RICHTNrNo=,iv:V24IODTWXhDp+mB5lZbUeusayoG17n8dDUMiBKHtqz4=,tag:mHDyaQH7KyHFDNt3AtOC+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
