apiVersion: ENC[AES256_GCM,data:64Y=,iv:F1ot354emJ9WLJpPzuwsBjTz8UNnuV8+edD5dNoRkdk=,tag:MH8ztKXyuCELaKeqTGxs3A==,type:str]
data:
    FORGEJO__database__PASSWD: ENC[AES256_GCM,data:e53NflxulBOpBb+yORtTwCnchIY4v1iNqqjmm6KSsvQc3byWxlwlprjcZrc=,iv:jpxyRxqmqfuV5P1bueetnEYZdzNiaXVoHRomZMnvpHU=,tag:slN/a4nMA9gVt2U2ZVC14Q==,type:str]
kind: ENC[AES256_GCM,data:tHmVMDCU,iv:Lh84BCNh3bcHZ32PculHN0ebqQ344Q9RzfuMIiCJooI=,tag:BQE4waPKPWBLnYfGAVtkwg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zh4FrdUdIErLkG4=,iv:vtJNSUYAYHaabGL13gSfQ3C1Jqf5XtuhGeuOtJwhXys=,tag:GjtKHKsYTDZJ7wIYqn/kHw==,type:str]
    namespace: ENC[AES256_GCM,data:J1CIWk/5uA==,iv:Xcj4MZbbQ4rN/PqNx6+K6l7N5j9ic6eIZ3LqGlROJwE=,tag:e2MIZu71WxyeMonPoucyBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYkVKQkFYK01keDJ4MTVG
            Ky94czBJbGgvcVI2bm5YOFRHc1N2MkFrODA0Cm10bTllaXlsSjlEUDR0c2NpUG10
            SWlJWlFrNXIvMlcwYmVCNVB4d3EvTkUKLS0tIFNTbGVMZ2VZbnllYmt3N0FkNVI0
            MUFoVXo3eS9qQzhiclJKWm14VXBVVXcKGeELyCe9rrI24IMiomrjJHJv1v4+Z1Hj
            cNmFhPNqy3U4qqqpVR3lWd75++Lrm+w/mPnDRPAzRyP4J3hMvXSYZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTFczcUxRR3hZeGkvWnFT
            anVsNjI5dmIxRTBaeVFPbmloc3o3RDZMVHdVCjdhZmV1akVoZGlHOFJaK2p3QlRR
            VG1rbXpLUHlBc0ZjSXRtZW81Q3QxRTAKLS0tIGVHd3Nnc1Y0Tmh2RFIxVG1JRHBJ
            RGxKWjZDV3VtV3pmQWx2bW03YTM1VjQKgz8b6Rzttj1PJQ5wunWZqVzPN9IYOEAo
            JRYVEH8rRE7ZPw1DhrmEsOhtuRDZ8blO6HjgmKURlAaV6NlBaAjX8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpcg5t420nf72k0c9rrx7amg0szch98uzqu273exj7lw3yu0j99q6vcckn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybWlNb0dSaVBIYWV2Y2Zv
            SVdzOEk3aVUxQW4xL2N4ak5tQm5BL3NGYmhFCldPemxuYksvVGc5Wi8zS0IvSTV0
            bkRKNjQzRzZWbW8xQkdoUko2OEY3NVEKLS0tIEdxZXZ6VVEzNzdyeU1sU3BxRDNq
            aXhVR0ZzWEZ1ZFhqek15Z2p6dzNkYkkKV929TF8eTELIeyqZQS1fd/9OxnJM6jVq
            mzRLxmBLzFMpGDxL9urGjDiCtJ3xIZP8m+VHhEa4bOVcYuSFJXjuCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4mzwe89aqgs56mn8zg7dd2l623kwmw80k90wr2sa6dnlcdmhcnsp4kt54
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSmxoZ0FEVzJuWXVSZVhr
            WklpVXlIVmdlRE14RTFaR09UeHZya2xKZVNNCnQzWjZNTVA5RUxFNkM2THB5RXZs
            QU5WdFZZNDFNWXRYTHljaUU4YVdsckEKLS0tIHk0eWF1K1lrWTgxdjQ1UWNVNUV2
            T00yeVVRdFhYbHBpVkphTHZCSUQ4dFUKLul0Rn1+uerFHEzWzFhg3GLj7WRpf3mX
            0U8ztXLj7b+0jz+Q/4aaxZs1GqBP+YlUsQRRqrlHgbAC5akdF7arcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwREkxek5SRE93R3RLa1pp
            WVdSOVpiRGpvcjIvWDRaOGc4WFJTSHZQRGtRCkU1NThVUTgxOVFUV3VVNm5CWFVX
            QWJFTnhjRFZUeURhdkl3VkpuSTlpUTAKLS0tIDI5SExqaVBWbnhuWVplRlZlWGt5
            ZTF0KzdEUGNPQytTQlA2M0g2cmRTZ1kKYwq8Ygz2/EOkmf9biHZcPnh8tDGk+ckW
            LnBjxgZ1J47RM0cso6NBPCezyCap+HRlYkoYMgRsyx6oSxFx2g4nFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYjM4WGpYVFFKRnZNdnU3
            bUlXYTlSSmZGL2M2aW5ZemllQ0MrU2Z5YXk4CnhIS3JEamhwS2ZDZXJ3Mzc2Tmdx
            SWJoTmFNZnBlbkRRVytzajJwRUFXTTQKLS0tIEs5WXZkcVZtbkthK05mSU1TcUlC
            OUJ5QU56ZHR5U21GZEZMNGxiRmhleFEKYD9akLZf6btMsBkbI4TPRoEcNbW7NVeG
            Jn1Yjz+f/dBKtpHS9cH6yiX4FlOhGXzDdWGupVwP6X+NyXU0Y8SBGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdTQ1QThieXJYOG10RW1j
            dHVtdHhxb1VNV0s2U1JiMlRTWTBFSFExTVJZCnlWN3BMbUNzcE9vTlFDaFVRS2tS
            U1JzVXhCNklvSHRINnRsdG1GSUFQQkEKLS0tIGFCaThIS08rTUhhRFp4ZFZjd25X
            VEp6c1k0c0ZoMFljLytXYWlrZzZoOHcK810E+Ps6Rf0Yl7J0SSPSW3fwDdyBt4j8
            pEXlLk8qpwLl1/RWWpfQumvG1YLDS7h2/huJXfAUwxpjmDGJEn+BdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb2ptK2EyQWZ4cm1GREFn
            N29vcDVkZmU1M1Jxa0VNcENxQTAxcldvR2dNClZlYWZXRnExSnFuZTUrMmVjQzBX
            bng0ZERKejg1VzY1L0FIZU5GK1dGY2sKLS0tIGd3VUxQRHM4QUFYUS9MeWtoM3pR
            ZC9DRmxQOVZ2Sm81aFBaY24rL2NzZnMKzhYMX8AtQ9z3sswsuCbG0MtVSaUrdC9W
            vn4st913kf7DUuCbcVZ6pJUZZCU7FXkFxY+2y6x++7OENvUGKZj1iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpcyeqjcl8j0dd4sj6f0vufs2vpus3xn4dvxe3cr8g8rgcm0nfxq03ds4y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNHBVdkdJYXZlUGk5NkIy
            aFQzMHZKWnNFMk1vWVRLWjZVcWVtNGJ4b1NJClFrbmFQOVpBSm44M0svcEhDQmw3
            NVpCczhGZlRqYU5MSDhxYnMvNENSSWcKLS0tIFhWUngrYkdYRm5NbzYrNE1odWlh
            R0FJU2FoaDZ2eXFLcTJvWnB6ai9tS0UKpKJIdDA/2vUT9gHmi/Q2d1NAfDHiVFTN
            c5TaLihQEHy2rt/m8t9mp/bAGiITCntuR3jwrxX+pmc+pjVcct8kzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4emRwY2NFaXNFem9yU0N3
            YVRRTmUrb0dzazg1dEFVQjZpaURpc014S0hNCjY2SU1MZXZOVHJIK0J6Y2JJRmRS
            UGNoNXpKZFR6aE9vUFo0QXREN2MvZTAKLS0tIEV3OE00dDl4YlBMditIbUxZMDFo
            Z0lNS0s0blhvczFXR1phMStYcjdtZ2sKIjlCQ5F8zepKh6W0hXfn224Ir8cTJoS1
            aAx+moUut+b2qaD9+kuzQZBHkbbl0rO71TpPwAO5Z0Y2b6MxPPOW8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TjF2Sko1OXgrNjdqby9T
            UVRRL3o3U0lBNVcyODJuZHJ2Q2diSk9Ycm5ZCkhVakptYkJKWXBtRzFRLzlrN1ht
            LytlWXlhVncyeWhtdW5lRzZJMVNaUmcKLS0tIHg2MnZYQnhhL0FoeUpnTy9aeUhZ
            R2lDamw1WlBxcEZESFJSRjBkMUF4VUUKC2ihqVX+nuC/ejqtfPIOqoRxI07wA/7g
            UsfplX5+BOE6KXrX3nNeiPl/Kl7cRVZQrgWsCP61OS1q8kWvwkS15Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mhrzghrmprq387xqsln6996yx3ja2e2zpamh9mtuu9zqmxahunqg9qugw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc09oVUY4SGw3ZGxReGw3
            bXhIMmUyN0drOGRvc3hIRmJUK01CTFo4M1JzClgvU3RiVllJUlBscXV2eXAvY3N0
            cE1zeGZXR3gzZ0ZSUnpTd3p4N3dSSHMKLS0tIFdjQWNhbE45OXlkRzVtaFVvZ0ty
            cXozZ3ArSEJLdFNxL3k5dlZaVnI5U3cKucs4fnl2ZK+uZs/6s+gfMJEQW1fDEqlB
            7Rm/w22vzvN/tGaW1YJ0imDTuzZguYzkRtD4QmHhCElu+asrQG29Aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVVUrcElqcENiNkNaUXNi
            Q2NnbmJack9EZitLemw2VGw0d3ErcnZ4RGdnCmFiS2NJamI1bGcwS1plZjByU1lE
            UWNRcXp3czhmN3VUTTJrOS9iMmtJcTAKLS0tIEZrTUc4S2hhQ0FsS2lHYWVPa0Fi
            d1NqRFAyZG85WWhRY0V6ZXB6OHFYTGsK4yqyajslfYnrtoK3O7DT/B1nGJa/oBDN
            4Iq2YsFGGGB985g+v9gSZ+ePhX2VqOBTUaEbV4BFwUbrRlmDmElKxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdUdiWU85REdIUFVGWXNO
            a2ovc0dNQUZySGpmWk8rc1Nsc0UvR0RSRlhzCjFFeTcrenRiaGIwblFza081bzBk
            dVl3UU16VlcwQ21MWEtHY3AxN0hOaEEKLS0tIG16bXlWWm00WDB4d3hldlJrNEN1
            NFc1MjZGWUxGV3YxK2FoanpwZDlYN00KptP378uz8V8jniUpfSqiCa/SLs6+FWc5
            205oTf9LbFqsSnKFUPkM3lA9RuoIV/02118E5CZ36XHY5bIs5dFjAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f9hd8fu0694rc3tr6hwxz3ldfpepref937rmvqdxvvsr0kfcjdxswyzvw3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcFdiZUh5VFNoR09kaWYr
            R0t5WmZZSGxHTC9ueURsWWhWRnk0Nkk5c1VvCkM4bGlwTmp2c3UrK2VES3Z3VlJu
            cEc2VElHaXpzMzdMMW9UQjNzTjNDeFkKLS0tIGlrc3RXSy9aZ3JWaktSUzRiaGlR
            T21yZmZPV0tuZHR2NG9RYlgrNmVFY0EKl8I1Mmst025cdMoHpDSgiN/fO8/PAtBt
            TqcNPoZtS1K+t8wnF9VoP2Y+iBgFSGT+zq0NgXxB8Uv5zG6IiOyS9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWTRtanYyenJNbWVPMjR3
            aHQyOU91RHQvRDNKSTFKSjNsQytOWVZpZHhZCnE4dXl4TmxKUzgvMzRSVUFmbnNG
            dENPQzcwNThydGJCeFRNUWR2aDYyckUKLS0tIFFLVm40N0hIbk5peU91S3NWUUJN
            aFNIRXVkeFNFV1hQY216akV6UXJuN0EKdKKDFgMH3xhCUD4Y38vNw/kwxnVy7gXw
            bMNGvS9egLCZ2pBgnttoo5NeKpdZSidnhPbQDbdsWk7B+fqNBFrFrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNFUxWCtqdkQ1TXRNMzA5
            VWc4eXV1TVhaREprNzNMYlFCcC93YmlFUERZCm50b0ljR2k1dGs3Z016YlFoVHgr
            eld5a1QrM2NQb1pVTTl1a0Y5aEZzczAKLS0tIHRXSUI0UDRjVUh5a25ya0hNMTlY
            bGdUQUdrakNSUWZndmVheVErZTdsMlkKNdwhjGl220sPx+PQWLPhF+tbAwuQQ3Rp
            cBf3tj1A9rwSWsnvQMDEuLhTboiHonj1MLRG9MDE2v5XF7mkeOVHLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWHJwTm9tKzlQNVdxcGtB
            NDg5R3hBeHdSMHRldWpUU3pwTUlhK2M3SzBrClhQbDEvWlAwcGJZdUJpWVJ0d0h0
            cnZpNGduMmZkYjNWUktTcTF5RTNUcm8KLS0tIEVJRWpZRC9keTZESWdiejFUNGk0
            U2VpaFVsTU1QRWp6M1RCQUdZYmFwRGMK9FnMZp5fynyrLHEogYdkX3mAzEJO4Sxr
            cU9BkqAiZg9BUPJw38w4dZiOgyy9IO5V9aE63hY7V1mRvVGURg3eJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRmJ0N0Q0MXFRQkhET3BW
            b1V1Y2d4SVZQcGRrYmFYZkMwL1pRUTBTK3pFCkRMSTlpUGZNWndKOWpYak13Uy90
            OFVOSktYNkRsTHo0dDVKMUtuZ0FsRTQKLS0tIEc1a1A0Q0xsSnl0YjVhdnBoVTBP
            bjMrVmxsTTVxcTBRckhjbEFZdmJZZkUKkNLF6gwrnUXaoLGhV45SUIlv6wMf/hHb
            JbRhNm924kzEaQ2Qe/COGCMHjuvIIfOlhvn5erpJ45OROrq4c+HxPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sukfru07msq8fm5ddgym23yal9lfm99090p999p09mxgrrwh9aqs6zp4fy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWEc4ZkdJSWZ6b1ZodVla
            ZUFKNE1SVUdaY0ZLaDJVdiswbXg3azVJY1NrClVVNFRBb2VoUHdFUGxwL0xUQTZH
            MUxBR1BORncxaGhxM21wN1paQlFqWVkKLS0tIHdNbis2STF4SlNMeWdoZGpFYXRs
            UHZxNFdRcVlqbUFFZzcvMlhheDZ0LzgKIX2HixKw7YuBcGIFXGUaOe77FmfNM9Sj
            UB//Hohi7khAl43Kzy8XKPPcpLjKqZMztT3FwcsoahIVFh7xRtiQxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ephzrpgftmvq4cul9766q2r3mss38xu6un74ryfmw0729afysghsh0a3qg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VUlwelhBZWdRZlFja0RZ
            bXdyNEFuOTVWU3VheWJyNW9RMm1DQ3JVd0RVCjBiUDV4azZNdTc4dC9wZ1NWZUFv
            SmhQYlJYcE9HQXUrZVNtUUNNaUdyM1EKLS0tIDRBVXJ2cm9qK3grTzJzazd1dGs5
            NTYyNHg1TE9uVFNvZlVDWHQ0bFRHcTQK0Kez7IdS8SXoawjFMZousz11uhbiqO2+
            zKKq5W3/TbHJQWXswWVQXvcnU16qtlTVUnXDlGQBRhdt2N+x/+xkMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQnQxWjhHQU1ua21GSkJ6
            blBTRzYwTFdhd1AvNVY1RjNPaGROSm5zSEU4CjRzZXRya1IwMnJxVldxRUV5aWl6
            T0FTRjc2NWJkRlcwMHp1R0x3aE1ZbGsKLS0tIG15Q096QWl5K29aWUY0d1BWQXE1
            ZHB5TG0yZWV1K1FyWnVIRkNpN2tjVkUKDkeowSfyusB7cgtW6rqChxArk5yH/V/q
            voNqVP92MJ5SGOirrwMGqe/gvZ5TQ0/cFnsbCVhbWcmeEFCNikzBJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7ecrfntus8rvyprzhffjpqk2tmrc259knf9xqajlrqvewfp8d6svwp9pp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS1l5RDA0VjdIWFBrM2Zy
            M3hoYXVCTkt1ZHl4UTlTaVNYS3pXU1lmZjJzCm02ZlpFc3ZzcjE2RmJWaVlOcnZn
            RjMxYmZZRm9GaXFMRVpoY3FKdE1EdXcKLS0tIEQ2cVZ3VFlYVE9WOG1UeEx2dCtL
            Y1VYR2lKR3pBbWpsMEZ5bEV6eUxoVTAKE4fOhC0e1WKy08IRddwKUaij3kkCB4Hy
            Hy8jGyhBr+1vtATl4/2AMYYMkyI55GHEdBV1d6W575Y2NlnJwewQMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:s51cZG+74+W6EyuF3w+SeyDFr8Ui49lusTC7grzNjJ5U7vaJ61a1zwzRuudd+nUPfo46xA7DZ8ifUFTxEy+wl8DrX3h6COJU+PtlrMsHjDts5wQ8Pa9TkJtCSguD2OBPYWdxZcBdYuxkvvtgOHTn0gdVJ40Lw8vZBJbiC3f3NbE=,iv:Pakzlcd23lZDLGAQV/O/9PysUs0i1xBk4BGp7ZF3kvI=,tag:1UreMQG5+VTRm6Tv1PrPdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
