apiVersion: ENC[AES256_GCM,data:64Y=,iv:F1ot354emJ9WLJpPzuwsBjTz8UNnuV8+edD5dNoRkdk=,tag:MH8ztKXyuCELaKeqTGxs3A==,type:str]
data:
    FORGEJO__database__PASSWD: ENC[AES256_GCM,data:e53NflxulBOpBb+yORtTwCnchIY4v1iNqqjmm6KSsvQc3byWxlwlprjcZrc=,iv:jpxyRxqmqfuV5P1bueetnEYZdzNiaXVoHRomZMnvpHU=,tag:slN/a4nMA9gVt2U2ZVC14Q==,type:str]
kind: ENC[AES256_GCM,data:tHmVMDCU,iv:Lh84BCNh3bcHZ32PculHN0ebqQ344Q9RzfuMIiCJooI=,tag:BQE4waPKPWBLnYfGAVtkwg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zh4FrdUdIErLkG4=,iv:vtJNSUYAYHaabGL13gSfQ3C1Jqf5XtuhGeuOtJwhXys=,tag:GjtKHKsYTDZJ7wIYqn/kHw==,type:str]
    namespace: ENC[AES256_GCM,data:J1CIWk/5uA==,iv:Xcj4MZbbQ4rN/PqNx6+K6l7N5j9ic6eIZ3LqGlROJwE=,tag:e2MIZu71WxyeMonPoucyBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaHhpc3dMWCt2VWlLK3Iy
            RHNnanBmSWhEOS9QbVBqODRPVmVDZ3Jvd2g4CllJTWRlL0ZrdVRlTXY3SWtJSS9G
            UjR1Q1lUMDh4M2NyQTBsK2ZpaWlKNXcKLS0tIGhoSmd3cDdvZUdIRVVmbEIvNFVj
            TzVUZW85MEY2RzRmY1ZkZnk5LzNuYzgKKN5nGzq+rMci+4u1AuEySLN02rSFb5MY
            YFCP07zaw2Nl0i74Q/fQ0vpdxZNOrIcfztSuozZXtuZ/TGxqGWe0+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUkRiUzN3NExCVVV3Q0lL
            ejlVV1lHbXNSeEFSeGxlWkdPaWtoWUlOUzMwCnZUdnErUE8vdjVVWmVVeGRSemg4
            K2Z1ZGNqV3JqQXRlWExkYTlZNzhMMVkKLS0tIEFJbnc2ZEtGTU9JU2wvNkJVSkQy
            YTVyUnlYRERWM2hzR0MyWU03eGhkWHcKA46UcA+ypaRbM/VWuXOnkMxE7CLZ1J2P
            yOSyxDNR71iNqgsjlAnptp5uKpaEj+veQ1y/qAYfvyqM7lJ7wVKMTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTXlyZllLL21nZGY3WXA3
            ZG16b0JJQWVGSis5a3hGN2orZnlzYnlSdVYwCkJQeFkvelZ0ZklValJSYlFnRC9H
            VURjeWgwNFJRcUJpWk92bnNGNnVqdGMKLS0tIHRSUUdzTlp6eWtJanh4QWxlMllC
            Mkc3VTBDa3JJNXFEU20zUVd2c1I5SE0KcQ0zH8vTxv1phywWPlf1Wf9vaZ15OQgq
            8Fea0RR/Wcv2wfll00CNqPmfZpgpefzoNmGuH34cqym6YsQYcFyrEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaDRjbmZyYWF4cEpTdHV5
            Z3d3RmhXczN5RTNwdnUvTjBpeFJSOTM3alN3Cit3Q3R3dEdrMFo3dUlUM0JMSk1x
            L2tyWlZWZ0dGY2hoYUJOdUNOL21mdEkKLS0tIFdWek9CVVFvU2pWSmt5cW1xL09P
            cElWNlZENSs3SGRRT0xQV0RDMDVmMDQK/QwZDzJCMHOUKCRR9SYdOGMW3g7v53ks
            g63fMUQ268mF7R674HUN5yh+lTYWDiV6mUhPYSs5OLKvEqSg//SJnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeFVuNVJIVjNDVGU5b0Ry
            Nk15Si9saCs4TE1UcjUzZ2FhaSs3SnhmVzNJClFicTdEbEV6Z3UxdnlyeHBMd1Vi
            akx1SnFRT3NpN3ZLenZGRVVhdWdCNTAKLS0tIFU5MDkydHdpZlBrTnlXUzRBbHhh
            bm92a3ZWUTdTelEvTGowNER0RndURlEK3jv7P8OL+MgQ80R/j/3B2Ip77wpuwtw3
            hgidhA+kXaVmpkQg+4ma6OE6J6MPKz3ruzGP9vqVD10MTYDZQ4gPDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMm9wMGIwRGo0aXNIVTlu
            WlEyZHJkcEFjWHUzM3REeGxpVEUrcXN3d2xzCldZaU5KUjh3c0RkdUwxY1hWN2Fu
            YUoxTDc5bzRWWmg0RnBuS0JSMTNUbzgKLS0tIHVWUFVqZE1meFVBRXBDMjd0djJ0
            N0g4M0lqZUVCZTVxNzhqcDJsN3Z2K0UK59u6hWYVCC+1x/5H7X3ntm5Kz+kIZ3og
            RJDWtmxqNDd4+B3gXMHr51mWAEgel3+aL5HrkRx92orOj6GErlsOww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTzEyQXhNd1c0ZHVuelRt
            MjhJbE9VMmVoQWxGY0I4V2xHQ2hYZUtvcmlJCm02WmhsNWxxalkrVzNWdlRPMTRj
            czlYaU4wSU02aDVVeW05WURqaWIyVHMKLS0tIFNFZFBORTZaS0pKTHlUNHZvbUNF
            QVRnejdwaWRHakxibTNZbWFyTkFycUUKMspTbMmLg3IsLn/4IHFSQQwW9mCGX/fi
            ccyt/iTEa1kRMFJ1T/KXmGqcpTdudVnZvnRi8xZPOkurbcSef0DOTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvS2I0c3gxL0ZjTitvNGY2
            VmhldWpGbW5FNjBCaitmZGI0M0NrSEpzZ0hzCi9BdEtocFRkTUdmc1FwbUpoelhi
            S2VDcjVRQVMvQkxrR2EyNE1WTFpHRGMKLS0tIDcveTNGWHJWZkQ4VHZwMDk0UlQ0
            dUY1MDZ0NTB6WUxSdFgrc0RyYmZIUlUKlEYMJYxGFUKCorjBJsSiyBjqsVApMHOy
            ezeSJcIP8qpHkGSijNYjShhyw/IhD/v5dvVTYaIeGBAxM8e5Efq6WA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZjlVNUdSbnFIVnBrMko0
            b2tYZE5JczFOSTIwZE9Gcm02LzlWVE8rYTNJCk4zNHI0QzkvQnI3aFpWYnJEaHU2
            NlY1M0FINEZsZGUvZm1NcEtDQzVTNGcKLS0tIGY3UjFialg4YitqSTRVNWVzdjJl
            M3dTbGZKV1ZETDRENXJveElCaVBXaEUKHNm9r6XYnY+9Oc8XMx42OXQNvASbnOcn
            da9yl5D/EF+ahs87JFx8kp8XcNMkjuP1rZKNbCl3anieBk1ZvJrmbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQm96VU5uRTVRdm9Hb2ZZ
            K0VvZWUvUU1JblJRbjJUV2dXYlNCWCtDYWpRCjNyUmQvcG9maDJXcHpkbkVkditM
            Yk5OSHAwRkZxZlVCSlh1WTBIZkdxdE0KLS0tIE9nNWdnNUF0NENlZkxBSjZOR2tG
            UFltYU9sdHA2Z0dSYzJXZzJXZjRtaHMKB4D5njyfb+TdwX4ZnmCg+Cdw1eMm3ToQ
            Ya95F/Ut4eBa6Ll4GQ3BT3qwsNNLWuEVdIJ9rsIpqtT6fyg3rkjGqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QmxnQjVTRHdsanozZ2k1
            dWNpK1kyMjlFcjJsUVNPSXBiM2FNdVJJdzFJCmVOOHZsWm85dUpZYTM5OGJKcWpY
            amgyK2o5RHU3am15YzdQVGZNdmlZTW8KLS0tIDQ5NTVBTUVNSGwzM1VpWTQ4WVBr
            bjd2VjUzVlNjQnhicWRUa1dqMUtvTGsK1vxFUypynUpAu0TQDEcIsx58JeDdO+6t
            7a5iwwVrye9qrF0pCy54JQPtj1j42GDJTiIuf8DlzY/kViGF39cgnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaXlIK0FOeUdjdC96YTZs
            Yndyc2FDYi9hUk5yOElsazRVZWZ3REtCZm40CmJIS09ZNVBWZm14Q1RQcTVkTzZJ
            NldCdHlsbk1UUEZENWZQRjdIWjQ0bVkKLS0tIDkraGJWWGZhb3h5Yk40cFJ4UDhm
            NFQvOWdaQ0tuSStoUlJESUdaSVVnR0UKA5OW1wn/jxBuysL3gfV0F/N9e4i0cKt9
            D1HViPY2+1yCFZyPOyaS2kUoDaBycm1ATFjGRsljsZ7LWmQXfW/YPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UVpBM0VMOEpxalpWbmVT
            amJzQU1qazNYTGRMUVZ0eHhlZzdXSmhvMTJJClMydGQ2YVFQYXdKYW9uMmNybkZH
            dmIvZjROaytqOXMvVXZYWWloV0Fra2sKLS0tIFNOSGNCQ2lBdkFETFQvRGczRENn
            N3lxMnEzczdHcEVSYkJES1dwSUh2dlkKlUHgOr4Tq70EV9eA+jpUymPyJ2XWUtta
            F8v38vE1yLsI6/OCpx5S20i3P3F4eH5nPTl5x5SOUqVrBvP4rE6asw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcHFxaEN0MCtRcUpXZzc1
            anM5MHRmUkxub21Xc1VnOHJIU1hpK3JxR1ZnCmdsMDVianFqbzZRM0t6cTVyOUpK
            RjlrMEtkKysyNVNoQVhkZ1NyZWxuK3cKLS0tIHh3MThidkpISXVGMFYyMjAyVUtS
            Y3VFR0dzZU5rZGVpWTV6dTF6MWN0MzgKm5deoC4feUCGdXVjlKPx8aKhEAsgAn9h
            1m2YXoPmhsIwkZrRAAju78EWVKq+Nmt/C1bjR6q+Xt0UdTUIq8S0Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:s51cZG+74+W6EyuF3w+SeyDFr8Ui49lusTC7grzNjJ5U7vaJ61a1zwzRuudd+nUPfo46xA7DZ8ifUFTxEy+wl8DrX3h6COJU+PtlrMsHjDts5wQ8Pa9TkJtCSguD2OBPYWdxZcBdYuxkvvtgOHTn0gdVJ40Lw8vZBJbiC3f3NbE=,iv:Pakzlcd23lZDLGAQV/O/9PysUs0i1xBk4BGp7ZF3kvI=,tag:1UreMQG5+VTRm6Tv1PrPdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
