apiVersion: ENC[AES256_GCM,data:fJc=,iv:Rak2d4XE/2pMCuyGEJca6uxLqv36vM3R8DoU4dVe8hA=,tag:GtH4sJ7a2/KPTuT1gnVuoA==,type:str]
data:
    DB_PASSWORD: ENC[AES256_GCM,data:NYFMIs3KGqa+FSmTNxocB/VgVLcuACpbLlS78WzOZqSsQ4r20I0CPHGFJxhwviImssKoclioH1lhRpv4,iv:HYHD5RFTuKLBNQaRJfj9oW98dtkcvJaG2wjFtB9s3ZY=,tag:Z5ufMj1sOHqr6yfIqAaKyw==,type:str]
kind: ENC[AES256_GCM,data:QtnZu0ef,iv:aaSwJzWzP+UFjMkfnfenzNe9fKhFCG2sWX9hL+IPMm4=,tag:NjyP2ZS2aBjPypAiSKBHfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3HLdyxDHGcVQsA==,iv:Py1TbdYVO+T4CyercMLwTWYgY+BBrlKCzEcJUIt1gsU=,tag:I0yH1TXFLqiTBBb1poxCWA==,type:str]
    namespace: ENC[AES256_GCM,data:ZpYevDpwcw==,iv:VfMwf/5bLtjaxczl5yH5pqKjbtrd0LuWSFVX3n5eRP4=,tag:v4H5yP5AtWh8by/EK9DMDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd3l1YW5NdFVPNTdtV3Jn
            QmJ3Z1dPRTh6ZGtnbFptck1SMEJYMnNZU1RvCkNLbUZ6a3NjTldINm81VjdyeTlB
            ZGx3Q0ZiVk5uU1ByZk03TDhidFNBVkkKLS0tIHVlNm5NT2lBVzh6Ly9QcG44OGxJ
            cUpOYW1HeG1BYTBueCtKU2pzOGxaMlUKITuWCiN9rr5ljfbU/HoDwlaMO0KCJ5HT
            zXMJGgnStHzXV//wgSbjI/BZbQeKNKrsjKiDxIMTSYmSyrEMixZcgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWk5tYktad3MwR0Q2T21m
            TEVZM0FGUjNkZlpPZGRVTFM2K0l0WWZZK0JjCmY5VGltUDFtQzBCNmNmekptRU9J
            U2dDWXNMMVEvZytTTE9TOWJpVXhRSkEKLS0tIFVLbWVlbVRFcTByNVpaWkhuTTNq
            ZytuWEQ5ZkJ4V1NoSzROa0RISGtRY2cK1SESw24mfKu7crB3PlWMIDurlffc+NaP
            JlzXXPG5onIApfgB7T4/QMGWQ+czLMjgyTxAJgdLk0H/iZ3sMrANHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM2pjQ1EwS1pzZjZrSENi
            YXZTOHB3SWR1OWdmTzkwMDUweFB3RGxyWVJFCjNBV01rY3VBVzE2KzV3V2JJOExK
            RGljTVJ4ZVVFU1RISVJLZnhpOVg2Zm8KLS0tIHRWTlNxRzEyTDhoQ1VlU2Q4NmlU
            TE1pY3VodHJoVkIwMTIwZCswVnNaUjgKeWuinXw25k/6WJRjIJf61shhnPXk8Qsj
            GWkRyuWybAe8T9BhwcElg/9kEHIAWUWGp+GmftJtBbzlZUoHc5RGdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSHYwaUsyZGlhcGdPMWNL
            WStLRGtuRkg5dUNualQzeW56azNHclB4Q1c4CjMzbm9VYWVhcWkrQ21nS0s2a1JI
            am9LbmFnTUg3OHRPaFhlWW1VR1c2WTgKLS0tIDVxREdVdk4rNVdLaFJ1T0VaRkU2
            c21icVEyZndoeXN0N3hXWUNFWWc3Q3MKzUVXfdaggoV4/BGcLV3yWso2xzM+VG3Q
            WOClQSpzTqcpgHIMLYpCuzwynjJfX2jutW0dKacAj94wp+/hS9ozEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcXBIU1ByQ1RPVUIzMFJt
            ZjJ5TFJaaWdJa1VpWW45QW4vSTVScXAveVdJCkphYzNMM0cvdjVtYlFrczgyOFg0
            VXV1RHhGc3VPUWxYNUxEckdaeE50bUkKLS0tIHFnVmE0RjFJRW40dHp3eFdlK1Jq
            bkNuNWV1NE5uZTNzQnlqUGJNektCM2MKTeM60Fkik0f1JTtcaeD2SkOeXgZirzAs
            HY0ufVX3peDT1dUcSd2yel4RPIdSKKfVKvAbpdk2eGMCijUIWHrhhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRkh1TU0yQlZFWWdjSDJl
            RXk5QTErUlZxWlkwcWVUbnRZYUlUOHYyYkFnClNDRWQrRjJmc0tNUEhGSVludnJh
            V21LdWROSVFpTTh2dkFMSWowWGk3VXMKLS0tIDFQU2h6NjJqamxDME5tZTZNOGlX
            Qk5DSHNiSXBva3lZTmViNkl1czR3aG8K+IzxX07ZyRaJsRlmSP84VL5zZF7+W2e1
            idr44ia75cVGpMhj5iDxVo6H8T8bihUyWugHJGVepk3G+dpLhBPayg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQWxRZlRtYTE0bTdyM2sv
            Mzk1U3RoaS9GNkpRMitTeFA1cCtRZVZLNnkwCjBoMGEwNDRPL2FRcGlSdjFlNTZi
            VmZXODI5d2hPWThYNXZFRE1lMjFBVVEKLS0tIEJIc1VKcjNtbEVWT3JVaFl4cVFB
            MHdzRVp0a2kzMXJMamlIWFFHdHJTbk0KAZ+8m/lKgpyWk6EVwgz63LWjIIFKyH4z
            wZDQgy2IYkhu6FCWyftRoKSDADwxmiQCo1umlqzf4LnkGwCMxKGQ9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZ0FEeVVMZDJod3AyNE5Z
            R2ViZjB5ZVRZL0gwNWU3blJDYkNiMFc3L21rCkRmRXV6cnh0ZFJzOVA0ZU0rMlpp
            OHZKK2VhNHlKVldqcnhnLzlyU0dBZnMKLS0tIFRqb0p6c3NlMGQxcERtc25MRysz
            RTBzbVJZbFFwMW41MzdrRUsralJac0kKkMCJZAmH2SFbz6ZknqrDRnLZWz4qjJuv
            QGMdLYKKcTWq7NuzksLGgsPLuhKbX8324dsNOlKcGd87VzLBJFTwAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYW9nNnQyU0IrMU01TXJO
            QUZXWlVsRndNbGVrQ2o4bEhuM0M3SDRRbkhNCkVOZlloSTN6MG5mYTlFWXRScWR3
            V0RDZ2EzZVVTNGlDNGdyU1lqVEI4dDgKLS0tIEhlR29GS0VIcUxtYW5PdllJakJz
            Um1QMDh3OWt4YzdoM01RakdXZTF5Um8Kz7tm4aoeegSjOsqSUPtbKofC6APUbOaB
            yq64yAMY4hz0yaSnlfamaCANjBfQzJyTSBekP1PQAPrqKnMGiEEJFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcWF0WmppWS9qS21mNGhH
            YjAvR3l2ZXdyV0N3N3NMU0w2b0kxdHRqRHlVCnZlQlIzZE9WVDlnWk5vZFU4dk9B
            bHZ6NEQzTDRseVJ1cDFoLzdwTndDQVUKLS0tIDI4UTRSZTNZbEVvMXVIeksrVGg4
            UFQ0RStGZ0RUUU5LKzJucDJvd3ZhaGsKZx9UBEd7+oyKnz4f6ORkJLLHuNNEcYQe
            O6ist2n5mxZw6xvEo+8V26o9hE0hv72msNgE7kb5IAirXZPZxbhCxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSWhoK3pyVjVCcStmdFNt
            UjhUKzBVMTFjWTNKclRYa3hQdmdjM3F2VzNVClBlSUxIUHVEdi9FVi9Cd2hpR3Jt
            QytrcW1yRXh4Y09YWVcxd1pnVExrZEkKLS0tIDlkNlJtV2REMWxxVXNzbmFoRG1k
            TXJxMi93bGszSWtVb2JGMWMzTUNCVHMKq7WAyAJcTSEh5cN7XIB229Oflx8AbZSI
            CF6ohNXr0o4/4A3sLtFI2plv8OrV8wUMdzUVqwQ8JTyDlIPGlmUwbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TzJPR255elJiMldIR1lp
            aWVPRG1DWHQ5OWFGL1lQTUZuaWJIM1ZjbkhnCklUTVoweHdWbm9Wd0x2SFVlRlpw
            b25yVUx1ZmlhNEx0ZVdQT01BVU5RZmsKLS0tIGlWR0kvVExzOVdFdnVoaUdTMVNx
            ck9rQWxqR1pYZVZmckFUYjNaRnE1ZlEKQWmk3phQpdFfwl/qZphJ1H5IxPI2XEuy
            NuN3iCVZyQT4L/TDZH4REtH19IqdKM1Kz8ozTH2dAhe7+owhCGZrVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT1hMZzVKWWlCVGl1TnBJ
            Zjl2RVZPdThqbkRjbTZoY0VuL2dybGN1cVFjCjk1eENJRXpJeVhZMVAxMVdTRTRI
            RTVqMG1KWEZ2d0dlT3F3d1Rwb1NWUlkKLS0tIFRKQ0QxQ3o3bTlZdDZYeHVzQ1Zl
            N2hXZ0dPWGZxMVZncTlPY1BvVlZ4c00KdOM55nPG1H3qr+L5GWlXSLGXEGBuaKq3
            JxYHlHw8EIbjkVL/lk/CDyV3WQ66/+9G4/dx+GCGDXeyFfT48vPaaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL1BTbGUwbEFCMXluSEdD
            TXlnTnc4T09DUU9yUGpyd1pmaEVwK3VoeDJ3CmVlZ1cwbGZJdVc5d0pNSkxlVVU2
            cGd3RWl1SXZXM1BNT09mdDcyRUpnWkkKLS0tIHBWQ3hJQUMrT3FUb2lMUURIOHhU
            RDFlQ1diSXIrQkYxS1lFZjBmTTR2OHMK3Ad729/u6awY/mI65TUj7p2X0A7gR8ut
            aXbVcKAv6H8Pnd2NsYu+xonfqzg8WxvF0FCHVu9SLuOGhhD/eeqqbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:WyCYhi5pKkPbBT3BDVIHnYC1e1L1d1El2YRU9R5bU8Po8rEKevKaJI4rCtfYv4azDqf+f5VfwvGqf0LsW0+ZcXP4U9yM9/DdnzVLyVUZ3BG5PuHOI/9LYBlV8LMb2ieZO1af2zaeV22ZuJxSDzd+WvCv2qShT+BFMv8SQxpOQ9U=,iv:GuWeUDyqp6klJWiKlc6HUsaSanHnB1vNgZA3aIiWZng=,tag:TuxMQPSHjCsw4zz9fsY/nw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
