apiVersion: ENC[AES256_GCM,data:fJc=,iv:Rak2d4XE/2pMCuyGEJca6uxLqv36vM3R8DoU4dVe8hA=,tag:GtH4sJ7a2/KPTuT1gnVuoA==,type:str]
data:
    DB_PASSWORD: ENC[AES256_GCM,data:NYFMIs3KGqa+FSmTNxocB/VgVLcuACpbLlS78WzOZqSsQ4r20I0CPHGFJxhwviImssKoclioH1lhRpv4,iv:HYHD5RFTuKLBNQaRJfj9oW98dtkcvJaG2wjFtB9s3ZY=,tag:Z5ufMj1sOHqr6yfIqAaKyw==,type:str]
kind: ENC[AES256_GCM,data:QtnZu0ef,iv:aaSwJzWzP+UFjMkfnfenzNe9fKhFCG2sWX9hL+IPMm4=,tag:NjyP2ZS2aBjPypAiSKBHfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3HLdyxDHGcVQsA==,iv:Py1TbdYVO+T4CyercMLwTWYgY+BBrlKCzEcJUIt1gsU=,tag:I0yH1TXFLqiTBBb1poxCWA==,type:str]
    namespace: ENC[AES256_GCM,data:ZpYevDpwcw==,iv:VfMwf/5bLtjaxczl5yH5pqKjbtrd0LuWSFVX3n5eRP4=,tag:v4H5yP5AtWh8by/EK9DMDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUGZBcFVaaGw0V08xcDQ3
            eTg1SHIxNVBtbHV5S3cwMUgwTTczeEIvZzBVCmU4YUlNajkrWTRuY3hKblNzR3A5
            aWYzL0g2SE9oQUgxZ0xlQjFpSERhVk0KLS0tIElaOXVRbVdETnJ4dldRTzBzNkY0
            Q29UaTVQSTRDSGRpN1BRaEZTdjdDRGMKcAlUNhl5UIa4gba4HgLJcPTfcmcHh7yn
            umYKY7acWPamTtq6EHeqonQPZxoAapNfPRLJtgBSK8bvR1psQDGGMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cXVBZmlBeUNuSWhBcW5O
            NENtM01hOW9vMGtlNC9KVS9xeGRMUm5GckM0ClhCdEJWM1NZKys1bUw5SFViZ2FN
            WEIrbHYremF5MktySHhPdHMrZ0tNMkkKLS0tIE1YbVIxRlpBZG9kVDRKeTF2NVJs
            M21KK3JteHl6MTBBaUlUWkE2a2ljT0UKEd/XkOzQ/aR9by//v47sT9JD3u/HDU2P
            bE86bjDw9Urm6a8uu9f15yXN4BzjyiHgR7i3vZQposKHoB+QWWlL9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpcg5t420nf72k0c9rrx7amg0szch98uzqu273exj7lw3yu0j99q6vcckn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrU0VUd0lnSjR6Yks4ZXZ3
            Z3oyWC9WelRuNERlMmhXSGl1ZzBzWjhZNkM0CmRuUWNxa1hKVEdhcUdTUlZKM3Z6
            UmFmMWRyOHUwTHc5QUQyZDhTT09YT00KLS0tIDRvcFB5YXpZdkRDdGwzUjZYOWhi
            d1F1eS9qOEQxNFg2V2tZdzVCV3hQS0EKEbBJwt16GnNHR2lePREbw6qsH/dP2x77
            0+cVzH5l4JgwdFYuQP5OsVCMgDlq/rYUcvTRCeX6oxoSBebWcHNytw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4mzwe89aqgs56mn8zg7dd2l623kwmw80k90wr2sa6dnlcdmhcnsp4kt54
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcXhPZFhXSlJIWWUxT1RE
            d3FYbkpTYVVkYmJCVm9LUFZSOVJlMUtLZ2tvCnVlQ0paVTI3S2w3OTRKVWJnK3hS
            WUFaa3Z2YmFDNXBpbU51blNBVkRLOUEKLS0tIER6djZjRTA5VjlYMndGWGRBcDlL
            K2JxU0dtNmJlVnJqaXRETGwrZ3NiZlUKJbnhCOEoJzEFZx1br4IO0MZyejGdj+PZ
            FDXAOi6fqLdYC9CZ4UsEcGvnsr1iIuLrCNj142qvgPRiyM/PuMaLMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQks1L1BvQ3VQUFpnejBW
            QVkvLzhnRjFxWmJha3NvVW5GNk5xUmhoNm1VCjVkU3FEZ3dCWlh0aEFBU0JGT3dh
            T1Q1NVZBNjdWTkZzTmpLMDRrYkNtWUUKLS0tIHZVeTZkOGx2Ymk2OGtIME8yZVQr
            UDFOdDVMd3piUHdGcCtVbG9pNTFJQlUKLxuNsO+5kbyndCbnWiyKjpgu/ZayFDYb
            4snCj+Qo8lAo2vo+xejAruw9QIygkA9vznbgFkOGlkSf+meSiEkZrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdUdYSjBHNjN1R1Zta3FI
            QytMRlpxVUcxQnhHRW85eGdwZDJvV29QNzM0Ck1KbU9UZGFPVkdNZXo4THdwSDR3
            dm9WQWtTVWZlL3Y3S3Y2M1dZWWZ0Z2sKLS0tIGlWLzVoZ1loblpqZE9YWnRMVm9x
            N3liUXpEaXpBajV1czRIYWJpQXd4M0kKfc8Y6kiU5943QyvPp8D3QI++6ExbbF7c
            92uijfRUjtslrv8m6aa4upW1lYGiNOBi74dc729gn2ZuzMhD3b0VQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYKzVsMU1VemtjVi9nRVVQ
            alFvM2xzK0drZTBNQ0p1QnpsYk5TbFlVNkEwClUzdWVDZjlld2s3UHAxZm9kdHJE
            RlA3UlhqVThCWFoydEhiTzEwWGZpMjAKLS0tIGx3S2tzRndTTlFzS2hBYzZkV0VU
            S0l5ZmZvNHJnc2N2djVycHRRMnJnL2cKs61QP/URStGx+p2UJTRXKxKxjtQkTtAN
            dSnu5BoV0ER6vv67Di9QJFFDWC/azSwHxMaMc5aTPzY0ySsdPp2QGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyektGVXlMd21qVjJ3TVBW
            OUpKUk9XcGpPYWs4b21FbmtCT1JLKzhMK2tRCjRQd0hBSGVMNkplTHZEZmp5M0Fm
            TnBzZnAvQkpDZ2tDdDArODl5RjZ3VkkKLS0tIGtqME5yQzV3eGFhemZlRVcrUVBn
            Y2NNWTVZUy9rZkNtbnA4Z1N2MmtBRmsKeY+RZzEqGWecvkTTztLM2lVUS6clfxk+
            KO4LzM4uOQSzPSLwYHPEjhq1o1aFQNQ0+1zb9nPHQvqQbDvSYIJxqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpcyeqjcl8j0dd4sj6f0vufs2vpus3xn4dvxe3cr8g8rgcm0nfxq03ds4y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TXF0ZENDaE94WjZFTldu
            aUpEejYwdGRicTdod2E2U1lRZGFYQWhnT1g0CjZXWFM4WXpBY25ycEZLekNzQmVH
            aFNwbmdCQUZ1eks5dW5JNmpZRmowRW8KLS0tICt3RVlGQ1UxdXRITm5SWXJ0L2JO
            VTNyRjN6S2txakFZNEhlY2pWWm9yUzQK0vlNmhqYKvPxIaLlj5z08u77rL4+T8up
            9mTulvl9UeInpcsf3aHGjoDH3i2telU5oIqdio4vU3dWFryqokOPtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VG8zOTZrQXFZZFV5QXFT
            NGNPL2hnZFplcWhRMGZlV0xUVnJnc3l1cDBrCmlLdnNEV3VCKzJPRE1oNWd6SExy
            R3lSMU5kMW1QdGl3OXZsZHBlQTYzTkUKLS0tIHhxT0J3NUU2OGwxZngyblErWll4
            dmtEOTB4UldyQW9rdjRBV1R5VlhDS1UKXwJS+N9zyCg5Syy1N2vM8yI3ZXQO6yfz
            aKauoEFdZIYJGZ8FvCAp4QykpX+1z2fuKcCFb/IAKGE2gJlxlj3S6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WmJRL1hqNUQyM2dJYlY5
            SUwrbERhNTFhZmFUcFJvUE9oYWlhS0RZN244CmZRcTQrYlp0RUpJSHJWOVkxWnM0
            ZFhTcEtHVkdGUXc5WHA2MnM5aGJwZkkKLS0tIHZMd0tMYXhtSmt6amRjU2IrbWVF
            TUxTL3h1emZGM0gzMmtzb0VoY3lsQTAKiJqtb73rkowO/3Xzfc11hKq+UA3Ss3ZK
            hcdrb2szMu+oY6IbTNURaiNefXEHWrhXVAL5FK0RiA75lnWoLpb1uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mhrzghrmprq387xqsln6996yx3ja2e2zpamh9mtuu9zqmxahunqg9qugw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TVZ4U3RFUXV3T1ZNSGJL
            Sy9oZS9SUGFoR1lteXlJTVZLTlJQMUp4ekVBCjRQbitMNkdaaWk5dDJUSTFqSEtU
            RC92bFgwWDdvc3hlS1dJRDIxanFtVzgKLS0tIGJ1YnhHYU5IeGpmSUM3OUp4OVZ3
            YnlQZWJ2elZGREVjczhHS252ZGdYSncKW7qNFFIkzH9ipadKoMZsQ5kdSHU02W4C
            GOMPxm7P0OKgVDa31gss4PBm1PSiZSazoW4zL7CAkjUjKV0/Uyvngg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NWpiVTlRY25XSzQ4aitN
            d2VQQkNxWTYzcFoxZVFoa0ZKVklWa3M0dUVVCmZ2bkk3NTJ4amVsZjFMMmo3ZExq
            Und1ZzlXYnZQdkRjN040dGp4MjFiWWMKLS0tIERqWVRwYVZEMS9aQVNJL2ptTmhZ
            YjlGRUpRVlVudjdiM3ljRjdldnZqSFkKsV/+W15mZOMStnSduGBfxrigjAaLvCc8
            JuNBWjPgn0h5A1nwXfMD7F5tD9dyh15DPMSVFmnPMuttsgsxLwVckA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVENrTmdkWlNwRU5lUVRh
            UUY4UjB5ZmVrd0NUYmE0dk5teTVWdk9malhFCm5za0dpWmkxakVCWFVhYTNTZU1h
            R25Tc3p3MGhaeU01cWxNWDFLNnNsdXMKLS0tIDE1YVRDRkZIYU5MVERSUnZIbDlD
            cmowSm5WYkZjU2QwVUFyTEl0WjhMZVEKFRXmuS0X4sxOJcPvzpA2sl8ATJp5I+8o
            JZ+JTqt7jVd9I2UGiCUPzpbkzWl2D6kWq1OD6lAVpqDsLLd8+0323g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f9hd8fu0694rc3tr6hwxz3ldfpepref937rmvqdxvvsr0kfcjdxswyzvw3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWXdMOU5qRWNRVmZwaVRK
            bW1uMlI5ek1nNGxjditURnlUcjdza2ptZm5ZClpOSTNLOU1PSWhzNk9jRm9YNEJw
            OFZPVGg0Y1ZlUHNvQzNxdVBic1dFVHMKLS0tIDhDVzIrV0VMRkUwZXJpaHlCZTdL
            VlNMUzhmbDZpUllOcHp6T2RTODREeG8KD3DKZ1/ccL5nvmhQsqsFW8sRWF/0zH1j
            9Nw8pz76VuQ3IT19VMSHWWWh5UqCVQXtjJer1cw4kRetUqkXgPnLnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd2ZLcnptKzBjbEZ0RjN2
            anVwcWdxcU80M2xwK1NzMC81RjZES0tPK0VVCkFYRDJmeU8vSFdyeVdsaktLMEpE
            RWlDZ2o1QWVyMWpQenY2blJZR1NLSmMKLS0tIGpXdkYyQTdmelFLVElZSDFUOXA3
            NDJEaEJDZzZRNUdJSEdnL3NmRldjWXMKBKTjgY8vuqkvSE3qCvbf/ylE41mNzSJj
            S2QkjkRB+5J/MCsN1JRu7S+U42SbF2z2UgTcZDtTMgiBKU2QQi2DrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VFo0TzRPY1RvWkFMU1NF
            NUVXT3dEMjVGZktNNFFCZW9iZnVpdVAxL3kwCm1JdkhyR29LQldub24rb0ZkMlJM
            VGJKUGJOaG1DRHMxZWdsSSt2N25VaXMKLS0tICtkUVhvVGlBdkYyWmJCMlVFYytL
            WjlEWE5sSFpzL2VRSFlHZ29sMkc1aGsKejkDwZEzsWL5E91JC1Mb0eyYamTGSkBB
            Mj6wI4C6Aw8KDiiVUZh5F/EBNr1Wko8bu0u+0oA9/EDWKNMTLtcwYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdDhKRWNCT2hVN3RaOXhm
            d1lFTEdJeEpZajdHTlo2dEYwMzBUdUlHUlFrClNzcGNIbm1oL01xKzVRQ3FSbDZX
            M3JRZ2hRTHRRaW45NHlLNEx5VExYa2cKLS0tIDN0c2Q5bEtNeTZNT3YvWFBxU1hR
            QUVKTCt5bFovU0tQbnJjaTFPWE9INmcKw9MJDON44QQksN/AvVuS5YVXpFzzdFv5
            Egm3jjQR848D78s+1WLwLlU2T0P1dxYPvT4DNeS0UKiDZ6ZAxr/U6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObVRuUFl3dzZrVndSSEJW
            WXN2QU1uOW1UV3VYRmg1QzM2WVNGaVdBN2hZCkdwTGlKVGtqSlRjYS95UnJkV25k
            UTRaeXBBRWl0WHVaZStYY0ZMZjdzN1kKLS0tIG9LRjlFUzNWRUszOUFuRi9JM3lp
            Wk5qUjR4dHBCRndnWEY5VnJtVnROeHMKeDM7Bp8fNwZ2hME33h950DbhOfI5qqJ8
            9O2QvqgkAUnn82C5RWFDX8pypSKpCGqUsFvxLJt1AhADRn2hb/ewGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sukfru07msq8fm5ddgym23yal9lfm99090p999p09mxgrrwh9aqs6zp4fy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SE8zQjBDWWlKT3AwTjNa
            MUNnZGZxdHFzbHZFeldwWTRoaW91YzN4NVFnClFWblhBN1E4Qkh4ZC82OFVWNjRk
            dVRWQUVtUlJZaFF2WnVYRWY3Snd0eXMKLS0tIE5WS3oyaitoUC9OUHpOT2RHQnBn
            RU1JaldoNFl5Nkg0bEVwelorbUZyVTgKLIy0bVJTpar8IIyXPoxZIeLiuqE5KApo
            zi7xUwG2Tlywi/Q7F2WyJwKRVTkIIGiQF+49avbizBP9hI5Kil1Pmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ephzrpgftmvq4cul9766q2r3mss38xu6un74ryfmw0729afysghsh0a3qg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VVZyaURsalEvbFM4c3U2
            bXNNdHV4eHV6bGMyWklMTUJKVjVHcERudkdnCkwva3ZNa1UrSGZuT1kvMjgyZWxJ
            WjhFU3ZyL2s2eUpzWGVyUUhGTGFyakUKLS0tIHVZQjBXS0ZidVdBSC9IelBUaW9p
            UFdvYllCVmYwVStWU0pYWlMrM3ZVcHcKbWu7+iYoKk2dVVHmKjmLBIb92+Ahijzm
            g3R+11Pmc3LVaohVUyFvsAUQ1tTYIvNFC05zVmvLi6QQl62JoxvG5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTWc5VkFXNXdoVWNUdTdH
            OXdSbnlRUE1WaEZCb3RWK1VOZUl5SE94VzFVCjhMR0RhNkhCSm04ZUdJSVdvZlNY
            cUozTWxJbllkNjVHcVNGSDJid0U5MWMKLS0tIFpPcnpZV0txZ1dPcUFFKzV3UzVx
            ZERrUDM2L2xzUTJwZjE0UjdBYmxoczAK4wKt33j3kwANVaa4aP1QUAFif2zLjz7Q
            RZQE0mFHl+FrnVpmG32zx6iZXNAiBoU3eTbKcvqIp+G5rXU5wqFkEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7ecrfntus8rvyprzhffjpqk2tmrc259knf9xqajlrqvewfp8d6svwp9pp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTG51cm1PRG5UcHdRNWRR
            RmthSHhLWEFYdDN4SkNJTk0zNmRiQXViSFN3CmcwVnYwYVZhNUpUUXgwazVCY1pv
            RGZCM1R0SjBNSlZJRUJ0K1g3UCtMMU0KLS0tIEYxQVZvNFMrRGNseTVPUXJpNitr
            T3VhWURrV2U2V25PcGRVbnQybHZxYzgKmUPiAa5RfMBj7d3QJSnNKY0yCVOkOtv0
            omTek540XnyczBwqhaGxEv30pWBSWNVWp96BRmlZr0Xjj0HIlq+TmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:WyCYhi5pKkPbBT3BDVIHnYC1e1L1d1El2YRU9R5bU8Po8rEKevKaJI4rCtfYv4azDqf+f5VfwvGqf0LsW0+ZcXP4U9yM9/DdnzVLyVUZ3BG5PuHOI/9LYBlV8LMb2ieZO1af2zaeV22ZuJxSDzd+WvCv2qShT+BFMv8SQxpOQ9U=,iv:GuWeUDyqp6klJWiKlc6HUsaSanHnB1vNgZA3aIiWZng=,tag:TuxMQPSHjCsw4zz9fsY/nw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
