apiVersion: ENC[AES256_GCM,data:fJc=,iv:Rak2d4XE/2pMCuyGEJca6uxLqv36vM3R8DoU4dVe8hA=,tag:GtH4sJ7a2/KPTuT1gnVuoA==,type:str]
data:
    DB_PASSWORD: ENC[AES256_GCM,data:NYFMIs3KGqa+FSmTNxocB/VgVLcuACpbLlS78WzOZqSsQ4r20I0CPHGFJxhwviImssKoclioH1lhRpv4,iv:HYHD5RFTuKLBNQaRJfj9oW98dtkcvJaG2wjFtB9s3ZY=,tag:Z5ufMj1sOHqr6yfIqAaKyw==,type:str]
kind: ENC[AES256_GCM,data:QtnZu0ef,iv:aaSwJzWzP+UFjMkfnfenzNe9fKhFCG2sWX9hL+IPMm4=,tag:NjyP2ZS2aBjPypAiSKBHfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3HLdyxDHGcVQsA==,iv:Py1TbdYVO+T4CyercMLwTWYgY+BBrlKCzEcJUIt1gsU=,tag:I0yH1TXFLqiTBBb1poxCWA==,type:str]
    namespace: ENC[AES256_GCM,data:ZpYevDpwcw==,iv:VfMwf/5bLtjaxczl5yH5pqKjbtrd0LuWSFVX3n5eRP4=,tag:v4H5yP5AtWh8by/EK9DMDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZDkwalJWSTd5RzNRdkJJ
            QlFha3JVVkpDbVpHd0RUMkVicmxmaW1FWUJRClZRcWlxWi91WEZ3TlFwcWVXS1Bl
            STdFQlgrcG9HVnlrVmFNQkRmNCtoUFkKLS0tIFJTUk1aUVlyRzJJV0xvc1ZUanJF
            OVF6N1V6UTJjc0U5WVJCdVNnQWNvamMK1EGwnVJMM4B7nET+VkQQw5tVbNRFEDGH
            b6Y971Bz+ORvDZmm8MUhfiHPTWHwwQsiWr16OtImn94ApyvLu0ljZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVlNMa2paV0dTaFZVS2hD
            T2swN1VxVnpQSURtNVZDM3dyeHVsQU1WSER3CmpYVzY1UGNPL3JQcU1GR2cyNTNU
            TnVQdlYvMmVEdEVHc05aTldSbTNkUDAKLS0tIEhQY1p6M3dQZmxJd0tNZjZsNml5
            Z1RWby8rZVFLaEc1VS9oYmE1YlRlM1UK4Pl/QmpPf+KZCVxjbe1jUfjpOeZDQVuv
            VAhzykmc34xl8lIFWhgWHbNEMnGb6ZB4CQbwxFl7JeWPdBTCRF0UnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUWMzSG1IYnFTTUhOVWJl
            bVRrNnN0dVA2bERaRzZDbTNxQ0x6TEJoZVI0CnZNSm05MFFPQkgvUTVPS2gvVUVm
            VGYweXZnUFlDQ21RR1hML0h2NFg5cU0KLS0tIEhFNktTeFlyZWF1VDNzZHdyeE9p
            dFhFK2huSkJhMk56ekNsUmxGUEVkQWsKTLgp/XWWHWcZ4ubjEpv3ZF+Nn7J7heua
            xgqA7avvFY7bJHw0H2PcsweCnVb7dxd5TJbIZNXjC8I8fZR+NyYJpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlckhMN0ZKMEM1SHFCQ1Zx
            dTF5Nm1DbFZsK3o1Z1NUSFBYZ3pkNjQ1amw0CkY3K2ZLM2pPczkrclhTOUhtUFdB
            Q0VKOEFyWjI5Z0M0ZFUxZHJzTW94WlkKLS0tIDdvM3V0UUE5SEt2SEo0VG80anMz
            SERjeitHK1NmOE5yQnFoVDkwTldHeFkKziffn8K/GAmMYHKLSI2ge6Jdstg0PBd/
            mpMItdjcHKMQVtN+2SiPKDIay8W0dwXb5IaanMARf1rE5hphXkcESg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWFdhUlQ2YUtrOUtVVXUv
            bGR6WXA2NFNDWVViSHJJRGRFSW5mMHVvZEc0ClNQK0xDZC9KVnVGWG5DYnhiR08z
            THlSbllWbGdsWnJqMm41T2t2ZGx4MkUKLS0tIGF5YUdXV3E0S1B6ZkRzay9hVzVv
            cjM3aDk0elpJaGFlenZ1WUdhdmtRT1kK461gKpS6rZ5mWJs4tGF4zIVutgFoR408
            ykqJXlBzIQZumxouHxooUqf2MaWzQPXoEBH7Gg8//Zb4YSI+4vkZZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicFBHUnNuaUg4TEZtOXhn
            dldoViswcUxkR2hCNklTZzg0MkNoelVOODNVCnFKWXRUaGY0UVh0SnlRZmVQR2Zu
            WUN3SmxVOEswMzNYeDc3bXNyQ0R2bTAKLS0tIG93MGNOSkhnVWF2RWRyNW9GVVA1
            K0oxdnRBa3plREMwTFRBVEROODZrTkkKx2AbW+OiQ0seWQom9h41d1bOMuFNEDt0
            YU6C1a0La1HhekotYFQhakLn/07xPIEWE7Exd4A/wcMzn1I4mFCvQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaXlQR2wveStnempsaXJD
            dkZCT0krV1o3VGhmaHNEdzB6WTZkY2RndXlFCjdrbmJhNUFCSU9WNEY0TTAxMXVF
            a0ErcWtKMWIra0FMSzlic1kvYlVNZ2sKLS0tIGdoTis5Vnd6a21wS1lhSjIwM0sv
            ZmM0RFhrSmJFT1BQK1RRYnRMT1NSOVEKxUkzza7F4V/YLlcNjJkAcjVfUc74NI1Y
            SiSpxIlzKABTdhWH+T1duswa2m2tOJ/c9S9SRmWm98e1KRU/3ZMAEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT1diUmJrcXF6SkNxNVNq
            ZUZYU2tRV05hQVhndEw5WGczMUJkeEh5NVZRClFaZDZ1Mkluc2NUTVNJQkxIUzNZ
            ME94ZFAxZUgzaWE0elJ3b2pzQ2ExQ1kKLS0tIEF3NGlnVE14a0ZxSUJhWGUxc25i
            SDJENWxpbU93VXBvdjJKMTduRUtwNTQK/GyR0HzopF+91XwICLAoYWcS+xb2flpv
            Esb3AzqnRgB9OJDLAn4ewVuuhTZ9MZvs/uTGU/OiANZAtkaHt10lEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd09FQk82cjBtWkR3T1pF
            UWhmc3dFRWdSV3dtVDBxSlZtenlaVGpsQUg4Ck5oSTNWeDBIdmxYQTZFMEFyT0lB
            WEtnSjVoWHJ0dHJRVXQ4NXMvOFdZQjQKLS0tIFRFWnB3Wlh0YW5rUmhQQkR5ZGp3
            d21ZYVhvYXB4bjZ3aEROYzZBSXVKTkEKJhLO4oUQs5V/C3sHlT46tr6uhVZIiFAR
            tnkGPnQGpM2D/CsTol+OZyh43MgCj/H/M5vxJMTWWzBad68qPy0EJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa3VLOEJiTFlaNGxCVmNW
            Wi85TTcyOTVZNUFxMDVkdXdZc293dWJJQkF3ClVwWjBMdjRHTUxENml4R1oxWmVn
            ajJhVWRUNm1SWTVrZXZZd1Z3U1l3cGMKLS0tIGlLNG8rU05uZTJDQWNhenNLRkNi
            eEs5NjlHL3pUNnlTVGVsSUxsQ21tRzAK3UzpeWtwau1D9aocEDblsm3UvC4u5zfu
            k0gu9/fNO7T6fz40C11VYa3IYMPMKhOA8Rkl0FETYgbcxPQGJ+rs/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTUJsajBGdnJUbzVvSkFm
            RnczeVdSdGlYMFR2ZHhrcmNoV0FiM1VpUVFVCk1MMHN1OCtxMU1HMXEyYlMva0NW
            aWkvTmUydk5zeXNYbi9Cc0E0UmRkNlkKLS0tIDdlUDFHOWxHem5oZVc3WDgxcWYz
            MUREQy96dEZyeHZlMGRZUzhxaFVlQU0KwbBKr0exnHqONU2C+oIU+ptSqrn5STRz
            Vh8mOdqVZxCijtBtQWAHitT0Es5oQ0mtAoC8IXYeGBzBzZfQhnA6aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZStXT3FLK29QdGUrSE53
            U09aODhFSVpxTHdxZDhPTDhQTGJrQTloNVFnCjA5QnI0VXQyQTNKcUVmOHpzSFRG
            WFA3a1plYUdTRDBwajVMazJsdVRHTUEKLS0tIDFsZ3pzQ2QwbGQzVFBJbUZmbmZ4
            LzRtVjNteFZWV1hBa0p5am1IanNNdEUKbS1yYGoN9iMjDnwVIs1hDHTseOaa/Zkf
            XNS8p4iwsfsei2eqVuZTpPLrZDJCJruUAJCUTEbGd6DCVZIHmfsNIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:WyCYhi5pKkPbBT3BDVIHnYC1e1L1d1El2YRU9R5bU8Po8rEKevKaJI4rCtfYv4azDqf+f5VfwvGqf0LsW0+ZcXP4U9yM9/DdnzVLyVUZ3BG5PuHOI/9LYBlV8LMb2ieZO1af2zaeV22ZuJxSDzd+WvCv2qShT+BFMv8SQxpOQ9U=,iv:GuWeUDyqp6klJWiKlc6HUsaSanHnB1vNgZA3aIiWZng=,tag:TuxMQPSHjCsw4zz9fsY/nw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
