apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - atcr-pull.sops.yaml
  - audiobookshelf-rclone.sops.yaml
  - cloudflare-api-token.sops.yaml
  - forgejo-env.sops.yaml
  - forgejo-pg-creds.sops.yaml
  - forward-auth-navidrome-env.sops.yaml
  - immich-config.sops.yaml
  - immich-env.sops.yaml
  - longhorn-b2.sops.yaml
  - morsels-blue-tls.sops.yaml
  - navidrome-env.sops.yaml
  - nextcloud-env.sops.yaml
  - nextcloud-pg-creds.sops.yaml
  - paperless-env.sops.yaml
  - paperless-pg-creds.sops.yaml
  - paperless-rclone.sops.yaml
  - pg-shared-b2.sops.yaml
  - pocket-id-env.sops.yaml
  - pocket-id-pg-creds.sops.yaml
  - tailscale-operator-values.sops.yaml
  - tranquil-pds-env.sops.yaml
  - tranquil-pg-creds.sops.yaml
  - vaultwarden-env.sops.yaml
