apiVersion: ENC[AES256_GCM,data:ngg=,iv:41HQ/aGWe4NBy0TtC8CYWxYMXhUpgcZMUxtAT/zdm8A=,tag:JOOuuXmRFjblHT0xMbhbHg==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Adr0Zs+OfvQ7ZWzXY7LQH97xbcDJA0mqAWHobYqz2Cq+K3xf,iv:7qXo7UqaFXlTxCjC5YBiIPwT0GfkSVTmnh4VQyXT8Do=,tag:6igLl20tuu5WFFro9OTqFw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:VeaIGzhNCha0XI1X3wDJ4t783+n5uRRO3UdXbbd4mhEMflDtGzOpL6q5iEj/AU32AFEa+A==,iv:JFS0OTztGRYTOWVwuf9qKohkx+pdsh0mneNBM/pf95o=,tag:xvqjQ0F+Qe49WiAy7eiXxQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LvOa38nl2V9mZdgDMP2g9VrL7QgMozgRTAe8nknFgnBHCf4yc7XCw3LsoVs=,iv:SB9PESa5djwOPTq0A6LSo4YNMImCImILuJueCoX5xv4=,tag:6Qbg9qIA//4wd6Mqmd2oXA==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:0gn3WQi0Puk=,iv:fMI5rF9+oVCglWl5ZARfyO8CTSFp1+0hu0jmDct0qIE=,tag:lIQYR4ZsMG3h0IJN7iVyKg==,type:str]
kind: ENC[AES256_GCM,data:HqqvIdOU,iv:NVVSyGMjv8LLqfMGoC/lCZUtZfVrjWrgiBLsxb23AXw=,tag:4LvFY4medr5pP1R4sexBFA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CjlOCKTmpjzDl8I=,iv:ikFXlMzpN5qFaKXmpB85i90GQkLPQMqwAzTWK56Ehv0=,tag:R2pmsvOI4TndZlWewNqSVw==,type:str]
    namespace: ENC[AES256_GCM,data:G3sanb10cQvObO1tPqEp,iv:qPyCZMVOeN3wteBXi7MLx5VHxyLfULgnpnastaowJw8=,tag:JlSXChdYMIYyRfbi35pucw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZkJSeTg0dEhjUVd1OUYx
            OGMxYlFmWm1tSTFmWTA5bTUzTzBmczhJQkhFCjdyNDhTRkRBaHVWdEVwUzhOVEIy
            dXArK1dlNnNoUGRjUjBqNEwwYllpWlUKLS0tIEZ4dzlNY2FQTG9YSysxamJDZWhu
            ZXJ2MUFuY25RODZMTkJjSzFZemhCSncKMwJ1z55TDVb0Bz+BHuM2TS+y2mGurNQK
            fnWu/0konbkXmtaznz0RSDt9rBwJQkAiyB7EkfRcBXLwaRHj4t2jmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZmNlR1oyT0pUU0RpOE0x
            c2pWM0U2aFFhU0FYMS9mYUtaY0lPZUk3SURJCjc1WEdhZzE5b1ozOEtoK1U1SDRr
            Z1BSMkVpNktSbnp4cmtwN05lT29TbzAKLS0tIG9veFVUZWlDa0NQcVlmOE96U1J3
            OVFibm1NN2I4Z1NydEJyL3lKa1J5OTgKOpHr3Rbbs1IOh7JkQN7RZnkhDqKQAfGP
            +PbwBjBaXUgrXCrp2m4tlTKkpwUo3OPDC+R+6I3TLn5GXGQqiAeGxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpcg5t420nf72k0c9rrx7amg0szch98uzqu273exj7lw3yu0j99q6vcckn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvS0xCSThxcFlNdmRtcjBR
            aWE0RG56K1VjZlZhdDRtRDAxS09TQVZCbmhNCkxFV2dCR0JhekovVHVZUytYSGtp
            Uld2ZTB6L1laNGJjb0F0Qk40RFNRSVEKLS0tIHlhcGFMejdjU1kwd2g2aWVka3Rx
            YWc3MGx5UVkyRStUMGFwWTl1OFNZREUKCpmBQtcKpnR8cTWMtYsT3tcpPex3FMZ7
            FzQPW7XxspWRAA/flAagAni/+X486E1X6HKbUBYDguGR2zeT0ND+sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4mzwe89aqgs56mn8zg7dd2l623kwmw80k90wr2sa6dnlcdmhcnsp4kt54
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ1ArYnBhd1V3N0hjT2JK
            LzhSNE9XWTRNLzhaa2c0M2E5UmtNQ1BDY2pNCktSRlEyUU0rdG1qMEpKbGVicERX
            N3lxblgzNlNPT3FCaDY5Zy9pbEpadDgKLS0tIENETkFpa0RPa0V6UHpmemNFZDFT
            WFFvRUd0dGlLMGtvenJaR1NwNUtxa1kKlUZwyuvEM55BQVUnFZn/hIocya+yIyOe
            xA98cMKYhPgxmPT3NlbgMCEDwd5RHtC2t0apk/6rPlTxsjABjUfvMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcWpZWXo5Yk5pd0FWbDR1
            Rkp5WUdPeG1NeVBGNndDZ3JhbzBRai9mL2dJCkVVVVRHWkFsNmJLUGw1V3N2Wkhl
            a3l1NCsyaWdkTjhBMjVNSHYxS05tblUKLS0tIGNXSTVJU2Q1TExESXpJMHV3ZW9O
            WDh4eXZRWkZacEd2S2wrZlBIenlEYWcKtVRFuXiFHIGlOt0v/SFi2ZvDVeXeTjCq
            MkVPawaMJimtzhg0i1wnF5FhPHXPCCV5Njj9g+fkPWtMuCc0DusniA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORkFnRE5EOFgwTmh3RVVB
            NHpOY2gxU0ZlSGxyNEdhRzUrZWRDNldMU1NRClYzVHBwNkR6MnBlZVQzakZ3VmhK
            bEdlZjgxWmtCZnNaME83eEpjSHNKVHcKLS0tIGg1UytGRlJSbnBkQjJKOC8rOHNP
            QVRKUnBRSnZYZHhyK2h0RnNsclFNRFEK+EfQAW+4TYoxIxb3U/UzPV1MBZ60HbW8
            MY2vtE4FCQMJeqeNNbYYma+lFpvxc8o7mE+r/tvn7OxTidhiYRVAZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYUdBMzlQS0pBSk9MNVNr
            eEFpRWw1aHRaN3JKYkJoTjg1dTFYWFdyQnc4CmtZTzUydloyL2lFMHZDQU4zd2hu
            a2xXZE5FRTFuTktaRDdVZnRNSUpVdEUKLS0tIEJ6aHlIMUlCTllad3VFS0kyQ0pp
            STZkTFJkQlN4R2FrSG1NU3UxVWdheU0K/VzU6Xtrs8R/i4/KTXYVNLqp1Y81VykH
            qFeZ9DvE/dLgCUkcbkKBeq0sCZ0jLQKzZsq20fFn/uGM7t5Fo3GGmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ1dmVEh1MW9GU1VDTkw5
            WkliL0FBQ3p3em9lYmczbXRYczdKR3Q0S2dNClJzczhpblZCdndRNXhSSGRrdnB0
            L2FyWE42REZRMTcxRFJqamdSNHdBYm8KLS0tIDlFbGthQ0NBcE9jREFzMzJEZG9n
            L29IZUZoWGRzZGlyZnRrTDhnYkl6a1UKbJxLWpuB0ri915V1sRaKXx6zvMQelgS6
            w8xXI9g9dQKd/TyyCG2sxs0YIMopSBF2iDJ6KKk2ig7OHjXEx6zJAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpcyeqjcl8j0dd4sj6f0vufs2vpus3xn4dvxe3cr8g8rgcm0nfxq03ds4y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabElXckhRK2ZNREpuRVg1
            TWdONHpXbmZqU2w2TVZHMjQ3bWUxRmlTTGtnCmRaSmpPMXh1a0tqQndLRDVnTDd1
            b3JZSmNmYlNkdTZnTkdSaEZ0anl6OHMKLS0tIG5QRk1yNjZ6cHNHOFhiTEo2NU9P
            Vk5rUFVMR2c5d3hWdzg4UENnZTBsalkKWAZsXEftw14ega9hAXCwriAgvFOkN9n4
            4N31i9RDP8mhCnwIY9ry2chDCD38FlO1hUsvKhI2U+NaadWqZFVFVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dFUvWURhdUtKQ3d5eEph
            a0xXVk5kNHBmRXdVU3lQSkRhUmdCeWR2QWpZCjg0UWFKL1N2R3hlTjhlSVI0ZnRv
            RGlpMzl0d1psWnRub2RlemVTTUVYWG8KLS0tIGNYQ1lZOW1HckF2RzRERWR4aTRW
            aU1RNkdMSDVEYkFxMmhTeEs1eVdseWMKht/AnSK62t8gDtsIa82dFLo8J3mdKF5o
            fGrpTtL+vRkChiSZY0J+DqGBkM5Q1HCjGXiqjd4R38XKBL25BBWgTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOWJiYTBXTGVZL1Vqbk5F
            Y3VXbHdkYjRacHJEaVdSU2RXRnZWcE1iQnhFCjNJMVNKUThjYmtEV2pHajVKWTdZ
            enZIRGJySHJKMjRpbVNFYXY0OUlEZW8KLS0tIDNQZ0dsUHg3T283VDk5YnZWclVX
            K29UaXE2SlUzTlU4WHlaUGZBTXNUN1EKobjcYRVPq+IRHmQE1tx8TEaAAX9dLW5Q
            j1nt8I1T0rI0wDTtoHrGJOMG5JRzX5CNWfW0mwPoXtlyZGHxU1FIYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mhrzghrmprq387xqsln6996yx3ja2e2zpamh9mtuu9zqmxahunqg9qugw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU3kyTkNvQzFFdmpzYml5
            b0dZMVlwVUQ1VDhEdnZtbFgwMHFkdy8vSkd3ClV5YUdkWjQ4T0xJWGpGa3V5dU1l
            QlF3UHdBSldXYVpqVk1UaDRraTYwVG8KLS0tIHhTWlJ6cG9OVGhCd3hKNENqOG5Q
            Q1lUbkVMSE9JakYwSU5YMk1wMUVrRzQKKPcBhehJWbXfFeyOZjm+niByALFv0Cnu
            CMiIPRvcydi94H+3x3BmDhH6SOipSiBesA/mnb/f/JM0in0JigdDvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMDIyeExaanN2TmxWdTFX
            YWJQY3Y2KzFJY0xBZ1pIcGtYVTIwU3dpM1JFCitWa0tKQzJXdTcrUmk3RldaQ3I4
            eTJHRUFhdktETlFValRSVElBMzB0MjgKLS0tIFZhYUtjVkxLam9TSUxmUFNLK3dv
            eHU0eWdza1cyZWZ1VDlaaEU2Y0o3SWcKVXePJbZlgNlFH1OFc3zAqdWBW8kCH5ib
            svbdwhIrr4rz/40G1Wz/gu3/VuIdknn3wmKJzJ5dySzr/SeMkpVmgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RXNQRlZxV0psSUtqd0dj
            STZnQzgvSVBuRXNWQkJkcTVyeHdIMjJCUEYwClZxU3g3SElJZnF2RThGYU5aSlJZ
            VTE5anBnVEdTVVE0Rm1NOVlRQVYwZ0EKLS0tIGdhWmprdkU3R1JzUk5GSktNMWwz
            Tm9rNVVlRG1TZjAwaVlJdXBCeXZTUU0KEBZJrdMfGPFphyC+q8mCva/p4eZClkZ+
            ev7hh0S2yFBzp41JQaYc3AUxJ33LnYCcxaBkqhjhOW4XdGWmJ9hf2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f9hd8fu0694rc3tr6hwxz3ldfpepref937rmvqdxvvsr0kfcjdxswyzvw3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNFRRRGt0aFNhZVlvWlhK
            bmpacXcvci9JVTRvSS93Ujc3c1dNLzhNTGhVCmQ0dXpoRVBTQTMyNTlNc0tZdjVa
            dFlLM0VtQURBMHZ4eHBTMG84TGUxTEkKLS0tIHcvVVlnVHdvc3BTeGlTSC95eml0
            d3BiK1RxeEVwdkN3TWNId3g5STBBczgKr7sJM56Ud/t3aYRztc/0xPbvz7GMlAEd
            +LUfHtZf3dAitheoKNT5bSujx0pQHUaD/YmL4ZHMsnxrQeEgcSlezQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZXdTZmpwNzBpUERyNTFK
            TURpdDZ5ZG92Q2JWbkQrSlFmd0F3RG95MmxjCmNLNlIwMGtqU09ZbWtCRXdZU1Ba
            dlNQa2ZOVW1uMlp4bGVoMHVPeEYvRUkKLS0tIDhZVVFKVUNPcXJ4Q0pLek13Zzlm
            bHByS0tCYllIb0NrWkF2dXo5bHE2UmMKTtQ8LgPWIr2gs04RXeX2ITDgjIRSxPuw
            2ERYEmxMHdq+MV2BiaL50SOhNoUEYBcNl9zC1N3ShxKRWhdEq8SMBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZUdYWWgvQUsveTdaS0lo
            UnZwOFZyTUx3Mi9zYjNOaUZmR1BscDhFTlZzCnF0T1FSYTdlYjRoTEEwVDBhRVlT
            RHQxeUxDampNSnVjQTJIeHU1ZnpXMVUKLS0tIFNGTm9vemxmaFNsbjNuS29ORDkr
            ZE1NazRBemIxNW5qcHpBTFkzNEwvMGcKKNnv7XlwBXfDRXEeVZFNJxrNX7A/TORl
            EnaqVbsv1Vtiklx45krJwKUhe4F2HZTNB3f6+/gyHUDW13Wa5Va+1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QVU4VTlqZGVlRi84VDNV
            N1VZc2d6M3dCYit1UTh4blBHS0k1K3U4Y1djClA2VVVKcWVYRUp2RWNhQXk4OC81
            QWpQcXdIbXZhaUhCamp4cmhVL2RFWGMKLS0tIDl6aWlOSHFjVVM5SzVHV3Excnc4
            aFlkUHk4ODZpdW5rQ3ZjbHJRMWRNT0kKLCChEohQi1AbRuUc0ySEu/xyBhLDGduY
            33scin78pw/ruJV38Q66h3+869zY14AVBbqaSnITP4TStRUc+83Yww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNlMwZzNXV3cwb2Zxekc1
            d0Fsc1NzRi9XZ2Y1c0R0VVAzU2dwUU5oUDF3CnVkTGdtUmVNRG1TMnpWbGVuYjc1
            SEdheVNzMlJ0cngrMkIrQVFmbUdJLzgKLS0tIEwxVDRtRXowUkpiRkxpMEpaN05Q
            MC9IZURSVjBtYVk5Q0dMK1dGREhOcUUKeDvVVWSYSnkmGdyLOwkNmif5z3U58/oY
            VbuUYc6fmv/w61ET5ltdqHpzKwc11y0yvpMhpVCGLLxgNZdXuYFvqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sukfru07msq8fm5ddgym23yal9lfm99090p999p09mxgrrwh9aqs6zp4fy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTk1tNWdUdWdveGRUU2hX
            Vmd4UzR4ZkVqWFdjVFUrTWhqTDZLWDRobmxzCnBicFIvM3VEYm4rUC9LRmZGemYy
            cFBTM0R3UmorMzFzU1BGeWtLa3BqZmsKLS0tIFdTcWxRU1FzY1FENUdXdDB5NSs2
            djRaSk5Zd1JzT3M0dXZ5V0VkRm1SMTQK3MUaMZl56X9Cd0HjZ9VA1Km9FRgF+hKZ
            40GUY7a0LARln2mzfK4XFowHK9LHjlqSZbNbfkJdu7OAQw8RB49yEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ephzrpgftmvq4cul9766q2r3mss38xu6un74ryfmw0729afysghsh0a3qg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTTRlcTBSSTVucXcyY0to
            VzZZSmVvQ1FJcUdkYU03N290NCtFUkZNWlMwCjQ2WDA5MWtzYUNYMlQ4bmtFOUR4
            SXBZMUxkVk5peCtBTVdvazNuM3Z4T2MKLS0tIERtMktRUEhOdGRZYWpmZUREZUcr
            VWxYR3gxdFdCOU9ISmFSUDFSSkY4RFkKVQx7Kw1pqu3GnxwV9723aIFqQI7yAnH5
            mT7PLcwpfvL/yvmUCH0kDyqxtWZY7fTXX2F1H+ZBiPW8wyfdY0s8GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTXhHZ0MzcitjNWg4OU4x
            dXdWVmRFMGMwdTl0L1kwMGNOK2pKcWlneVhrCmgxU3RybVlja2R3M1RTbUZ5TFBB
            Y01QS2MzQjZBKy96UTh4K05tUm8vb00KLS0tIHc0VHFFOCsxbFBid3FLZzdpQ3hY
            M1BseDNCY3VYK05NRE5NaUh2UGxaZ2sKYmOgTFQEWDLsas2K5urwjK9+e96ps19V
            sYgp1qcJksOlqCxnaUdxIaqlpDp6ymBFDiBIUDJXVfBtTUCv9IkJVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7ecrfntus8rvyprzhffjpqk2tmrc259knf9xqajlrqvewfp8d6svwp9pp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYXVEQVJGUm8wZ25VQlF0
            ZWloRDdwRXBXMTB0ZGFiekxrUy9CckdmQkRFCkdnQmNIUnk0Yk1kNkNXOEoxcGxm
            VkJXT0hmZFB3U1JuR1BCTEk0MjJPdTAKLS0tIDdrYkpNNlROalBUOGxSUk1HUmxT
            bWFIMHFqYmxVRllmZEVzL2pyeGlWS2MKyi2JpJSOgBDgXQy+Qc5mKJ8FHyb4A312
            GNbHNlQkxr1LC+nQZiDd9XEmQeRCV/S35R/2UIO6Y1dDG3nBGMdEkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:24:47Z"
    mac: ENC[AES256_GCM,data:LqvQIhp8t7tR9TJsGeN8USEkpWELPOcgTJyn4hltB8nbUQmal9SCaVCOFOJeaHJHEDYZ7Jwb00dTmAvTzRyaERWroSQXc4r7zncp6OqVwsdtWvgOs/ue8KgLW+rFTwLIDW9dUKGuxaLrqooplJcj+B0uXVIXEWLv0t1b7c6XQfs=,iv:E3alANpPKiTga+j+mAIHh0Qa9v/sYFKK1yXXkeX0a1U=,tag:zFzWIHMfiWrbgUdyj6AyZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
