apiVersion: ENC[AES256_GCM,data:ZW4=,iv:hrx1SdH7M2ymdG8iRp7k8MyuHd20BbKCjzj3a8QNlSo=,tag:tE1bkWtNSliQm2Nhx2pd2A==,type:str]
data:
    navidrome.env: ENC[AES256_GCM,data:b9oxjwCPQ1p2DTZuUBFfegj7Nuyo4w+WdmN6oJrdtPect3RmLgI+25ACNQ8v1dGPcl028ZHWaDR9kEMDoQvP7xyp+0S4yhgCWb0Ellm5TB4z8YRu972tzvpLLr+u3gHSd/oRVWcZCAVkezgkDc3QYjEQ67R9qOhX+RCTthbV4jMzzPqZ8JnQgjC07d44n6zECcBRbeyL/h+RFutY+0FTgg3tMExlxhuQK9vUNgiwn01gl8D5VkCk0KidKTTpE1WU8mRo0vUan0So8FEpAUeuMOh8fbXAG2hFf2+YGaQk7NiZTsDwFvnYWd3Yyp///si8pREvPSjIAIn7CmXq+oDqhfC3bjY5na5gL4AIZgCg6TUP30xgteDBdcx5KC6MRAsULziOUxuX0lcI9h1BDwzUlg==,iv:FVqVQ/1LZ9YMk36ajg2aST7qkrPT8ghuYG10XtvHNrY=,tag:njVugcPT3/KHN+jA9y4Nfw==,type:str]
kind: ENC[AES256_GCM,data:zLjrGF4J,iv:BkD1BosHSCsWTSBmXDJccugCO3aRHiEd3PETX2KZf7A=,tag:2o57CsOZBKG7zRxi1oupkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3Q4DGsOWB965bU8syQ==,iv:ItHJUogV5NyeZEBg6yZt7pY6zeOCC2J+iNPd2XI+dXA=,tag:ih9c6sixAIlZ9/Rey7f9Jg==,type:str]
    namespace: ENC[AES256_GCM,data:kU5VXw/4ZQ==,iv:tr0vsYZ9ZmPS48eLKSjt4/HC/uYF5B0qfMCRrOymDSQ=,tag:O3fJY4fHQjVg7ghWHYSoiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZGRsc0k1TjZnOVRrZWxW
            QzVvbmhyZS9UbHM5QVFYTUxDRHJWSEN0RVY0CjgvcmdCcUJZb1dkNS93RjR1NUNG
            VitPdFFYSVAzWS84RStSVlZVWkFvZ1kKLS0tIExVaFo5L2RydU5iRndyeHZXRVdR
            bWlDMDhaWXpHVUlZWWtnUTA0UUcwdGMKgh/vbHraxVtI1Is0nc4JqmS9ErElrGq1
            sal2BSgcu6fNipdISOOfNn0+sgSl3bPiD3+iSQgnJUjNQpNAcz/hEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYVU0anQxdk1aaHJ5NHpH
            eHlTaXVNaFR5SWRYYmxjaDErM3Vmd3FlUzJJCjZvMjBoRk5abkRhTGNqbk9nSmYr
            VWp3SVJKYXdjcWhVTmdvTWQ4cXZGVnMKLS0tIEZ5TG9NRUZ1OEd4U2JqRk5IVWpS
            emdHUUJoblh6bWZFeGJsT1BwY0ZVb2MKfiY9o1Q4C9KOzK6TQ9ZBdY8TF7/KjvKs
            gbRlTbZa4NXMqMMPBRWblEuPSSuTJ8vF1JwPjjbgnFbUXmgywCKCLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpcg5t420nf72k0c9rrx7amg0szch98uzqu273exj7lw3yu0j99q6vcckn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdmUvZGVMMEpLTjAvUGJO
            aTJ0SjJqUzJIWmN4cXYvRWNiZXFuQmhvb1d3CmloZjk4dTdUK1NEMitpbXlvVCsx
            Y3cvV0d2WXdrbTBFUi9aZzdna2N1c1UKLS0tIEQ1K09VQXBha3kycDV5eWR2NEtp
            Q0hwVlRwaGNYY1g0MzQ4UW42WTVWbFUKctO903t/dxE+zJBSm+zoDkmB7dh++q0M
            SV/RtsSQOttt79kJ0UsNolkqM32Oauize0SooQazqubKyh3gi21q1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4mzwe89aqgs56mn8zg7dd2l623kwmw80k90wr2sa6dnlcdmhcnsp4kt54
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3LzB6dTFEeTgwbG1meFlp
            UkJqVHpacTZhYTZYYlJlOFkvdzN1UWhTLzNNCktwWkk4QklPb3hER1kvWGlWL2U0
            R215TWc5cFArOTJwczNubDlHYUxlM0EKLS0tIHFIVFVNUmVKeDJkK05PTld4ZytG
            dkthWmRzMlpGeGgrTWoydHphZmdCdGcKJxlH765fp1UHGlPSbuSCV9zfku9WXvrk
            ToJns2qflfch0mxNKfPMY7TEJHjXQCrS5lBDxqsNeP1Vy85CuGxlGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRjdjUm9SZTUyVk1RK01B
            TTVkUkRSWXFJZXhYanc2S1dxclBMcFYrRUZJCkpZR1cvYmM4N2hMcVEvOTZ4RHZN
            Vy9USllyaThDK3ZoZzAzRGFxK0lFWEEKLS0tIDFaMTFsYUx3Qkh6ZGRmNXhpR2RK
            WW1SaFhteTdSV0Q4NGFMS2ZNblRYemMKqFspoPIhZ5+m2HIg6zGG9JLdDtljiu4x
            unQA8Rv2hYezSmmWskuFLIpX5qybxtv9AK1pGgAkx7RtLr9n8qlbDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ1NWd0xIOGRLUkNzeTQ1
            ZjJGRjNLc2lZdk43SVdXb1dIZkFCQ1hURDFBCm9qS0pKN3RuRlF1ZEcwZnJpdHd6
            dFovOGhZZDlpOWxLcUhBei8rT1p4dE0KLS0tIDNqM1ZyQjl0Sy9wVE92VzRMOGk3
            ZmxDWTlMR2htSFVTRUdiYUdPMjVSWUEKu6eYvtVqj2A1U6b465hcou8ZWtSPWarM
            weWlmRrnq0Huar3dXPJw7IUFYyJ3DNTiOjVWttDRuL0FeFTnj+LPHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNenpTcVRGa0FwbllFaWZt
            b1lwdlBkcWsxaU5xQWdOQ2NpcGY2QWlIWlVjCjdGcEVUd2tBVGNKdWloZTM3eWFE
            SVp6TGNlOTFoTWFRTEt1L1VDa2cvd1UKLS0tIEJpSHRKcE9Zd3RwQ1ZUaE5ZYyth
            dFZQaWsyMVVaZ00xRTdqWGk2TGdrWUUKr11axwu+YtEupTdW9c8Pj4MVjt9OA/t0
            Wo4jDkJqs487BeC9r/Svq56e5RSKhB/Dd2R+U57aywpZrxW7Wgdz+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1ZtUXVCcURDaEhyd09J
            TDA3QUtTZEk4VVIzMks3QmpCY1YwNG5OWVM4Ci9sTlFFamVZRlkxeitMRC9nVUw5
            bkpVS1NudEQvMk5PTWNvMkRIbkptRnMKLS0tIEg3UkxiUy8rVld4L0ZnYWUydFZI
            N3VwaUVQYTBVMnlKb3d6ZDQvV1lFamsKQ4QUCLzEFEwZ4659VRwLnEg3zWFab4dt
            6nRaWBmk03FqqM63s6TIktd+7GF+GdaPL4ezcgFEzyRNmdHJYau+OQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpcyeqjcl8j0dd4sj6f0vufs2vpus3xn4dvxe3cr8g8rgcm0nfxq03ds4y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMU55VlhJc0N2aXFUc1FJ
            Njd6ZmRiVEJjaXQybkNDVFlWMkdaN2xQTGdFCmtzSW1HT0p4WitXaTErWWFWRVdS
            eXpWSjBKWUx6VlQ2NFhHOWVaVVBLRkUKLS0tIHZkNCtuZWpPWTNDQ25OV2RITGx2
            SndubnpFZk1XaC9iWTlyaW9mWkhXd2sKWfJHSuXCZIIqyTKDhNpHghar6DfRYIAw
            3mLk0Rx/E0CWqORdItylAx2IaVt3uuVrQ/57xgQ1opVRHoQTIkEuEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZFlqUXZDQldKc3NNMVVE
            ckdjWXZ6cmJFVmpOY1dudjYyd2hJQmFUd1RjCjBTY2dBWHJ4ZUUxaHdoSERqUUYy
            Vk90UW5KS0NiSndJSk5DbUU5U1NNelUKLS0tIFFoRnF1NUVlWjEySE1QQTU5N2p0
            VmdQL1R5Q1JpUGlkUmhjT0V1YktXNHcKje9rlpwyGhGtOGSHyf4tdTHV4trffTS1
            XZHAsYivqNK1qxBinHEeG5euYOGuO+6daokM5+038NcYm6GwTzcJxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMkwxcURxNWNBK0xtcWdY
            R2JGalpkTmUwTFBlOXFuYWxKNFk1VFplRnk4CjNBcGpMRUlKUkJVUE44Q29UTXZu
            MzZSa0c3R2xXLzhMcnpsOVdpcHo5ZVEKLS0tIDgxVk5ubXVMZThsYUpOWEZ4bk82
            N1ZVZmc2cnZrS0YzNDZRSm9hVXNZR1EKc8jNRpY73XXrtO0U0oSopP0G993VY5va
            vRUNdu8DBnpRJQCsj7xrgx7BlPlm8dLibloF5ucfdpc3qwbI6uxf8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mhrzghrmprq387xqsln6996yx3ja2e2zpamh9mtuu9zqmxahunqg9qugw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK05HTlhrTUs5cFFUc2NF
            ZjI4L2hPbGVMSlFIWWxmM1pCSFlMdkhiRlNvCnRsQnpsS0RFQk9FNGFrY2ZQdjdX
            bEpRblJiV2RxM3QwVjVmaTUvUVRSaXMKLS0tIGdZWHpHbHhhYWpYT3J3MExNV2Nk
            SDAwY1pqWmFGM1FYR3FwV0U0R2M4b1kKKHSFunObAkcUUzWpjpl5HQOSvhAJq82P
            CY+4TRCmevfphVMeC3NJ88Zmx47OWEysMu2U7k8BDe090mu1g/xDFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU0UvWld5ZTVBdDVhM3VE
            ZkppS1h3OWNhNmpZQmVOWFBoV25hSUkxK1ZvCm1lenJkU0VZdnZ5aDRNRUwwcmJa
            NGtDWitUK0JCZFZyY09GcTJTZGx6VjAKLS0tIFpBcVljWVVEblNqU09jSG1pc0Fi
            MStheURqV0o1VU9IZmV0OThiOXpmVlUKBNuP/KqIaqRWWyFLm6SlnSQmlejK8OKj
            VzRQWwtdWLUsJARzGHZkxQMzdGg3ISFuBgXvPyH138MoCkKvgKazLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbG9PTkJLdElIa0c3Rjk4
            SmZJZTFva3FqQm5RWktKU3NUTURDQk9JTW5VCkJqSFhhbm1uMGd1MlkzVVFVMTIy
            VnA1SzFHQTVqdGZGdGY0emEyS2pSakUKLS0tIDB5WHlFWmVHM1Y0dG9IOCtnQlll
            SDdMZEpXdEJ0S1BKdSs3ZEtoLzMveXcKWfdiWwpE3l5VKBGkZeSOrlMn8IWFNlqu
            r0ZhYUcWppxMFJhxSwIIny8pzI/QBeYnEldlDE1OQfwffK6ab9DVBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f9hd8fu0694rc3tr6hwxz3ldfpepref937rmvqdxvvsr0kfcjdxswyzvw3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV2dqZ1RVQ1ZWK010bzFE
            ajRtMWpCUjJGcnpIQUxKdXlaZ0hnRW84TmlnCmtNMFU5eCs0Ri93amhOV0hpY1VQ
            dXVmUko1YThSSEFVZGdIRktETVVQYVkKLS0tIFZSN0lTSmYyNWhOVGhkRlVBdURC
            YjZyMnpURzljTjZxak10dUdrNHR0NG8K+b0vfQhSfd0W4+e2OE0nxw6rvewezSON
            mBCi6IYePmKpiQJunSbqf0FeBenCc2E+RHanbesBJePC0XP7fLnZFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VXJGdGEzVUZ1QXBUTUc4
            cERUbDNEdGwvdExXMURuNmllSGJUc1BhdUFRCjNWeTU3R0Nza0ZvRkRaWVU3c2xW
            S3Y2WmpDQkpqbGljVnRaSzhKOW0wYjgKLS0tIHhNV3dQaHkzVGc4Vy9uSzE3QmJX
            TitwRk9WV081ZTByVVBBUlZDbmE4a2MKirGim1j2CHjYRWnm0GcFBtoj5qDKJR2X
            djFldhOt8HeOklry8Yv3vHy0DBYGfBivhXJHSzUfheKFmkJvm+hVNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bkFhK2hyV3BTRFRBQ2NB
            cUxNcldONEJoNnpINFhBVEhCT21ua0lCb1FNClhEMkFUY3pnWWNTa2NRZDhaM2Zt
            YU85MFp0YWsxNWE2UWpBV3V1S2NXZ00KLS0tIHd3Nzc1aTlYL3kvekdTdUR6MlZn
            dXhWT1JxRzJJMkF0RkdmZ1Q4Z1JmTEUKOk8GJiFfyLmSrE+vztgeN4IGWenEkb3l
            n5vZBxgqx8j5xAcXYh1lAHz/cMYDdsp1epArB5dLUOL7mFOcbchIGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWlBXaEpkMG95bEI4bFZm
            Qm03UnVQQ2J5NkhOYzVjR2RzVGFhSW1oOTBnCk5XRVUwL1JJUjhuZXVJYytjWnlo
            YkhlTkhYeTl5ZWZ4UUhVVGN1RU9EdWMKLS0tIG5VUHE4MElyQUVteHBFL2xUTzFu
            b2kyOS9HMk9FTnR4Q0dkeFBzL1NZKzQKFcRBZuB2sr4zdavcd72R1oVvbaC70l8A
            3wkI818VLmC28ODuJ93yq+b8tO7nn3g5JbV4jESQHhSgUEK1lJiPYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcHhHd3lhZ1IxOXRMK2xu
            MWlxa3NQMkFLdXhjUXdSQnBvNjhJU2FkZUVnCkJxTkRSbGpxeDRYY2xCSkpRdm0r
            UTkvWERnTXhyWmxiYmNkV2ZGNmFSZTAKLS0tIGdIbHZmN3pFZnJkNXFWa3pKaDJE
            STVLRGVYOTRxd09TWDFuSVJ2b0IyNk0KG28SaQAIlajrwxexxFWfeoXlhmVER+1a
            MLMb3n1F+xQkgU7UNEC7R2u9DfVA9l8cn8ONk/zl8mG9RzJ9FdMH+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sukfru07msq8fm5ddgym23yal9lfm99090p999p09mxgrrwh9aqs6zp4fy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Qm5sb3lWT1FZeTBpbjM4
            aGMrSHZXSHVmQnlaVFZxMkdYNEVNQ0ppRFM4CnZiZkhqd21Hd01lcTFvYkNRRHgz
            cVFoMzFJNGxtbGVZbmw5R1MrdlRwek0KLS0tIHBqeW4wQmtPTVMvNGx0NDFVTEFo
            NWEvOE1sbnJlQVdOazB4MGU0NXRHdzgKAGqxGSUHQ4xFZqiw+OX/5BEtwq/tOx7C
            qDPf9BPSHn6+8eVNXBjTY731GRCgvfvK1SyWUU3RNdG3AB+CaaL79A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ephzrpgftmvq4cul9766q2r3mss38xu6un74ryfmw0729afysghsh0a3qg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycnVDSWpxZVE4TWthL1Ns
            YzArZnB6emN5dTBzR1BrQ2F4TXB1OTh5TWw0CmN0MVhLMmFrZnZONmErVHhXVjdm
            QTBZTlR4MWlHakJ5WHpsd0pYcDAwUlkKLS0tIG4xRmNqUGlDVU1GaWVTQk5nRHFE
            c3FGVWM3MDFOVDh0YTdVcUZRRE55cjgKTAhnuuqhyqARwODXdpnplOVB7ndpyLHP
            7rG/gbGy0AggFisi4y/q2KuWm9GpkcAX0uLakwtnKUym622uW14WCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN0JLRHAyUEdsS21DNzF6
            ZnA5VmRSaWVQMTIvSzU0cHRyVlBIY1RoK1E4CkRFbDF2dlhkSm0rOW82d3k0M2dz
            eHBQem1RbFppRGlxbkpUamg3ZndYQTAKLS0tIGQxbDJoS3lKdnN3d1cvdG5uZ0lN
            dEFwQUVhVzdNeDM0RTJUa0Zad1BndjgK9A7bFuWAx6oJUx7Cfg+QcqPFj0f8Qq+a
            SKcNRKVfvQKYE6D/DMioIHKPrliztWex/WJM4BxcB1I3P0T4ahZdiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7ecrfntus8rvyprzhffjpqk2tmrc259knf9xqajlrqvewfp8d6svwp9pp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd0Nqdk5FQ1A0bHVUeFlr
            bWRSbGxZRHZoSzN2QTc4bkh6bjlwZGFWQ1dZCmhOR2dKa1NYSk5pUGJlNmFveVJU
            SGg4YWZ2RjdjV3lvRW5TdnZCN3hJMHMKLS0tIDNQbnRHYS92Vi90WG9IOUNlRlVZ
            V0h2TTNWdURSYm5SNU50S0I4QjJrNk0Ky4feob7Zpdxm7rz6sJnGyoJybY0g971j
            Q2pf4wnA1XZfWdfuHmFsOz/7q2XLBtf+GqMua1t7aXfPEbTD0zIRNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:sv1Erw6bjpHJc8jbUYMjaOzTfwJ2aNJMfagxra7ag2lxfi3ngYoJGwbHapKQknkqn6sjMSA5SNqpdM6if0XHDapGjSFMPFloFoGifabo1h87NpESqbqPX2mgjuQJ4LNDY/D1RTMDaOkh+p++lVNsrtEI5RJAGWSWjLoa+BUq6mg=,iv:sLlS6vauB6IunBlojwSItvSDARjkYePzKpPHA8SO7os=,tag:yHtt1YyyKQwecU+YP00Fyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
