apiVersion: ENC[AES256_GCM,data:ZW4=,iv:hrx1SdH7M2ymdG8iRp7k8MyuHd20BbKCjzj3a8QNlSo=,tag:tE1bkWtNSliQm2Nhx2pd2A==,type:str]
data:
    navidrome.env: ENC[AES256_GCM,data:b9oxjwCPQ1p2DTZuUBFfegj7Nuyo4w+WdmN6oJrdtPect3RmLgI+25ACNQ8v1dGPcl028ZHWaDR9kEMDoQvP7xyp+0S4yhgCWb0Ellm5TB4z8YRu972tzvpLLr+u3gHSd/oRVWcZCAVkezgkDc3QYjEQ67R9qOhX+RCTthbV4jMzzPqZ8JnQgjC07d44n6zECcBRbeyL/h+RFutY+0FTgg3tMExlxhuQK9vUNgiwn01gl8D5VkCk0KidKTTpE1WU8mRo0vUan0So8FEpAUeuMOh8fbXAG2hFf2+YGaQk7NiZTsDwFvnYWd3Yyp///si8pREvPSjIAIn7CmXq+oDqhfC3bjY5na5gL4AIZgCg6TUP30xgteDBdcx5KC6MRAsULziOUxuX0lcI9h1BDwzUlg==,iv:FVqVQ/1LZ9YMk36ajg2aST7qkrPT8ghuYG10XtvHNrY=,tag:njVugcPT3/KHN+jA9y4Nfw==,type:str]
kind: ENC[AES256_GCM,data:zLjrGF4J,iv:BkD1BosHSCsWTSBmXDJccugCO3aRHiEd3PETX2KZf7A=,tag:2o57CsOZBKG7zRxi1oupkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3Q4DGsOWB965bU8syQ==,iv:ItHJUogV5NyeZEBg6yZt7pY6zeOCC2J+iNPd2XI+dXA=,tag:ih9c6sixAIlZ9/Rey7f9Jg==,type:str]
    namespace: ENC[AES256_GCM,data:kU5VXw/4ZQ==,iv:tr0vsYZ9ZmPS48eLKSjt4/HC/uYF5B0qfMCRrOymDSQ=,tag:O3fJY4fHQjVg7ghWHYSoiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSE9BNTZLMTloelEzSTVl
            bDlCUkRyaXpHUjRpT0ZNSDNOcW4rOHh6aFgwCnlSVHZLNXVwNzd5TkltK3hhMVNk
            emF4cW1lbFl0TUVpd2YvOWV0YWNWN0EKLS0tIENtSVAxZytLWlpBTkhBbW5mZlg1
            aE11UFNKZTk3bElNT28yUVFJc2hwWkUKCMLMzGyA/GwphPzu+W71MMGNU8WgAVpK
            UUOp9KnmgKhtyUSpEPpN+Wos9cUKnixxONs0jt/i92ZcH0V3kwAD9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbzRkd1R1cU12VVRpZ2R0
            Njk2MW9mb2czZGFwam54cjhmU2hUVmhPdjNRCmhWb2M3ellGb2xiWS9SMlJUeDFt
            SzVhcndXa2NGeEkyMytFU3h6SDBTRTAKLS0tIDZPRXJoZ0hSZU1zVjVhOFN3KzJo
            NE12Slk3WWhXclZZYThYVjZXSDltaHcKiDwF/DJtsz3sa/GOcYsoaTrsFdYEQcEZ
            FJy1t80/YHeVSHF625DecYd/UlPwkTPDS/2LKyRHNFFwUYpupzu9GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOGhOSHVMQ0dzR29oUVoz
            VDlyOHk5cUtyN0RPS09wb3N6YldqLzFMc2wwCkxHRkl1bVpRTmxpNCs4WEM3YURj
            OVJvdEMvbDFtY1QyRGRxdHpVbUUva1kKLS0tIDYxY25oUzY0RUJnU1ZsT21wQzEw
            blNrN1NndWczSWRvRFNZZEs5SlRaNmsK44CEL3n4gnytOZZoCx3WISCrlVUt1rHi
            bCTiLg8m+fBcKkIoixKHdOnyruAnesOqcNrraCuzAK3bloExcmdAcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK3ZlK0Z0QUVMQXlpbmpW
            bS8vQlBZWGVFRlEwK0x6YWRzZkJKenpNZkhVClNIVFVTUUZvREkrSGduUzdkOVN0
            eHAzNCt0N1V5QTFySWJTRStNYVdtSjQKLS0tIEJDdDlSU3o2UGcvMVFaR3hPM0Zo
            bGdSam9HNmtqMW9nVUFtZGhHUzlZVWcK7mDX1EugtZYBrc9ne3do7By3VG4WCPs5
            /Jmf4uIuSrNgYyPqmz41nOu7XmIKe8jRZB56PrH55W5cM/RikiD7pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSmhIUmtwbzZvampnSTZC
            WnZmTEUvNzlZRjZMUW1jZ24wVEV2L3lQSUNRCjBWQnJGWm9CakxQRncrTXliVkdk
            ckJ3VC9RZGNqRG5UU25xQjFWSUtQNzQKLS0tIGlNWlA3Nnc4SHp4Vm0xRCt1dlFl
            b2FodnE5czBpdE8vREFzMkM0aDVCbHcKPZ5WVJ6KXu6f6Zj9SbBucXIngaCq9ERZ
            nC1pn8D6XTCcG8kWpWJAokMLgwnwqSCO7CAaeTAPpYvaOKxyyVyltA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd085ak1MbG0ySEdrbjc3
            bFE4UmJwKzZ0eTlzbHN2ZVExL1ZWcitSSkYwCitvS1BUK2dMWkovTzJkOFJwODlI
            bGZBZ3N1R2dUL2FoMFZraTBMUWNGTDQKLS0tIEpKcjFiNlBsYkVNZG1yZFg2eGh5
            V0V4ellSUkM3VHZxUC9JSDhmMU5PWGcKQcD6kLfQyXSKOPwzawZTQ+BSELHsB5vC
            aXfO/kvOJHXNUoT+S6llmHpJySdrnhr0J0kulVt1rUukPQTE2eCZ+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZkgvaU5naEx3M2d5bnUr
            cDZJaE1nSXExTGZvWERiWXlBK0w0RGUxdjBvCjRob3pJSDBlbmVZalpJRVhhL1JP
            dFpFWW9haVB6VjdMMm1tWmtRcmxMSGMKLS0tIFhjcWFjeEJlV3N6Q2xqMFp0NEl3
            V28yUDJrYlpqb0xHcFR2MEZZSThYWVUKA0Pi2AHx6Z7mY2KK3icoLdmLNWl43fbQ
            Z0FEH+6GVkqVnNX1ZiAkr5MxldTpXdwDA68hzja+PR4H49lrE9CoRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcHR1ZlFOL2pPemljRmFK
            MG9hdHdIRmRWa1BBYlhzNm1yc0JJQzd3aGhFCmhUMkQzQzJRdjQrVjFtTExncGk1
            WWtTdDR3K0JJRGcvR3pQTlJpaWo4NW8KLS0tIEtzRDJaOUtxTUFkRnFhRHVlMHRn
            Uk9UUUdDRXcyajFFdXo5QXUvR1RHcFUKY9kC/f9ZFa2p/CLWNBLzXHHJTWJvdkTQ
            YggAsrL8eO2B+SQKZ3mmZJiXltRKAX+X/lNC9Tz7bR1dWyvdWBhhYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU0xTNGN6K3ZhUmRFK0RH
            akRHdTBxQVM1eW9RK29uWTk4UkRpT2taemwwCjNYUTVXUU55RnR6eVdnaEFqYzlt
            N3dmTSt1aHBRc0Z4NWJURTZwK2Q1bzAKLS0tIE41QU9hZDhkUGpUbEUyOE1uVDF0
            Q0tRYXFIaU9TeTBzeFpodWxMUzU5QTQKAsTYKcv8CSySVuKj1TBkygbIdVoboi/c
            P45vrrCy1KUFPJyiGTKz/YLZfHxMPoH232FOM4HCi2WP6gK+F5OEYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRzUrYjMwVXBCSHd3TEhr
            UWMvL0RsYWlxbmpkNGV2bHBNUHgyNUMwdFZ3ClJ1b3BpZ3lVTnJHR3prcUJBWWk4
            OGt6OVhFbkkvNkp5WFl0REk5VTBBalkKLS0tIHc1aSs5ajNGcnRzbDlnc2EyampS
            VUlDSUZibW1Jd2FRMTdhT3ArUHh1bGsK78FWxDDluSx/VxM0yd6OexmrTZtCOkk7
            WnxN2dF9n3uUlCcxk5Z3XquPo83wYL/5S337HaFeNAqaBXhPB5IfEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWkJXVjZRMGdMR05saE9O
            ZjZGckZyaHozNXFrUm9sWVRlUlNKY0krTG1NCkZreSt6OURKU2hXYjZ5TC9zdEdK
            QzIvUS8vV3IyakhkZzdHdzVOeGgzRW8KLS0tIGIvUlM3bUdVaUMwZTA2ckNOa0Vm
            aFhNTkNyYzMycEdRZFJzeVQ3M2E3QnMKXIe/dH0oJ9raYBU26opRh2qrhAwx/q4q
            NgOeRCXVIjpDrlEmpnI5z0tqP2xpw6GfVHRTPoMpG6U69qLYfkgkmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UHU4TThhNW5acWljRjZT
            NjIwN0R4ekorUEtqYXBxMG13OHdKb0pWd1FjCms0Wk1GcEhVYUE2VUpIVVJFWWRm
            bW9JTTJNQmRlakxDYkxPQjBFa1pjVEEKLS0tIGkrcE5qOW5PSmFFQS83UkJlVmRp
            emJPWjBGRWhhemlmbmhqT1VUbGFhYUEKNpSzhHwk//kbRfmRQgnFnSJsH+vmhC8p
            5Gjpp/GpBVouQLBgaj8TIuYQbQ/jB862ttTWBSTD3zfQtc5M1+01tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWEhydVUrblBqZmFzbmla
            MGJzam0rTVRLVmJneUNzWWFPMm9McmVyQTM4CnJxdGRLbitqUEJlNEhzNWlPQ1dp
            V2hUM2MvVENZRzJoTFUzM3VXbGMvNUkKLS0tIEtWY2diUUNUWjZhbU9SVGJQQ3FZ
            TytWMjV2RG1XaHlueHJ0NDRYWXpnVk0Kz+1RYT+0V32ZK/lQD4wKYhB0oSrmVkcG
            YR3r86X6TeUVmOTI3iODyXS7EmxPWJdVn8vg4bNFkNxU8JTuRAfycA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eUdYSXRkVHYzcDYwZWR6
            NFQveHpVSHl2UnR2aUN5WUZXOTdzQlNCeFVjClVzQjF3YmlwcHErUUxtUWhvMWZo
            QStSbjQ1cWVtZHMrQVJIcTBSSDNiYlkKLS0tIFNvaExJM3YrZ3pMbnpodDdkOEs5
            WGtRa2pEaWsrVTRJL0d0L09wenE3UHMKehLEhk35ADZP7DzJlhZICMsVs9YqStEb
            DsFs9y+/x4WzeW8XDJrElXHIAh9RzfNVANyUCgV7REiDF0sNLRAJOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:sv1Erw6bjpHJc8jbUYMjaOzTfwJ2aNJMfagxra7ag2lxfi3ngYoJGwbHapKQknkqn6sjMSA5SNqpdM6if0XHDapGjSFMPFloFoGifabo1h87NpESqbqPX2mgjuQJ4LNDY/D1RTMDaOkh+p++lVNsrtEI5RJAGWSWjLoa+BUq6mg=,iv:sLlS6vauB6IunBlojwSItvSDARjkYePzKpPHA8SO7os=,tag:yHtt1YyyKQwecU+YP00Fyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
