apiVersion: ENC[AES256_GCM,data:ZW4=,iv:hrx1SdH7M2ymdG8iRp7k8MyuHd20BbKCjzj3a8QNlSo=,tag:tE1bkWtNSliQm2Nhx2pd2A==,type:str]
data:
    navidrome.env: ENC[AES256_GCM,data:b9oxjwCPQ1p2DTZuUBFfegj7Nuyo4w+WdmN6oJrdtPect3RmLgI+25ACNQ8v1dGPcl028ZHWaDR9kEMDoQvP7xyp+0S4yhgCWb0Ellm5TB4z8YRu972tzvpLLr+u3gHSd/oRVWcZCAVkezgkDc3QYjEQ67R9qOhX+RCTthbV4jMzzPqZ8JnQgjC07d44n6zECcBRbeyL/h+RFutY+0FTgg3tMExlxhuQK9vUNgiwn01gl8D5VkCk0KidKTTpE1WU8mRo0vUan0So8FEpAUeuMOh8fbXAG2hFf2+YGaQk7NiZTsDwFvnYWd3Yyp///si8pREvPSjIAIn7CmXq+oDqhfC3bjY5na5gL4AIZgCg6TUP30xgteDBdcx5KC6MRAsULziOUxuX0lcI9h1BDwzUlg==,iv:FVqVQ/1LZ9YMk36ajg2aST7qkrPT8ghuYG10XtvHNrY=,tag:njVugcPT3/KHN+jA9y4Nfw==,type:str]
kind: ENC[AES256_GCM,data:zLjrGF4J,iv:BkD1BosHSCsWTSBmXDJccugCO3aRHiEd3PETX2KZf7A=,tag:2o57CsOZBKG7zRxi1oupkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3Q4DGsOWB965bU8syQ==,iv:ItHJUogV5NyeZEBg6yZt7pY6zeOCC2J+iNPd2XI+dXA=,tag:ih9c6sixAIlZ9/Rey7f9Jg==,type:str]
    namespace: ENC[AES256_GCM,data:kU5VXw/4ZQ==,iv:tr0vsYZ9ZmPS48eLKSjt4/HC/uYF5B0qfMCRrOymDSQ=,tag:O3fJY4fHQjVg7ghWHYSoiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbzh2SW5naEV3djE0dmhN
            cm9PN2l0clRkeHcrRTZXbWhwM0NhNk13RjBvCmRiWk1ZQk5McE1oZUhjOXI5Y3pN
            aTViaEtCWnNxaU1VMzV0Tklic0c5a28KLS0tIHV1dVN4ZUdLaGI1QTczeVFlV1RL
            bzEya24zZ3AraE1mR3NWK3ZyVHBmZWsK8qUsg8EW1tHJQa47wv7y++n569TrYoE1
            RcEIrmF8AE2qIU6CC5qGXYbot31SdxxntIoodLJY0F5PvcG7vCMpJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eGliQkpHajNRS2dIa0Iy
            SmpmSThMOUZtZm9TNlVhc2FneDBya0tXZHhjCm4wWTkvVXpydnQwQmlic1hSNUJ4
            ekRzYzh4QXVZWko0Uy9wVG5WL2wvSTAKLS0tIE1sc2VNQVBWUlRJUGdHeDBmWWtw
            RVZMMkc0NEdJbGNBYi81elMyMFl6VTgKhMXFI1USvzWVfIKyPXuoL9EFUSyOJAZP
            0y68p6omVwflAGggy1nEljNt4Q41KRxkQQqZGvXn7md0KPt/lxlOUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrd3ZYUzQ1dXpkSnl4dFI1
            Zy9UVllpU1k0cG0wWkw4Tk8xRVJMMzE1Z0JnCnE2bFR0TWZkak1nQStvUlB0RGtj
            Y3I5VG5HekZvc05VakZmaHJmaGlWNkkKLS0tIE41Qm5EejArUngzUXJtdE9lZEl0
            anI0dGpFazhSNVZPbGdyNE1uTXg0U1kKZvFDpomwql7ArDBEPRA6ccPBIgnXJ4m6
            Pd908IANGsC9D9ROBdX3kIC3JN99lkMLq8r6I1CDudvjufcLhEdRJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaDBzY1RnVmU5dlVxTGo2
            RUxzdW5VaVM4SlovZUtWSHJhREYvZ0Z0Q1VFCnExOFluQkp4NDVkekVXTlZQVTRh
            c0ZFUlNsalFUUGk2dmY3T0xldUFocGsKLS0tIENPQmRFQnY1VFZNU3NrVHoydlVt
            TEdPY0YzV3N2OWthcWQwRnFmYU1iTkkKJKzZxvMDGqFhxImlaxNkw9NgxvCASf2J
            T0vVEIy671PHzpJwuf0PoQay46ZLRcj9Vlbaj63NAVOTmTS053rLBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsekZDTk0vZTBBTGgwVjUr
            ZDJhQmdEN1BlV280UTlQZ0lBZWJpNFRTbFVZCndGSzE2NFNkMFFhOExUWFE3NXRh
            eUxSQ3paRWYrMEplV0I5R3BkM0lvcTQKLS0tIEE0c254cHZFSXNRd1RtdXFPdTlK
            L3NkVjc2endITVF1QzY1Rkc5M0RsN2MKOyPqJUCoz0spsfjeIe+p5uJr15J13qsC
            78CCplO5S+ggzisxtt9/KQCUvlgn6zN5hBuPLal4Y7Yr6jkRvYM6JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSckx0K0QzSG4zWGRDSmVN
            R1gzTWdzazJLSnRCQXFubTlGbGF5NGJZMVdVCkZhZHQ5ZzA0aFN6c25sVkplRHp0
            cmMwV1F3K2VRYUlyb3ZaWUNtcmlnR0kKLS0tIHpLbnZSd3R3c2pyNXpBNTRrYmdt
            K0RCWGw5dzhuR2k4SEg4TXRTWHF1bDQKEcBO/Qu//0TgBoTL2ee/TNcmlLc56dFR
            dV1VoLJBRk1AZ7zDJwrS5n+i2MThahIQNUbiXfza2TIOvtKOre6W0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUHZWVlg2ZVRpTmZmeVBN
            NnZDM3U1bjRFQ3dSaU5GVnFRYjhTclRTbHpzCkZrbmIwWEZiUGRDVFBubFlRVFN1
            RTRwU0cwamUxWWRUOThZeCtlSmRJRHcKLS0tICt3Wk5LblZPZWo5ZUJtNjhwS1Qw
            NDdpZ1Z4bm9PRFRNaXdRSElwL2J0SFEK5ae28lLySkFkaJSr6KJWhRtugaek2olU
            /q6N04n9JqHhTDUMZesKGpahZqfPyyVLnsupUsmv/D6MELb2Orb7Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNlg5aXhEY3lJQlFTU3NW
            alRxVDhrbEZsOW5ucHJhbTdVZ21Wd3JJYmxJCkNmR1BOQTExb1EvK3owczRJT2pj
            R1hjWlkrOEFmckx2bjdXU0llaWUwS3cKLS0tIDdKMVQ5TEI3NEhZdExzUW9heWI1
            NExMb2dBbkpHdm5IZzMzdUZxVjhpY0UKIoWyvOvHG5ar4itxvi3pbzNPqK4D/3kg
            zl1kByeMXcxB0nayHEYJhoMpzH8KFJFiMO769jyG0qpAE0EUenWyeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUHZNQ0djUW1ac0czOGd1
            anNPSTMxdXhmNnVjYUY1VE56NjRyWUpSekFrCmhHeDRkcjVKNnl3bHFmeXNIazYv
            TERMN1pSMHVISllOZzlWOVdTS2xFNWMKLS0tIGxnVWhSSHVmTWpKdVJvdlRpaWEv
            MTJJVlpJQXY5OUYxWXJRTk04cWN6ak0KRV/5YZowzl22U2Yb2H15bcq3g6/2U3aO
            esMqQma2EglF30h6MG+hZy0UXS7Jj5bmIqYy41UtyHl0yfrVPZp6Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMldZTmRGVUlvb0VVbUt4
            UDQrU0crUnJyVzZ5TWZnNDQ1M1ZQWjFrSmo4CmZkRjdGSFRLZDlWWEs4ZlBkMVN5
            YkFKQ20xVTlnY3FnWjVQS2FvTW5MSmcKLS0tIC9wN0NCd0ZJY1hoOEx0NS9CUUVX
            UHpnNmM0UG94dStiVzAxdXhCZDUyN0kK5FoCUlJF/243Aw58udPl2EHP7eo9TEN9
            Gmkyg0taFD1q4xFfT30tWPlXic0n5GFA9PQ/3jJdIH+eBq2ie5PxiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM1djdVJPZ0NlbWs3UVJN
            WmNIcEdFK2JDRGRLUGZ6Smx4QlU0U2xXYVJjCkJCbWNNWGNTaDVGWXZqb2JtZGRz
            N1J0dzR6NGhsb0xvb0tSQzZlY1dLalkKLS0tIDIwWDA5b2d5eVlCQlY0SmVZK01C
            bVFVVzJLZ0JZR0FFR0pOdUVaSHB5c3cKeIS7AubCTHBjaRNbT3UlegAvFKgU1RSI
            uEsnsoKPjQkHSDZobGJhBgg70PR4tquxkFOhJAETF3y5DzIPGKdE/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsenFXWC9IOU5pWDZoQzdH
            aXBQYWJJNnl3aW1RU3VQWnMrcEMvWHpiYXpzCjByeW12MFppdk1GZ0pnRS9va1o3
            QTgvaHZOWC93dit4U1BFVS8wSW9HaXcKLS0tIFNhZGtEeVNIdWZ6VzJFWEQ3SGph
            Z1ZiWGFXeERGSFFlaGViNExtdWp5aG8KSoam3mWuH/jffm+8X/wY6D1cPqomocQh
            c7Rs+fRkhtuvl7Yh3goH8sxejlHT7/y3YaxP8jz3/GVnXS7mXxrkfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:sv1Erw6bjpHJc8jbUYMjaOzTfwJ2aNJMfagxra7ag2lxfi3ngYoJGwbHapKQknkqn6sjMSA5SNqpdM6if0XHDapGjSFMPFloFoGifabo1h87NpESqbqPX2mgjuQJ4LNDY/D1RTMDaOkh+p++lVNsrtEI5RJAGWSWjLoa+BUq6mg=,iv:sLlS6vauB6IunBlojwSItvSDARjkYePzKpPHA8SO7os=,tag:yHtt1YyyKQwecU+YP00Fyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
