apiVersion: ENC[AES256_GCM,data:ZO0=,iv:unsylz90FtYo7tJ3/ZNsyLVhOfsnxC3JJGlc3v0dLXk=,tag:Pkx1detzcT9g4JPjT9uhQw==,type:str]
data:
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:lSIgm0gYDilCxa4xb+xWTWZG/9P/3oZzTeBMCEQp1tfh+hHj4hhT7Gx6ViXtzJK7zsu7kzbXxPHMZAGWfVsLtw==,iv:wCZ0BU3DA6yLyWdZdpsFtktVAACiIsUCwFzOhc0Pcxc=,tag:nguw8DzrKn4iBGdWnq86/g==,type:str]
    OBJECTSTORE_S3_KEY: ENC[AES256_GCM,data:usxHCFo099zK9d7BYV/bmGGpRqEr3138NDPeoCXOuEO8oWjk,iv:X8yTTNFFERyW6K4yDLrgaVei1FaNJ7nLbEtAynGmgts=,tag:0SvpP8XtS+gNRpaQsOW2YQ==,type:str]
    OBJECTSTORE_S3_SECRET: ENC[AES256_GCM,data:zLBG2G+Lw9a7OCbKJ3aStB3EDi5TUZxN3/0QCVgS7NCgEZuVMTATL6rBEZ4=,iv:mLf/6VYx72Bbt3s0Ex2ieKPpDCWwMZzAQBZ8Czh4ZpM=,tag:35tCQziPg4Y143r40zzgig==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WY5YPtaHlLbVvoh8Mk/ZTTuSsR5TZmkLzbCL8dWzYo7bWcG93qU+fd6erN2qcI4gbb4RSYzd6tj9nBhuID462IRNDEd8g4X4blyehRWN8Gm+c8IUOSoNyQ==,iv:xOYaLb9o0fHcua/gj0wYR8BTKpFYEhq6RbWuxw67AzQ=,tag:50DCrniuFeoCS51Mn5srqg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:0n6SYP9fyBcH915xhpePGhsIKu23svVCMnr7bLk1CA96K69nNcnd4HrLQv8BlGMj,iv:3M5jL1aIgQWrtLXjTpd7uEqMwSS5mWHTQZKrIvmV3yc=,tag:oNqWpGvCORkgyBFefBWU+Q==,type:str]
kind: ENC[AES256_GCM,data:XFnM1wwS,iv:uCrY2sARWNCcKmmdLS4xwgX4wBj75DxjjwHci/lrvrs=,tag:EHLSCJ/tZtPFh8P2CHsPXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8yn97igRWV9RksPmKw==,iv:3I4s0FJDi+oOq7NT0nsQMd9gI1+TPx3RhQH6XPQzkRQ=,tag:cRS4gS07dUfGRzTh1/9HOA==,type:str]
    namespace: ENC[AES256_GCM,data:5sB/UD30dA==,iv:uNkfz1Phj9KW56ql+F7MHWD99jdPEVgAEFNPqVTg0EY=,tag:b0lNxTLqn8WPVM+xeBJW8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRzgxRHVkdmttUU80blAx
            aVNCaVlkN2ltK1czUUliMUxIdjhCd2RJQ2s0CjF3ZWJVUHVuR1E1Mk5idS9WNnpJ
            RGFkMEs2L3RBcStPTnpDK2wyMUEzVEUKLS0tIFJLUEw4QU5KVVNyaHBpQzMxZi9B
            c1dSUi9ZZ05PSXl1RGFMNTgxc1pLWG8K29cRMgzUb4CKgrj/o1ZbvxQLOJMuw3yG
            fxpetnnXX/Y8y2cAH5+rBEnrMbOlLH9AfxcA4redcLp0FC68MTUGWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc0FsYUsxcElic05rcEhQ
            R1dwRFV5YWRWVDhxKzRINjBDTzF1eEZJeDJrCjFHdjgvVG5TRk9IRGtUQm9yREls
            enFpRzVFWkhGaW0va2lGQ1M0UmVQYWsKLS0tIGFPWEhxcEk0d0tqYnNWVE1ndktj
            YS9CcEtEY2lxQ0NwSXQwQkdraDZqZ1UKCnm9Di/GNkORB448hTYBNcOuQZ0eQg8J
            dqMLNFrSNFVDA1L1Hdmf3OuXYAIoTmEDLWcFImCD4JndUGe8Qg3t6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpcg5t420nf72k0c9rrx7amg0szch98uzqu273exj7lw3yu0j99q6vcckn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMm0yVS9CYkxYYXoxbWZT
            MUdTOEJ2ZG51Ni85S2NMejRVOHJkcU5rbW1VCi9OQWpZQWJmUDJsVTBzRm5GQmtv
            cm1wU2xmV2FIM1hUMGJxa0xQREpaSjgKLS0tIG0yNTNuQ3RaaWN6eG02RS9lSWtE
            cFBPdlZHb3czMTc3MkZpSlZEUEl5K2MKkKu73KF/4JUoQxTaFpyDGEcSH5hdarZc
            GlUsydJ3MDzl9GDzggEQS3oSERMqgpFk2fadR1lBFbW95I/Cvs3xMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4mzwe89aqgs56mn8zg7dd2l623kwmw80k90wr2sa6dnlcdmhcnsp4kt54
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSFgvUk5PRE0vcWRSTXVm
            U0ZSRHloSEt6Zk5BSi9JbzZMNGlVVHN4Mlh3CmVybVhWL1VnV1lNcDRxMlFGZnVu
            djFOdHYrZGplZWM5RUlXWDY0dEd1Mm8KLS0tIGUwVnlHbWlFbW9oMVZSSkJ4RkJX
            UFZWNndqbFJFQ2VJeUtoMHlFaWczWGsKTGXrKxZCIeqJVvDTS6lc91wdVvm7H1pO
            BGBdTZ9TOLReHdhFNfAeFWvSycoxO/IuRYwDaOMuvcLc3ypzF9m9tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQTdjZFJhZnlLZy8zeHgx
            ODV1ZHphSktuUjRBQyt2MzV6azVuMmxoM2cwCjFMb2pLNUFjSGFWK20ycXJ2anQw
            SVEvdmJKYm5xdEVLVjNKaUlXRExMODgKLS0tIDg3SHVUbWlhbEdycjNSVmRVRkJF
            c0FQT0VpSEkwSU9MOWNNNmw3bm5RODQKVPPGbKBQnm5INZbjv7wuKln255b3zN25
            y8WOzP+3qFvscPwzMjzX1lBpcwV9xekh9eBUgOSgIaIB5opHdTR+JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZenlsdHpMdE05ZVRHbW9G
            bUpqL3lEZXRvL2hoUnFYSnhGUTNYdEdJcGpNClNIQlMrN3RpVVpuR1VRTzluVDVH
            Zyt3Q0JYOXcrWjNrTmJ5TFltS1JJN3MKLS0tIC8xNmNjbjYydlVXZlp1YWRreEJs
            MzdBbmFleTU4cmwxVkpLeW1FQXJFMHMKnD5hIfOjqoiphTRSnYHuHNgWkQKJgsYU
            0tYvsFAyG7eYj4sWkFFnG6zn5id7k5adnf1ow1WJbf8llCUyUOxVjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaEdPYWxBam9PTWdxWWt3
            L2xXN1BYc21Bd1FreU1pOUErVkZiL3RKZFJ3Cjk4dVhaVlRQS05HYjQzeDNCcVZD
            K2FFV3UwZEdhNElnUTZ2VzBQcmUyaEUKLS0tIDRCeEJWVjkwRmZNNHVQcHZGcUNu
            Q3lkaHo4ZGw0YW52eS9xVXByNlZEWGMKpbuG6yunXOZJir3g3B9Cg6GbTeSlTCVy
            fLWNu+7+zCWAflTynBYg1shpjpLpD2zkf38TrXlQqUtRS9WvhzV+pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMTVGYUxXUkE0MWhxYWlM
            OHY4STZZeHUwQWJ2L0gyZlJFY0JHWEhWMkRBCjA5TFBWMEp3WHFTOTV1OEsxUHI2
            c2k3c2RtY3hyakhCaDdHbG0yRWdid3MKLS0tIDBaUEV1bGJPd0JLSVJ5MDBKYWw4
            b2dRVzRCMk9JRHExVWVQMWRWNmxSVncKBuOf7HW85cdQnfxWHxvQa9KX1PGAygg8
            Y48HZoeVqDivXiKUGDbPquVXV6ULwl4JjUD/V9mNRhWaIsmawNKHRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpcyeqjcl8j0dd4sj6f0vufs2vpus3xn4dvxe3cr8g8rgcm0nfxq03ds4y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MEtsdFp5RHRiRWZVVGVa
            MmpxbzBxK2VjUnA5LytxVklEMUhibTRwN0hrCmc2amEzMDFYbHBGZGI1bHQ5NXRO
            R0ovZU9va09jYUpXNG1VbkhGbFpuTlkKLS0tIHpMazFsbDNBNHVFTGthUXVYQVJn
            a3h1RVVCak1QS3hXVlJwYXpDM0ltSGsKWu/B7l4WNNfOBtEJrSZBMl+pBVn2mg5H
            t0VFd/c9FosSwe4pxNfQiKXiGM39+1wPOhzISoOUsX83cJmwOKPXlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc0NGcis5cVhYNTJneDU4
            dHFTbGpDUEhSSC9iY2RmY0t6TFNiVmFMeWx3CjRmQ2ZvUEVZR2NHRjFGR0J4STNj
            U1dneG5Dc2JpY0g3QkxnMk5yYXltaFUKLS0tIDJwdy9oekZTa3pLYXVrMjFCNG9J
            NXJlTFRrWEVmMExIc1ppYVlsK0xGMlEKXkkuZmHhfM2d0aLZimU1Bq5bUmb49ecR
            LL1PTE4pB42QfMrM7UUmjZMtQ1MrUHghWMXhZYH8KEDlwaZKm8ITqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVElYRXFMOS80ek1kSnI1
            bzhwNlFkOXlwUm9KalZQeERzWDhldndqV2gwCm1nQVZSV0p0eTNLVjZvcTllMDZ6
            ZDc1Y3c1UEViQ0c3bm5YUTRIOUhLYm8KLS0tIHhKY3daRWlJbUc2aVpYOUV0L2ds
            YTdBMmlJSWgrT1BYb1M5QXZjNTI5OTgK+4KrYgMqnnfTJidc/CQewVSx4+Dquxj1
            x7KjOikK75CJZk4xac72PNK3OyZbj+LhrbIVubnR05GKOQcwg59mdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mhrzghrmprq387xqsln6996yx3ja2e2zpamh9mtuu9zqmxahunqg9qugw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOG8rT1BiclQvRlYxTmFz
            bURMQ3NyTElPQUhXYytrWkZaSE5mZzN1azJJCmRTNVBIKzdYQkJMZHZQTDg2N21L
            RlpNNFp3aWlvMmo5L0s4Q1EyaVRHN2sKLS0tIGNmb2FzWm1ZMlFIbWF3dVBld3lm
            Y0dIUlhuNEFjeXo4OGp2NXNEOWNTUjQK4hZchPFaBM0gU5p5uGPQNoi1CXgLIf79
            habu+mYaNRwYBl6kuFURLAz45KFZGk+e7Kjj0ASBnyNB5wmW56plDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRlU3RGpjd1ErV2JQZnhC
            bkZJbHdFeTg2b2prNW1GdVZIbGZOejdzVGlnCnUzdTdhQmEvRVJFWWVicFJFemdv
            aVlPTi9WalN0RUJIUXRjV3JxcEh4TmcKLS0tIFhaSjNTeFFSbStXRjhuOTIwSUND
            LzVpMXlOa0p3U0xYeTYxaGtxOHFmU1UKLN55KtfBePvL4AA7sOgqpacOsqOdjpxd
            GDi3ELhiO0jYZ1JV+kAPRT3Y5qcnuipBhu5JdqCfvnptH2RkukwpKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWUovUWRKMHJHQVhDQUM2
            QzJ1cVlxQkZUSlhKSUEzcnhNM3ZJcG1pY3d3Cm5VL1Z6RnRmcjE0T2t2TSs1dFp0
            V2JUNm9jSUlscUdsYmR2MXF6STc5c0EKLS0tIGVhVGdmQmcxRG03c0ZWVU1kRHZu
            VVJzNU5nSlVCOVJCOVZwUCt5VzRWRncKRGoGQbhKgJHA/yKU/TM8vpXm/zz6HOZB
            w+0rEVj+C0g7wZlvtpFN1XCfwbjLyPXpZrGkH83j+MV52FtpVURmhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f9hd8fu0694rc3tr6hwxz3ldfpepref937rmvqdxvvsr0kfcjdxswyzvw3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YWVlL0xwRGIvUFZuV1Bt
            U1JCVCtGZGI4eHI4OHBGdTVqL2NzRnRJdUNjCkpDYXBUbnkrVjZLSzBiUmdjdWQw
            MSsxTXpJOUQ2cFE2REtUWUZ3VXBOUGcKLS0tIDYxVGNSaFMrdXdTaG5aZktTUHdu
            UDdvdjJhVXF3bW8xbXdwZnV4c2xDN0kK2KIz572jVq2TuNA/4t/tH720xcbaPQhP
            KXrTZa53s6M6kE9QSI9Df/PhDqIJ/7svPCD+9HCXgu4mEDkJLG5hug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RXg1VlVsOVlRZzl3RTZD
            K3ZrMi9oUk0rdlNBa3hBcjlDczBFeEhXbGg0CjlnczZpRWczY1JJVktFeEF5TFNs
            SnBRZzNYalNUZFRaNnF0ZjVwaVdsa0UKLS0tIG4vZFhSRDZSQXdrcGoyZGprSHZn
            eDVZVGE4MXBEVnRDQVd3cGJMalNLdUUKoW8S/ApvD/q0w9CEraQWqPU3JeLeYmx0
            IwDbK6imJ+bOAgHectTCQur1FW1yfwXFXMo3PNJPi3F7fSzajscnHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RWczUzFCWkFCbllrWHBX
            REtJSEZPS04zRVltcVArNnZ5MjhGeGJUS2lZCndJUnR2ZURUZ0RGYlA1bGFhNnBo
            ZWxzMFZSS0VVYisrcmxnc1NueE1QR0kKLS0tIFB4NTZVNERNM2NjV2JuNGVWRHJ3
            d2NPeHozUy9qUDRZbzhYRjVIRGFSRWMK+IBYOdlukRCPEdxMd8DAPn/NYou2RGMZ
            0Oqtkaq3KKel/WsbCKv0nNM4KZfQlUBq5Mi+1xIFIx+w20eZBemLTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISmhnYkx6UE5NNWRjTFNO
            K0NCMUJLSXZkbVhURHJsQ2dpL1R0RWJjNTJrCnIxT1RraTdFTHRRQTZTcmRPNTQx
            MUZQRTd4NFkybUxQKyt0UThpR3ZwRHMKLS0tIHcxcGVaRTg3Nk02NnBmRnREZ0wy
            RElvcGxZTGpLVHdqYzFiVGdUNHpheTQK+6rKv8dX0wYE546GesF5jJ3PF2ZWThpT
            8wu4F9vFpZe2GQgTJQxF9dGmN5sL3oY+Y4PloZmeW1SHFlk0nP/zQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OUZCMks5SjI3OTdEMm5n
            NStOUnVSUUtZV1VYVS9RYmN4dFlNaVVTbGprCitZdXlZU2UwSnFoZUlHN0trTDda
            Y2lUaG1IRWp5UE1icE5PVTMrak9sUGsKLS0tIDFlbGJtQ2JpTkpjLzUxSllKOGxz
            VDYzWnZPS21jc1hyeWhzQXhpRGc0Qm8KD8Xfg7LloYRON7qzxJQDSyn6iZ91W61e
            T90iYT37aqsXNb5C1hhvi1sRc/vqyTy474Nf3vXLmfM9o1lTRh5WtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sukfru07msq8fm5ddgym23yal9lfm99090p999p09mxgrrwh9aqs6zp4fy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ1d0UTI5Vm5pOFBXbEtC
            bS9HQ1ZIeE5wNHRLOGJTOUNGdG5henR1M1Q4Ck5KR29wakp5YjR4ZnBrS2MyWDl1
            NVRvbUN4Wmp6dVNkLzdTa0RKTGVHSFEKLS0tIFRmZmo1cjBjQk9qSXRvQjdtdzE5
            b2RPaWJhSjFpOU1RUjRiZTk4eFFYc3MK2hI02Uk0P493coq8t2WNKxNCxUgZLtT5
            IxKl7SL0V3vo7Zf1bRHdhosYOrmB9gZqYnTpoHvveFKUxp1rvSgvtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ephzrpgftmvq4cul9766q2r3mss38xu6un74ryfmw0729afysghsh0a3qg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaczJscmZYMEJzUVp4UWVj
            bXppS1laTUxhYXJGdTEveFZqOGpBWG4yODBFCmVXNUJNd1JsZE5CNkpyZlMvUzFP
            THk1dmozRGNjam1FTEV1YzZwSTF0TmsKLS0tIEk4S2o3M2pQVm02UGcrY1JLYTBo
            Zk0rSUNXSGJ5NE15N0JONm4yZ2Q5eDQKnxkJqSvd0W/x/OBtu7DWWa/s0qJd5tD0
            MK5E2gLWUfW1ENboWBkTPrruzMQVaN0AIv7KYgA8tt0Ef/9aB2HFrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNXR0bHFmZ2k1WUJIQ1hO
            ejU3Z1E5TXlTR1FTZE9zWDBxd3NpZ1RQd3lNCkJtclFtUDU3cUxNVHBZczVvVHpS
            UURNR3ZrRnM3bW1uTGV4ZWJ3RC95b2MKLS0tIEdEU1JyaStlREFZc3RNNzUwVEFy
            d2xLL3dRakJVVU5IQVlCNXhyQzNiSTgKJqVvRfIKm7mYKoRdCD205XlkeaHpNZpK
            ig9Faw0it/sQHnhvHNeTz0xUJRv52XYKmDTvIcFYnetSWHHfn1r3SA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7ecrfntus8rvyprzhffjpqk2tmrc259knf9xqajlrqvewfp8d6svwp9pp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dGJSMGRDK0krYUs5bjBk
            RHFkRXlGZDIvdjFqMXpRbEx5dVJpMGVtUlVFCnYxZlRxOElVTHpXd3ZrNUpsc0xY
            cW40cEdLMEZtVk8rY3J1UWh2NEVvMW8KLS0tIElud0FxVlhOSVd3bVpPVTNHME1Q
            OW1acGxRREg2ODkyMjdKQkxPRTMvUEEKHACcxQ1+qp8bbChm89DHJyDlUXReRpY2
            i2Z/s6AQHzTlTSFK3avxHLN1NhUUXHzbJ/ucvkn51lbo76oeQulF4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:YXhTz72+FQkmRFkv/5XMQOMWi9LkMbtZmYkujgjmatQ5fwNalt+3k/WC0U/gdAfp6WaY4ZNFq7/bJ7SACDIILZOLfc4ZU7YDMZ5vGZcSPT5NRIe5hStcdNxK7c0UKS4Swpv7Z1M5vGpSWf1klYaAYyri1FZGfvsRsEhn9+Rmp+A=,iv:RRr8ytyYSJ1i1nAtBAU+g1KKOsP6g9tFyci2hbZgH5I=,tag:3mU+bb+Znc8x4Yx4m6zYYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
