apiVersion: ENC[AES256_GCM,data:t3s=,iv:h/i7yKXXhiVRmCSD/UopqnIcEHVm0mWZuw7ngf9nXHA=,tag:cmnV2eBzPomYdW3WCOA64A==,type:str]
data:
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:vqEfboo5x/Q2DHJhag91ZiSK1atkPuEmxjngaM1a5v8YAAKxGcXDj3JTuH2r+iOgz3cM9TVocQ9uA6AVVChGMA==,iv:uyaTyQWsCMTrI2PDduTyYfXWS7U6YJ+oY0KdxN/VOeY=,tag:QOynD1IEa2x6Y15YN+SI4Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:N4GdEDGhzLkUhfyosthFq2RoWeOhCd0mzdmXXuMd1Xqdh6jq1ccZYO1C2fCU36Fi7MumkeyzmNbnJ9JweTKUXIzCi2a8B/RC6UTIiaXmYUZ0aRKfJIJyTQ==,iv:j8r9Cp/cvfFs27zNLkB3HG1hnhwvi40gwfxt0KsB5BY=,tag:XWyNUsUykhyh0IaxCQ9bvA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:iUBie6pwdHfNmjJpYT0ENZ8OG5yRfyRLgKiCK0cjVqxoh+KXCuLg+8Q6Axkj8sCV,iv:dIEg0c2eFQUxdyaDPO64Kfnh33AnE7MGS4BQqxHEwUs=,tag:dFNKatRVmjckhbi7dM8rKQ==,type:str]
kind: ENC[AES256_GCM,data:uSHbNk6Y,iv:F4CwlA8zsLAtYo0P3UP1jvUQSyI1PR/GSTV9oyzeznY=,tag:iTlCglEf/gY+kKArXvlLgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xNqmQ5PzKQYtQ/pjoA==,iv:lVvKi568ny0F3yqca26mDHCOekKOLI+e9dzFEK2CYho=,tag:2AbNNAx+dW3Wh6cMCte6Tw==,type:str]
    namespace: ENC[AES256_GCM,data:2vqvsmF9lUzC,iv:uCU9YeZGdAsoP1wzPJZ4ixHYDruO3e2m8HtP4Hk+qBk=,tag:Yi6m7YRciHxdSZG7yzIy0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd3JRR3N3T3JtWm96WHpi
            NlR4SjlHaXRHbHFkSHJ5QkdLSGhIUHBnMWxrClBvaGwwN1MwVjBzTWF2TWMrM3Fw
            NUJqeHVBbDNMSm9QWDA3Ymt2ckRBeHMKLS0tIHdpR0dSclFzMVVsVlRKbW9KRzd2
            R290d1Y0eUZGZVUwYUN0a0VxbkJkbmsKsKT6YxcGK5RGtIE7HwbSwEa3Jdosd7V9
            MJ8TysoLVNQFD/OiLukNY1/jSgcSx+Kie9o7WObh+GHnrhR4/PqUVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeGNEQjh3UjdCYVFVeUk5
            UFNEd3FKSjhlRU9WSlpXTlExVDQ1MHVaRUVrCnB0RCt5bUF3WC82dlRTZUhKOVdp
            cWdCT2RsTlFOWTVqcEg1VHRZb1FJaDgKLS0tIGdQTnZad1FCTTd6L0FDVHhjaTNM
            MFpNbE5jc20weWFMVDJiN0MwMlFOZVkKvZEJnqSibuNfyE/4tn5vbPFINtfy1dxU
            TyWbyuVKfrIMXLyR1yay27B/eQOvMWwYrDMzOjva6BDQQwZ/pPS0nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFRndzFodlRucEFyZjd0
            ODBsQ1Mwd0VTejltWlE5U284cm1jRk9zUlhRClJUM2l5TmJUbTg0OGdzOUxXRkw0
            d2piUTIxbk53RUJINmU0eTYwKzBQOEEKLS0tICtrVm9VUm9WZFhJZGNENlI2cm8z
            bUQrc1U5NFRqanlHckhxL01hblQwd1UKsyZsjlprl/QRNbHRiI0ye/9XYjNhQ3v1
            cC6+BjrMXccerT8T+qroKZY0NbxEZDJPePk3Ju85Fj55pGbbVq2trQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdDkwSkhCVno4d2JhbXlp
            bTdqK1lyT0JCbzFCZEE3anF1bjVQZEdiSDNFCm1ySEJUMW9NOXBnTjY5TkhZanJB
            NWhmVThoczg5cjhKbnpvL2IwMDg0amsKLS0tIFhqY1h6Q1ZaNDF2VlZxZlprcTBO
            VExDWmlwb2lpSVpYUkJKRlUrbjJoZUUKcUzAixIVmjP+VklfoLJ2VbUKyThc9AD0
            HXKYSSCZsGw+PfUFDn6qyI7+6hC928Q0iJozJKNF/c7v7zTWkVayxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMk9pS0RxVWVBK0ZMTVVK
            bzRTTTZGeTRqUzJycXVjSllpeVRpOWdFc1hNCnJ0ZjhDQjZTOWJFR3AvUlF4NGNx
            WURNOWFjeEhSbFhFQWNackhDZ2oxd3MKLS0tIHQ5Q2tTOWt2WHhwWjV4SDdlbkNy
            N1FPRkhMWmxWNFZtWVhjQlQzWS85VUEK3QEgk86kirUfXXfjrANx9ngPD1qC5Egq
            6shIF07Ubj2+iOf2XQwVnLRmfwlmMK/LVR/blf0bDY1d0J7eGSxrKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTW9id1c1WE5ySjlYVktn
            ZXJnWnBqMkFCcFYzVjVlNFFiMW9tTDVtZEhRClVsanlJdldXQkplejl2aWFEeXdZ
            VVN4d2wyTU52MHRuSndJWGFaQlRCWkkKLS0tIFZ3QWcvWU1RZFFWTGlXK1BNNk0r
            Nk9wSFZqTWwzS2E0NWJoM3dzVDNSWDQKkLN9QB/DB0dn7uQqG942QHfrrDWzuRxs
            hJgT42QL56tU761EOrkMzfoVJqGBGRBOGPw4V7Ip/YSlAf5+rbeXEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNi8vdmlLOC90YkNEcHN2
            SE1oLzdCemF1OFNtdGdFbEs5M0RURHhSMFhFClhhdUdLOGQyWllubnBNWE91ZnVz
            UXE0eDdKS1U5enMwUTRxTXpJM1B0M3MKLS0tIDkzNy9VSjBaUm8vamt5QnExT215
            bHFYZXFGRWNqVWRJd1lVYlBNZEJSM0UKmhYrgZEowbP9wjGGyFe3fIOIZeDhSZqh
            hQL3/+0OP8xhQwhrA1y/BM2JP3332Kf032gtgArP/FjQ+hr5fM6YHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRTFRbFh0ZHFvQjNCT2V3
            NGdFM1kxNTBIOUlISzJqZDdseFlLNzJLK1VNCllTT0xpVjFGN0hrRk00RnptTkpQ
            ekxiODNFWDUxdUp3Sm9RdDdHLzFFdTAKLS0tIGdxMjQ2RG94RTdrMThGdEppOXlI
            SVhXY0RSd1lGV2RRZmhhM0psWnR0M1EK/rh15lwk77aJTI6ej63V8Twf0ggnPspe
            aK4vXSIhGExaKgmS58EKF6Xsq5ugWv3NAoTMZf0Bf9QT+d85/6aQvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZE52TEYwR3QvbGk4RjY4
            bFRqdFpjcktQVVVnaVlTcm1xYWRvUjd2eERzCnZ5ejF5a05wbWlzWUtuUGp1ZEdY
            alJsMVVQVFJIT05IdUxJVm8ra0haelEKLS0tIEYvK3BGRTJyeHhZcjczb3JFQ2h0
            WDUzYythUkNzb0NQb1ZGYlpVRmhZVVkKczjgYc4zdVnEobpPqGwORtxR6R/tFMIX
            By07XVnlQkihGiiN9DPDskGLkAznNqejcsF7/mp52qEUFu+Bwgakxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV2pUR0hQTmo5QTBHQ3lu
            VlBicC83ay80Z1hrNmFjN3hWS1I1L2p0U1ZvCkNRc1ZSN3VFTUhsclUycTVmUHZZ
            TStOZmRDZkFUYzlvSmZxNzZIeEE2ME0KLS0tIExSMVVHR3ErU2dPcU9TNE5wWWtS
            cDVXZFNuUDV5cUlPSTRuUGdTd0xEdVEKlfUm2aRRbhrvFrb7CdLyV2rrPZ2yulJT
            bYcewQflIMc29y8ooDKdGzskYdB8ozDnqxarv2K/I5YVjLgiX2VVOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUTVINCtxdXVmeXZsamVQ
            aHNzOWxHYTJ6SHR0OWw5OTZpUlRWWXd5MlVBCnRpNWhZa0sxSmhLelVrK0xCRUNS
            SGR0RGJoMmJiQ0lsMk5VM25tY1IxcGcKLS0tIGNVQU1PR042OGtqVkJXeUVNd0hu
            akk2QmMwc2l4di9zTnpub0t1a20vOU0Kj9BKZgH03Vif4cduUQEqBO8qwP7aLuro
            B6RCLGuXlAYFxC6eAS1JJ4SWkSiTsTbbcfp06Ua59v6sXihFaJ8T0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWGlHRVFtRlplRmVURk5r
            OU9KbjdBaHFoWjVFdFFWQWNIVmdTQXBudUZjCkJDSkVhV0VPbTBRYUQ0dGRuMjhV
            cDRyQWV6MXYwREJvVzluT2c4QmxvamMKLS0tIHZCY1VNNU5BcXp6R250N2tacW1o
            YUswbENibVVIMTJOVWoraEZpSGNWazAKXWirM43zI+eL32+Wr8nw1Bdgd7e36igq
            cO3ZefmLl4yZ/Go+qC2ldtfRUE/0hrswh5OthdTsGDX5MYNIstIq2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-08-04T17:38:48Z"
    mac: ENC[AES256_GCM,data:Vtq0cZ4EDK1rJqRUptEK5SoDmWWForMKTG67O8tX59rspGm+Xw4P7D7hp1JO1GEnXtMTfVqiAZ1GI1+cTsbo493AcP+sXeJ/XY30UhCmKuc1S2phn/ATNXEYF7HhYlwJCiYvPqFW9DWEbQI3n1ROSw9+OsySfRWKcWXu1FdLpN0=,iv:5m0p8so12JtVQb86n8c9VReJwstkvcYoJeNtq8aum3k=,tag:VublqPwa4cicFcgK7tuTLw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
