apiVersion: ENC[AES256_GCM,data:t3s=,iv:h/i7yKXXhiVRmCSD/UopqnIcEHVm0mWZuw7ngf9nXHA=,tag:cmnV2eBzPomYdW3WCOA64A==,type:str]
data:
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:vqEfboo5x/Q2DHJhag91ZiSK1atkPuEmxjngaM1a5v8YAAKxGcXDj3JTuH2r+iOgz3cM9TVocQ9uA6AVVChGMA==,iv:uyaTyQWsCMTrI2PDduTyYfXWS7U6YJ+oY0KdxN/VOeY=,tag:QOynD1IEa2x6Y15YN+SI4Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:N4GdEDGhzLkUhfyosthFq2RoWeOhCd0mzdmXXuMd1Xqdh6jq1ccZYO1C2fCU36Fi7MumkeyzmNbnJ9JweTKUXIzCi2a8B/RC6UTIiaXmYUZ0aRKfJIJyTQ==,iv:j8r9Cp/cvfFs27zNLkB3HG1hnhwvi40gwfxt0KsB5BY=,tag:XWyNUsUykhyh0IaxCQ9bvA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:iUBie6pwdHfNmjJpYT0ENZ8OG5yRfyRLgKiCK0cjVqxoh+KXCuLg+8Q6Axkj8sCV,iv:dIEg0c2eFQUxdyaDPO64Kfnh33AnE7MGS4BQqxHEwUs=,tag:dFNKatRVmjckhbi7dM8rKQ==,type:str]
kind: ENC[AES256_GCM,data:uSHbNk6Y,iv:F4CwlA8zsLAtYo0P3UP1jvUQSyI1PR/GSTV9oyzeznY=,tag:iTlCglEf/gY+kKArXvlLgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xNqmQ5PzKQYtQ/pjoA==,iv:lVvKi568ny0F3yqca26mDHCOekKOLI+e9dzFEK2CYho=,tag:2AbNNAx+dW3Wh6cMCte6Tw==,type:str]
    namespace: ENC[AES256_GCM,data:2vqvsmF9lUzC,iv:uCU9YeZGdAsoP1wzPJZ4ixHYDruO3e2m8HtP4Hk+qBk=,tag:Yi6m7YRciHxdSZG7yzIy0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUW43QU85RlU1VXFHai9O
            ckNzTkNJRldBaGtnOXdLTy9FbW1NU244VlJVCmVxT2FuU1NjV0VPZVp3NEczQThN
            Ri9jS1AxU1p1b1FPNVJ1SzRKQUVXVWsKLS0tIERidmduMjM4VzhOMWRaRUllcThK
            dWlqSFVtNHhVVUxUbDJJSG0yZFlBUTAKo78KHfRMSqnzLrdktC01Zu4/excZUPtf
            SEjKfsXmKcD4b4nn/v2camIlMmnEn5j64mdqKkJQ2Ktv0/eo/BLMQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q3F3bk5KYmM5YUhVM3g5
            TC9rMVh6dW5rZEFYaUFSSGRJbFRzYUw2MUhzCmxRL0prUXp2K0l0NnlKbEVCbVBH
            SjJEbitpY3kxdW5IRSsxUVN3aHI2a1EKLS0tIDBWOWhNRGpEYklTWGgxTlh4YWZa
            RUZRbk5yT2QyYXg3NklJcFRPRnNCcm8K2QM/sFF19Lx8K6Vn025+d32/4dJ/BtM2
            hyx1p2fQ6TYI5a/WbSkyC+JqW/J7WrP255QtPlZyw7oOB5gnAy5iTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpcg5t420nf72k0c9rrx7amg0szch98uzqu273exj7lw3yu0j99q6vcckn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS2RSS3BuMTUvUThEMnRU
            NUFxN1ZiNjd1VmZDMCtxQnZ0d1ZuaDRsMmhZCnZsRXRTMktLeFRldi91cGIzSmJi
            NXppQ0VCd1g0VWxML05HR2t4YmQveXcKLS0tIGtsWUthbDU1U3ZIMzBsVGVjaWZN
            a2h0WDJWZjlPdUtMQTR5RENKVVpMUjQK+F3J1DpuPUHFmkq3awNye7tBtB8Uf9sn
            UkcLARUWmrcxbLg1vOaFxvFMlsSYTY7V0fmU61O2JAym3BfhrU6xkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4mzwe89aqgs56mn8zg7dd2l623kwmw80k90wr2sa6dnlcdmhcnsp4kt54
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTczQzbEtXQTBiKzdHeXdR
            YVlyV0QyZWYwZDNocktld1drU1d0VXM5VkI0CkxQMmFYSXdSeElrQ1NUZU9yZkh0
            RDRZNS91SnhwTndWRTR1dEIzdVJUeU0KLS0tIENIVWVlN1B4MUpZMXNNekVUc3Ur
            SjZrakErOTVQK215SHowUUpTZDB0YVUKBg+aL7GIn3o03uxXuCa8FoCtl/pPWgA8
            HTFAE2QMuKFlHVwru0bQKuyBdN5sBigv3KcmoDb2Ua7ihAjXrg3sHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYkFxbDBHN0I3QnA0VXNy
            bFVrcHNZaklKWGN3UEN4YWVyS3dlNVlFdWpZCm1odEF1WFRtb0Q2NERJWk1OanNo
            ZjZGT3psSFZGQ0ZQZ1NjSnB0WHI3TEUKLS0tIG01UFNnVlJqSmxzTFBTZTl3M1Vt
            c1ZTOUUzRms0Vngzd2lNbkpTMitLUnMKdy5YUDsSTAcUHZKwiLlS7AZGtvpUhmTB
            45oIxYajbXtx5OPuLIwEXDqHeh4tvewbz2/MNA/AnafjMa34V/oUjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOUlMYzQ3Q09DdnJGQkxO
            R0pYZ2xFb3E4b0NJUngyazJKSEt6R2ZBRzJrCmh4ZFl4ZTJhODVWVDA3YUF3cUx1
            c2dPMkpsYmkrQndQQXFVM2FkSDJDd0UKLS0tIEdrQ1NETWkyWnBXYUVxMXRxZlcz
            Mnd1Y2o5WkRiTm5GMzdIR0NTaU95dkEKk/uShyrTA9AUyH5nqTA0Xf/cRZWUewXT
            46duL9mGtnvAGZs0WCjco60U4uYwnoTYAr53oJEpS/1Z2MB/8o6lkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VDRCK25FOXo4Zkg2aXdN
            c01oclRHbmhkSFhZNnlvUzJNVEpiR3YyN0NVCmdNQlh0bUJBb0I5M3dTSjBVaG1p
            TDkzYjBsdnJqZHEycXFIV1ArMFpsczQKLS0tIERvK1JRc2p0cklqWjhyWWp3bVZj
            eGNqcEh6VHcwcllkbVQ5aWNOQ21QUkEKPH5YHAbDt7Vtq3UAPNJhsJYAoMArtRwr
            7o3xEuERFM9gI9ZjBtZjFbnpuXVFTDbYyS12JCYcY0PQ6Q0v+mhZEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS0RPRWxtVFY2Ky9Ubm4x
            Z0FISDVVaEcxRldlRGladk1tZlpqNFdQTlJRCm5CakFGNkpMNFplU0d3MjJDZUR1
            K0pmQktRRW0zSng5VngxclhBRVpIMk0KLS0tIFV4S3JKeVdKZitHTWpPSWdYeVlY
            aVZEN3lPcXlSVG4wWjA4MDMwK1VocU0KaA4xqLr9rqx57jkh7cywwIWndYyp1T1t
            qvMn86fvyCk1sBzRIbRB5BDqF8652/qopyPkFYuJ1XH4IBzvGzt2jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpcyeqjcl8j0dd4sj6f0vufs2vpus3xn4dvxe3cr8g8rgcm0nfxq03ds4y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc0VGQnI1Z1NvWkdBb0JO
            dmwvNVlMQW1DRHBsS3BaWTRwTXgreEpUenk0CnVDSkQzdnZ5ZTF1ZGtCWkU3MnpL
            YWFDanVhdEE5TXc5Ty9pK1FlaityTVEKLS0tIHRDNXo2b1l4bE41ZUFhZkt5UkJ4
            WVIzZ3dQZjlQbzdpeHhMb3ArUCtUdVkKocKel598/TyFa59pT/W4AorysuCYOutn
            NtwyGdTN05LZkGjW1MvjQdP0X2MSHiWoDqdXDsqjH+Fhm4B+vFqrmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbGM5ckF0ZnE5WGxEakZp
            dURZNDRlZHh0TlMyQXowSkRQRVZySS9nZERjCkpjS3Qxd1B6ZUtoV2s0UFlmSFlC
            TFVRV1RUemVvd0VQTDE2NGlseE9McW8KLS0tIGg4bEo4NmljQVZEeFhrVXhPQ0s2
            ZmN1b0NyNjREcnV2RFJ6UXF3cWJ0WWMK4jS7I9tuD0uptgA7It9D+OoZMFbkO+8L
            aX5Aogs4NXz2QxzpFpFiCjq6wXyzwHJnMVVKmoD8yICK6Lq+WGw3Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMU9jOGNuSG1SZ3I2MmxD
            clNZTi9ZWklWMU43U0ZPSll4SW5NaXVGSnpzCjRndktwenhiZzZKb05VclJpRThj
            SG5mU1lSQURxbXFwV3VBNjIvWlV2Y1UKLS0tICt4OC9USFpTKzRXM3ZSMFdPcU95
            bUo3R2ZKTFdXR0FSclM5aXY1TmVoaWcKRZm5BssMVIGg1J52+VuCB/PVmJQHImAC
            eRiyAh0gOZUFnFvX+QWZayrULfuZxLHdAivb6Ch9z3fLaxhV0hcnGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mhrzghrmprq387xqsln6996yx3ja2e2zpamh9mtuu9zqmxahunqg9qugw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcmhtV05ZaW1HckpHRms4
            d3Y0VCsyTU5xb3lubmRrSmt5aTRoNWNkakdVCkJxOWxpU2lVYllBbHV2SzBKWng4
            QlE0Q0xHcG83NkRIWHZjb2duVDhBVXcKLS0tIFNidjhGbWt4VnlyZjRsbzRGWng0
            UXlUbCt1cDlFZ2RYKzYvN1g3TFhIY00KmcaeCOYGTJIBKT/BtHP8OjsVtbKljv86
            WKSrh4Oj+dhsRMUbzrb23hTKz+QXKNFD4XFeZXOOZon+14CG+0r2EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczFNaFJXU2xNdWpKWXBU
            bTltcXN6VVB0SUxCcTdDKzRoamdCWjJ5TEQ4Ck1PNzFVVXhwcE5YK2xxT2Q5T01V
            YkxFeVJHRlFJeE0yYXpZR0JiQU9ZS0EKLS0tIDB4aGVPcS8wUzZjMmV1R0VCaVVG
            U3JoTmtoZmVCenpIbzhOU1A4c3JMS3cKV9+F6qID+EyVk8zwv9L+R/CuofMVRkTE
            dTLm8QHg9d7Zlvxcw70Th6ngDSnyCS/2NxNU9rRc7stW+Z1mcHWA1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENHFkdWVVUENVY1NQQm5U
            ZjN2aXVGdTN0TlJYOEJuSTlCMGRoSnI1L0FNCm9FMDNOWWVzUHRMSThXaTlBaEE1
            Tm80UElHTTRqNGlDUzJXWS84UXBMYTQKLS0tIG5JcEFoNEZQaktpbE5PdE9vUDc0
            SXhOOWY0azdndVN0anpIYytYeUlLb1EKH/jGaYk++lQDyHNVI/tdknA7fQfx67Ww
            D49D5d90RaCOKklsyJtJfrXVmr7/fhefj7QKwsLUSp0O4UQM9dmA/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f9hd8fu0694rc3tr6hwxz3ldfpepref937rmvqdxvvsr0kfcjdxswyzvw3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZnc3UjdBK3JBQ3NkSXFS
            WjhwS0t6cG95SFplS1lveUZKeUtzY0o5WjEwCnY3VDVCSXZYdlNFelNNV0o4R0lv
            dkNhbHcxQXBxSzJOQmpCMjI4eDlvUTAKLS0tIFo0UmJTcm00b1l3bWxPMEFEUU5G
            bXZEeFFTbzh4c1ZaY1hENGJDRmIzL1kKiaal61SR0/FuCk6+uRT6Mj1N8xW5gx5p
            nrnkLTwkrZF08nIZLX+Axjn01uJ8Y6oDvLfSAf3FIU9ZCBe96LBizQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVXlDZVJJcDRHdEI0bGNq
            M0lEV3F6REU0dDZhWS9Zcm5wWTVNalJQUTNZCkNraGtYZFFDMFlMa0hIQkEwazFN
            dWs2L2RETERQSVdqNGJHUFFFVzRNTVUKLS0tIDRRMVNwK3BrV3o2Tk0zMnhCWWtJ
            bHlNOTA5N1lOSGhIL0lwOFFJWlNyb1UK55puG25VY8tJspprEhB4hd8iEBI769QK
            wha9QHSp567MhL1xIu6QNAeL6EkTlV1UXT6NBLTNgTfo0NR1yRu6JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcFNtYXEvVElBaEM1MUhS
            V1hSRGJoQ2tUcEYwVU40a3N2RW53b1g5Z0EwCmtJQ1h1Z1JwQ3grUnJocUtzZjFr
            TU1ZVGNHNW8rSFdZeExxeXdveCtoZDgKLS0tIGVML0d5VFFmeE9LYzAxQTJ2UzRP
            TjcvdE91di9NckJsQTQ2aEtxc21JRVEKZPryC5Dk8LXnY9NKLVKHcG0z6+syT1eB
            EFD4rc2UoQ8mr/I9dYw7GHm9J0Iw0LTnTlTJc+YlS6uA3PLjaX5B0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNS91VVZSSFdaQzRscXF1
            TGtXaFZrL28xRkU4UWg2R001UDc2eVlod0JjCmZ4VUZHaGVTSDNmZGJ6RHMxVlYv
            TTQ0aHpLdTcvN3FabUVXb0pHYkNORWMKLS0tIDJCbE1iUTAxSTFxK1lTUThremZi
            S3d1ODlCVlA1OXZlUTVZMC9YYnlZek0KSjFbUM9yG64+2FWLjWx4jnj9EMIZ9xNp
            /t6pc0Lz4C8SiRy+sjmgTr8RgTVMbzBLqLxViJ4VKSaCE1FcMU9UBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOHhyNVhJNG5BQU03T0I0
            RVdHTWYxL2MxWlpZYmhZbitndy9IMjJVUVdjCkdzcUl5UFJoOFF0UWNxWEdYK3R2
            Sm9OTS9qa1F0SWxYKytJclRXVFpWMGsKLS0tIGhIV05MYU5YN3BtaW53OGV4VHFN
            TXNHSUZxaFk4a0RrbTFjSU0xc1VyS00KYyCq9qmhgfhgopaT5IBFTPjaSjkXpQuJ
            rTw1hhJYlmV1jKPJOeFYH3Jky5rmYFOwaPDMqVcg9FCeVnDP3is07w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sukfru07msq8fm5ddgym23yal9lfm99090p999p09mxgrrwh9aqs6zp4fy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c1JwZlpPWlFDSlNyMytO
            djBEVUhqOTJrTG91SWMwSmt5QWVRakJ2WnpVCm5wc3k3eWl4WEFMYUdqRVBYNXJY
            UTVOakovVmxFalZqYlRPbmJ0RVlxa0EKLS0tIHdTVXZqNG10NGV6d3NPZU1OU0Zh
            U1RQUmpNNGZaMkN4NUNyUTRSRmlidG8KXatwUBmiXukNrA19ZT4Mo8d4EGvgnV+C
            s7kOUjetopE+3NbYfb9hPMQWcwupByBHt8qs6DTCtRalYlRQgqbY7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ephzrpgftmvq4cul9766q2r3mss38xu6un74ryfmw0729afysghsh0a3qg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdGtLNThWZWdPbG42ai90
            UkIraU1kd0tLWkY3emRkR1k0TGY4RDc3aFFFCnBGbjB6aGJPdkdzc0RYV1RyNFRZ
            N09NYXJwb25nYkhmTXFPSDVQTFZvMWcKLS0tIExjaGZ2T21EbkNEUnpYaVRKZ2hI
            cFZOQUwwcFlDRGNRb21jWXhRWFpOencKxkiRwt8oqLuwtFD/2hTZMwQpaAfhKfnd
            CJNw6PGg2tvDuCUe5suq/Q5LVL3qWQxcpSyYdk1rEzW7fHejfsxb9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeDYvVlFzbE0vNDNHK3Rm
            QlJ1bVhCZC9UQTY4RDBqd1Vwd3BGMGMxdlg0CmY2dmxhcWNlTkpCanZ2UmpDZFEv
            TllaeU9Udm9DZWdJVDB5L01abDFzb00KLS0tIFZGMGE1ZTU2dUxtY2tCWXcza21L
            bFBWMG9qMmhsUjZhMjVjT1g1Um5uUmsKrf9xmzF/N5w15lyad7tHwiZE4/Lf4MZ8
            /E5yo5H3K/zVWkiNhai048MhNkUlmQHdGeANlb1zOQrIH9beqNDWNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7ecrfntus8rvyprzhffjpqk2tmrc259knf9xqajlrqvewfp8d6svwp9pp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMXlodDZBMElneTloblRD
            UXV0emZPOGtGc3lvODFOd2ZyK09CTW5paENJCkFrZEpKREcwa0RRS0pTdU5SMlBB
            RzN0b3lhcFdNbURtbHNlaEdSM1NyYWMKLS0tIDJueEpEYTV3ZXVWME9kcHdUakNP
            S2xWdVpYUEh4aVhFNkc1a0pFVDE2VFEKAiO6aliev/v6d51J0efqZ/b3ttBKFrkp
            kcvRxBdyBgQF3H+3n/i6Ptnfj+EFdmDCrUFT+wYAMzcXWnPPylEvLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-08-04T17:38:48Z"
    mac: ENC[AES256_GCM,data:Vtq0cZ4EDK1rJqRUptEK5SoDmWWForMKTG67O8tX59rspGm+Xw4P7D7hp1JO1GEnXtMTfVqiAZ1GI1+cTsbo493AcP+sXeJ/XY30UhCmKuc1S2phn/ATNXEYF7HhYlwJCiYvPqFW9DWEbQI3n1ROSw9+OsySfRWKcWXu1FdLpN0=,iv:5m0p8so12JtVQb86n8c9VReJwstkvcYoJeNtq8aum3k=,tag:VublqPwa4cicFcgK7tuTLw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
