apiVersion: ENC[AES256_GCM,data:fsk=,iv:JnKRWmDlPwn5+9ByCMKDLd+ZzShJ7nl1vWFVaRhzaNY=,tag:NrAVKbCio4QftnIlLasUgg==,type:str]
data:
    password: ENC[AES256_GCM,data:rKuf13AF1YrWUIxXRJDXZLVVxSTLq9ZOmVM5azgGhEmNAb2TnokEK6mGw65a/4ltHRbkXnx/4MboOQObyF1MprrosH5gpPVW1AQMsotGlWonT451AOTZEw==,iv:9/4uAGN+LED0i8QH1mkmrpJiFnXdq0G+tqAxKWwMThU=,tag:H2U1bzBDnMuGym4Yq0uqTg==,type:str]
    username: ENC[AES256_GCM,data:yAV0kTChLe1DkR7j,iv:X+jHgP7tj3/uQI4yo+aEd0D2+j3CmjFXJOKHc0nA7Cs=,tag:uJP1Sf3H5MmwoVQOHV3lJA==,type:str]
kind: ENC[AES256_GCM,data:QkCdO4kM,iv:8bLZai/Mi0Sc1mMOFKTh/vJvVJzLjtesQ8X6EX9ZUm4=,tag:sx8Ri5Axh1pF8QDjufjljw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cDWwgwnDiGC6AgtNYsj3n29x,iv:77EacuyMTJAjxuvrVyir4nqGQ/k0Kglvg2kWnYEyJAI=,tag:xYK9msMxatzoLk2I+UHUMQ==,type:str]
    namespace: ENC[AES256_GCM,data:hS+pO6CMLO2YT/E=,iv:MZ8sprf1aTNohEX10/zZsxPnBwxZH9jP3AohzFax2o4=,tag:ie1wVuLvNYnpe+5PdRfw4A==,type:str]
type: ENC[AES256_GCM,data:+krNHBW5VLIxEg6av+YCSk3F7hLspR+D,iv:Zjzm1wCy3UeeZcTWK3ytvEOpQTDeujnW5X+JZiRAR3s=,tag:1D2kZ7bvDy/3sSXgfzDDeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUzBlN1V0azB2ajlQVjU0
            V29CWWNhR0VUZUptQTcyZVpDZThjTExVTm1jCnZLUWY0a3RwWm9xdWFHRTZ1WVp0
            a3RRSVYrVExaRkUvT0JiSDNqZCszWTQKLS0tIFZ1TkxqbGlYa0xmOG1xSG9sTFhJ
            RTRwUVVTYjdKRjhyOHZaY09pYmhqQzAK9N7+iCgcNsjgOYue7lfhSbw0AlJeDvLs
            F1pwxycncYAw88ddc+XJQnTUtzTVb+Ro1tPz2n0K52rC1Q+jj1anqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMG9uMHlPbVVsYTFseHZs
            R2FQejQ5NnByQ0Z2Y0pDejZSTHpxMzZzYVZZCkZ3a0RNaWl3R1dMUHljY2xuTGJO
            dDArNXBLMmc5b21hSVc0UUw5V282UDAKLS0tIEpRdU1hbUNVSDZsVlVEcFFDdHEx
            VU5UOE1WeHZXbjY2OG5iaHJYcWtjZEEKlUULogNURkGw/3gYYJMnMt0h33vJK3wf
            QUQvZOgGBk1CeUOWJaQfEaig/zMuagXftu8F0cZ5+4+yTWIhtDCX8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweG04eHA3cWk5cU43SlQy
            QnZMVHo4UVVOcG9KSlpPeXl4MHdobE43MkFvCkg3dkpnU0RHalM0SUc3YkpORUox
            K01kckp0MWJkSmYrQjdNVit0OTZ6dWcKLS0tIFRyUHJKUm1EQVlIVDFuUDNlcUVU
            cWNqdmxtRUxDdDNTeWRiQVY2UEZ4NlEKAO5TtTCfq4+OB02Xd4ro4H1K5gj8vcWf
            SXqnSiMyhyfnENbuQhPMvuwgQteQB+5L2BtHZ4Ypz1cckrXuGYcEzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbnd0VWZucnV0a0FJL25a
            bFViQ01QdXprcVlpek52RGlUcGlVYTZsMEQ0Cmk4UEFHZnpiV1FzYjY2M2QwQWg0
            cFdRdFhlS0o3VFJaNXp1dm9hQUwyYzAKLS0tIFBESUw5VFdwOUlXZFhIZmVQd3FZ
            R2VVTzdGYzNSMjNyM0J5NlRDa2xSS1EKLmbVhFY+EQ0MZFS11Tg7FtAevevh8gCP
            KmlzvMiUKsk7hGRTHc6OQ2AYD9HnuTVLUalM9ob1Flsky4USgJOqlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSmR3NXdiT2QwNXNzQjV3
            S05wZ3dFU1BvdW1ONjl2aDllOUg4b2cvb1U0CktQNGJmQ2ZhWUFIWEVZZnlhTUNU
            YUNtUDdwcUxYSHRpWWpXRk9tdHFMOFkKLS0tIDRSTFFaaUZZYXloeWhza3lERUE3
            MDNta2E4dzAxYzVCWGIrNFBSZ2xjN0kKv/xp9zf83O6eF2DN5IwSWm4irB52cWH0
            wPL5GjWL4VoQCKBXVwDYGEFciqCjbST7X4d21Nm5eTzARNmDeYJaEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cXk3ZUpNVFdxbGUvVTJ5
            L0cyY3ZXWkw0VU81WDM4cklNdkJOd3pPTUZFCk5EbmkwSTlWNkhQc2lwZGxqcS9B
            QTNxb1czN3J0RXFNWHh0bnJlWGhqTEkKLS0tIDJVV1NHb0lmQU96bmdXWkFHcHR4
            cnRJeFI2dHhIK2EwcWIwKzVXQWg2YUEK1ZDI9PH9TvfTwqV7GWdLNbLYqXwmv5W6
            NUie8LZ3GFovs7Hp3Vn9jaMzcC9621zPwBqMvRXMiAfYnQZeaTFN/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3REpZeVBmMWRZbWQydTcr
            NHBzNFJtQWdQaXVzWkVHTzdkNHlvMUhRZ2hZCnJ4dzlHdkhrSTRGakt6ZGEvQ0VT
            MmY0MDBBWG1JUkFjdlBxYi9UTXFhZncKLS0tIGhSNFR5amVLaDZKVjV4VThNQWxD
            NGtLQUM5S3Q3ekZmM1p2enZEbFJRQ2sKatYm0Fe2+a6LXGFzpMqTRZ2CbgH/T48z
            K2cXaD8F34gQ8ENzSnHBPB34OlaaEXDbnwfnVKPim7bJeGGHYoguIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNSs5SHZPMnVHTWVoRngr
            a2pKSC94OUE2K0dUUVVjS0dzSUdOM0VCYjFBClJycGV5cld1clRqUHNuZ0lZWjQ3
            UGRyRUI5TWo3UHFWZ0sxaTlNWE4yWmcKLS0tIERJQ3FkWUR0QmFwc0oxSXQ5NGw4
            SW5IK0VHUWYwNzQ5UTNVcDlKMnA3RVUK5E3cy/eBFmxpaEQfNyVU/H/68V79UBWw
            U4pSdzTHya3sSBw/7QXMuS5j8OoAv1JAj+6lvVYRnBfYPZ2WD3ahoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQksrNEFyZXdDb3AvT3Fu
            d3NGT2JXbXJrYzFBcmhscURqQlpHdkhxY3pBCkE3V1lKZFNnVS9obW9La1JHMFlY
            NXAwbTBwRUcrTWxGSSt0OVhaQTlyV28KLS0tIEttSDVQeXRIRDZpZWVJYU9LZ21v
            WDhTZ3d5bW4vWjFwbGNOVGFuS0p3VmcKZ71r5rIZKIWpnDTl9EDYngLYQzUCVi/l
            7h1NUKWnTsLr0eqXgHLgRZvQYMstrY6ElqoioCLoc6G9pYOZ0ZfI8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU3lSK3dERjNwMUk0RUJG
            RTd0cVMzZFlaQk1PSWtaTHJSVW9aTkJ2ZVhNCjFLaGZMRDhpd3F5eEE3WkRwTjYy
            bHVOcFN2WU9HV0tlbFBoSFBKTmd5ZGMKLS0tIERYRzB1NFZ2SFdmRDBwa043cFV5
            RGU0RG9kdnZDTnZ4ZU8vakx4SG43ZGcKgmIx5L3dvAxMK6RSOSqcui57oLLJ0KOU
            5tMk4rU4au04dx0y1we6dU6ldhRAfPQA5njsa9BTOYDsu5ONjwuK9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU0pZeWcrWWk3NlJyeEMy
            aVpMVmpqUlBvRkQzOWFpTGxyRWRLNy91a2pnCnZSYW1WSlEyYmcvNTJNYW9KQi93
            TWthSXIwWHkrSVFwMUZRRDRIQkZoU28KLS0tIGh0WjRYaldqakc2MGN1RDlULzd4
            b2x3UjR4eVZqZXgzVWFOdjFVc3l2U00KC21RA8B8C9XZ4ClN2fYl8qChHt8JZXp4
            3xFPrI/2ckRv5setrASJHitTN7nR4S+zg2n1VoJttFhOZa+z0pAoYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQzVyUExaTEMwNUNCblBN
            MktWSE1MYmhqOHZJRXJaKzF5aHdJd3UwMGxvCkVsZURzY2ZWdWlUdVQyVTRERGdy
            N3BXZkladDdOendweFRId09JQzBvL0UKLS0tIEZWTmRPOEtpd2FVS1VydGR4UzlD
            YkllN1dCbXJzZlNIWEVXQUJtc2hkelEKU5ou/qh6GAw4QMwv00Kv5ovzaFCnGLe5
            icHAm0U/MDOIq31ltkkdn4b48gk3p9oPXuDctVzFZhGjMQaupgrOiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWUJZeUtlbUd3L0JDRjhw
            Z2s2NWQ4M1o2RzU2NTVSaVJ3TzlxZVgxZTFNCmFncW9QOGEvMHkrOTJYM0RFSGlm
            SmtwZTVCNEp0bHhqb1MxZC9qemJnRlkKLS0tIGRmWGZMcCtRanRaWkhmWU9ld3FZ
            b2FJVlNwVDMxTlU2UEVOTmp3NmowQ1kKI4WWNqn+ynrRpw59boDoiay2RVlCl/z3
            6R0KVfgyerKH6+dcGRniwHG1zhkjBGxB1u2A9rb3qSVvo58tXB8AHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwN0lLZDh1V2p6amZpTlo4
            MGlkNkhNc3Y4WjY0bGwyY29MWFk3eFBtdzM0CmJ4NUVqQlZtWUpzWE9saUJFaUVh
            eWVuY3I4TjRiYUxNckVnNnQ0aWxPcHMKLS0tIENJSHN4dUpyUE13Q3JOenUvRzFL
            OTBKM05nV0xUdTRac28wemRVUWVjVEEKdepsfSxaVFJL15bXiArnBeHyAcP/75Sw
            rl3//pvJA54M/QJ7U+8grmQbArM0Y54m41PWB+cGp9NQqXihaxhIOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:32:43Z"
    mac: ENC[AES256_GCM,data:oHRVVG7+6mbB9pT4SCoC4d4IVjWZBTt70jLzHUf0YCtLAZEUtrb1g0b+3Q6zqJxnMShY8+y7S2AnRxQGxrO5VPhtVz+JzLqTNd4GQ2uVHaIgHk9bbcz92u2WKLna63NBT5RX3Z0FTHWxVYegugGjsIhnVwF7QmrapJfl/sOcwHA=,iv:f3AQQGlwZFyKk49QQfON3TCs1NznnjEtW+n6cAoG2gg=,tag:n+2Vc4p9jMkgt4f+r7DmQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
