apiVersion: ENC[AES256_GCM,data:p2M=,iv:yV/4O3g44Rghn6rTuzjF+uOS6gzCd9aBAP27Mea1Tvg=,tag:w1/mjpNDG9jpDDG4JnQcEQ==,type:str]
data:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:7fU6RXwNYIuFoNmQKlaWVpdvWBD+ezuQGVyTfggoWtfqarxHouqecoNtCb4=,iv:SbY5Se0nRKbzbGQEZVJp7slwWaTB9DzIRWUG5n+sXvI=,tag:PU+zP5IwFi4lDauuf4eT/Q==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:QLF0Su6GnQyrBkhXt7UiZrL4+hUqwJ0NuNFTszMon178W6X8x6b9jqZoyTNAkaaSItJMV4Z232taB8GJ5jO0OZCPJV3MK7bqE2oRhBrKuClkJSLNCSPxMw==,iv:wQ7oWEoD/CP5BJPmN1oT78S7YsNH7eMPpEoGj/m/8PU=,tag:JI4CnkcSofeh/Yx1v61/kg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:114HMlGKrcP9WOswcv7S7tOBpstpNcXV1vwMxFsHNv0r5N4EpMLd4ZVrrQ6PZhPBxySd+a+bMalcDbnpuBA86StH63cmHxlMC8HpFb+X6FT+XhYpMA6xpg==,iv:kUrUOJ8is4WhSwPnQZLZGaWWVa1YqaU4BZvwxTpgz8M=,tag:O3ziMnInAiHVvCkgiqn00A==,type:str]
kind: ENC[AES256_GCM,data:lOm02YEk,iv:FWu+4JQ9zwgFdiHK+3fgVEArs7+57jcvfRNUsMVzxFA=,tag:Ix5bgpkG00UvNAYBO7RklQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SErDAnPOLBXENXt7Zg==,iv:M7liOnqUPgfXJT2dCD14Smjucwtx+UHIr3m2OFaS/RI=,tag:ck8O+6QHIyJHN22nLwCMcg==,type:str]
    namespace: ENC[AES256_GCM,data:v4SrjrzdaQ==,iv:m8ehQq9EjXtWsr2y6Mgs8Di92GJcxMlyFNmkGISwKBE=,tag:JFUwUAhgnrjxt7rM8XokqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRlVSaFNtUkFRa3k5em9H
            RGx1Qm82Y0VjSE1MZktNS0pFTGVjMFY0K0RNCnBFcGtFa3YxRGNyaHlJdCtmZmFK
            aWFoS1JkUW0venVoTzhMc1h2UnZqQzQKLS0tIG4vMGFWbHRBM1lqc1p2MUt1YWkx
            WWdBajNiMzdscldnVkNTUFRlZUtjY0UKfC9DW/7dC1vboxdvTfVYViWFxmGRYy+o
            Kavj8s3XbVJkdxEq03kNNpxPyNnJ9blf9eaSDtQDM3FxEbACvXouVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNnEzUTN6bEVTUkZtYTF0
            V3UrbWlLM3ovVFJPTGtCSE5jb1BBcDE5V1RrCjYzWHBqRSszQ2dnWU42QWFRN2dR
            WmhpR2VsdmZxbzBsdmJ1bHpwc2lQM0UKLS0tIHc5cklYQmZ4ZWZsRXdRaVI3Y0cw
            UFAzV05pUGE3TEdpRGtNTk1BOVE3TkEKeey33+GtCSmY+p/whM6mBnXHuQi6RccZ
            ZRAn6vfjgwdQNDiV2nS54hXUZhxnYwEimKk5GYf6ZDM/iFgcil3NGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaDFkWmNhUVdwN0YyTWdh
            MGthc3JnRjhiTmp0VDlHYnRGMXN3akFiSWxvCjRSaTNJVzZNeE9zYkIvREJ3akRl
            OVZVL2ZoNy9yaDIvQ0IzNERQOVJZNmcKLS0tIGdjUXljOVpRNkhGQnowUG9mQldj
            Mi91QzhhRVNaK05sTGc3ckFZV0o5cU0KwjuV0ZcQIEhZJe1WaPRGUdi+tjnbbnQS
            ghLMMnAwuoAmT+Fz1AyrPkPVR4mJOLl2rlm8J/u1zy7oO3Sa0qBzPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aWUyN2dwS0tOdU9YKzVY
            alVKT1dYdithUzA5aXdLcFZFUUpZWHdSQlZRClljdjdrMVZZaTV2dlI5cDMveDVI
            Q21HMXYyQUh4ZWt3aEdDQzNDWFo5dk0KLS0tIENkUmNtNjJ1bzlRd1hRa2Y4LzlW
            b29OYkM0VnAvT0J1U3kvdG41TnZ6U0kKVZmOzqVK+bplnDpVSv2HDndItnpvBQPj
            l0sEfPEUb9nJYkYHhZS6hNVUxq8175FvlisKDTTlPbz7Kk+MSr5O1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQU1zMEpTU0dCMmhrYmFE
            QkkrejZ1dVM0VnVNYm5sbHE5d2gwN2djTWlzClpiZmFLMk1OSUcrZ1o1Q0xjYy9u
            Y25BRDdUbkRCN3ZKNnA3YVBPQzh3VmsKLS0tIExYc0ZFV1UrNVVPOWtQRFlJWG5G
            R2V1V3BLdHJaMnNpUEZ4Vk90bXhxcDQKZQi2xIojPh0kuaLHlUa8PThgpa3m0EJH
            47zcRU9PXRgWA+YMUny4o0YDPaX7YC6EEoW9T8+oRrhft4gpRTbENg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaXd6VGtZdzVaSDlMejZv
            WnU3UzJYZXdMcDNGLzdwVUE2N3p2S0NjeEE4ClNpdXhqVDhxejdqdkt4M0svTmk5
            MlIwTVhIMXJvalI2R2g3ckRkSndKVEEKLS0tIFEzTUxPR2hUMHZnYTBaNi9sdmZy
            a0w4U1BicVB2SERzOVo5dWpOaEhveFUKjZsJXODj7hyiDX6SyS9U0ZqfS3NBC7pM
            lqVF9tKtObsY8B2YFiS9hcN3Qrxpjbkb2ow49SwX46FvZEWAkXnYgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNHR5c0EwYndkRlBvTFZx
            ekRnRGFtc0kyQXVYTGQ4dk1wL0JFM0ZrNHp3CmhjQk5jZ3ZrK1gvK2tPTks4VEds
            MmN4RzBUNytrOGxhUlNhRkMrblZxdHMKLS0tIGFOWGtySVF6dW9WMmlHUWhvdjBN
            WlJrWFQ0YzEvZVNMVU5nNWZmM3Z3ZTAKeA5xL3ULObtxEq0WM8r6Zdgny+H8sLgL
            /muGZVKJKyzZ8+Y8rcm1leq3XETJCS/rp545hC04KuAY3ZMC9oULTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYlNyQ2dSbUlKTDRsRlFp
            ZGdVQzNEZlQ4Y2JJV3hDQU95Q2FrVGFOSXdZCndHN2ROakRlMlN0bTRNRVd3bnRl
            a2Fvck1rcUN3UEx5MWJPR2FLMXU3ZXcKLS0tIDFMNzhWSlZ6NkVIaC9hdnVkMkI1
            bS9MRU1HckVJM3JZdDdNY28zRlRwRUUKjmiYuotwLLm8qs3AnmBil7sUs3WGEYu3
            bSStafjcUjkO7AcQ5qR4o3J6NpV3Yzd7SSk5LXkNdnFmHajBRjQd2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySUdYV3d3M0dJOEc3emov
            SzU0WmhFSW45cEJoNk1ZUjhYUGxIYjRRZTI4CjZndFY0eEZUTnNoSGJYcmF5RmZV
            K2Z3Qk02a2NuZ1lvbU5VL3V5Y0F0ME0KLS0tIHpYUE91em1WVE1nMWJ5ZkVBTjhH
            N2srVEN1OFh3a2Z4UncxV3BVSUd1STgK6NH1hRZH9gS3w5Y4Qp0b4fB4cYKvZPLG
            sQgJoKr9QAmPzsb1Ah6zfa7nw3xosE7HWI5Cn/qwQUJUz43VdQlbsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjM0srZ01KQTBubFdBOHM0
            V1ljTjdUNFN4NkthY1VKanNWRmtzU3NEWGl3Clo4NlY0dCtpMjFCVUxPVjVSRVpy
            YzN0VVFSa3pOc2kxMnB1QTRJRjUvdWsKLS0tIHVKN2FOeHpXUVNxK0p2Njd4QVE5
            NHVrNGRZMWdrdGdyWTdSZ096bTRVbHcK2tqMQsf6ULHsb70cAf/+kiS8xDn9PsCJ
            k5oUUWgAt3JSKrx6xR3t3+Hqgb+2oiLzisaWtDt0i1L4dVX1d2XYsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMGw5UVVWZzdtY1dSMkRo
            c1lpd21oN0dJT1VWbFJEaWEybEp4MjZLcFdVCkxmR2p1QnZjOUFja3ZFU0ZhQ3Q1
            aVhSUzBHenM5RVhOcDZxNTlkV3Z3MU0KLS0tIHpObkN3eFFVMHp1ek1ocFNESEky
            cDBnc01yTUNmVWlxREtEaTBZN3ZNSkEKUh5/vLAxANSCc0P6P66Pf/Q8y7urswBi
            HiHz8l5xMCf+po0XPTRguPadYV/KM4hj1al6n8HTMu97kH2lhLZHfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR3NwU2dFWFBZeWJIdFF3
            a2laZUdzQXYxVnNMZ1oxM2hqazRqeU4rcUJrCllNY05UajExZXh6U1c2d2pKRUxF
            c1duUWVJNUF1UmIvdng0UXNuV2o0RUUKLS0tIDJGSXhMWUd4cG4xOTNjM1hlYXdB
            YlJwQ3JpMXdmaFQ1VkU0KzJOVHNXbE0K2c6dimZN6yNAG/DtWJp6Lix8FsC5QZTQ
            QC5embAlunVC63i1OwE4t5VWJ5ufSDfO96KejP+vhUuAiyh2obzs/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:nFVEWUTj3PqbEpTmeF5kU8kL5+Y2BxwIXzH4IopHgFwl6kMt+0WIRzNwuJ3ronmQUhJyyZOpcmet6MdDI3ybtjFcqQp2KUB8FaInbt94SLR45CgeG/Wen/CQbis8YOFQNpzBEZMHkoCWxM260cHD47XNaAJDJlQPX5gbVcUIFsU=,iv:ei+NNap//JljamcvU+jT7H7vjbzh68QF+v8iJDQLJyU=,tag:NL2GLN1Yzl8rvX6k5Itulw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
