apiVersion: ENC[AES256_GCM,data:p2M=,iv:yV/4O3g44Rghn6rTuzjF+uOS6gzCd9aBAP27Mea1Tvg=,tag:w1/mjpNDG9jpDDG4JnQcEQ==,type:str]
data:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:7fU6RXwNYIuFoNmQKlaWVpdvWBD+ezuQGVyTfggoWtfqarxHouqecoNtCb4=,iv:SbY5Se0nRKbzbGQEZVJp7slwWaTB9DzIRWUG5n+sXvI=,tag:PU+zP5IwFi4lDauuf4eT/Q==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:QLF0Su6GnQyrBkhXt7UiZrL4+hUqwJ0NuNFTszMon178W6X8x6b9jqZoyTNAkaaSItJMV4Z232taB8GJ5jO0OZCPJV3MK7bqE2oRhBrKuClkJSLNCSPxMw==,iv:wQ7oWEoD/CP5BJPmN1oT78S7YsNH7eMPpEoGj/m/8PU=,tag:JI4CnkcSofeh/Yx1v61/kg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:114HMlGKrcP9WOswcv7S7tOBpstpNcXV1vwMxFsHNv0r5N4EpMLd4ZVrrQ6PZhPBxySd+a+bMalcDbnpuBA86StH63cmHxlMC8HpFb+X6FT+XhYpMA6xpg==,iv:kUrUOJ8is4WhSwPnQZLZGaWWVa1YqaU4BZvwxTpgz8M=,tag:O3ziMnInAiHVvCkgiqn00A==,type:str]
kind: ENC[AES256_GCM,data:lOm02YEk,iv:FWu+4JQ9zwgFdiHK+3fgVEArs7+57jcvfRNUsMVzxFA=,tag:Ix5bgpkG00UvNAYBO7RklQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SErDAnPOLBXENXt7Zg==,iv:M7liOnqUPgfXJT2dCD14Smjucwtx+UHIr3m2OFaS/RI=,tag:ck8O+6QHIyJHN22nLwCMcg==,type:str]
    namespace: ENC[AES256_GCM,data:v4SrjrzdaQ==,iv:m8ehQq9EjXtWsr2y6Mgs8Di92GJcxMlyFNmkGISwKBE=,tag:JFUwUAhgnrjxt7rM8XokqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZG1hbzBYeGZONENRaGI3
            L0FEQlBwTFRPdFNTYkdrb2VYcjZnMkg2WWdRCm12bEZ5eThoVzhTam4rNnRWL1F5
            bkNNV1ZMZ3VBS29hYVdsdktmSVRhUFEKLS0tIHVXQjhqMm9SdEIwN1V1VnI2SVRn
            TlM5MmtzRWpqd1phMThRc2RNTU84cmsKM1Em74r/N3l40Oc2Es3fG5XLAcA0QT4w
            FD3BB1uPslK1R+uva/ld3TIbtqdOJvJA5GlyLcq8Xk6hz3GtveWMnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZm5VMkJpRkJZcGZLZ1hy
            azJ3dHdEWlVrR0R6ZXpRMVpVTitMMHhYZjM4CkNBZ1l1Um56L1hNb2NRd1JRS3Js
            QTVYS3dmbTFkL2NOUXB4c0J6L2pUQWMKLS0tIEttTmlyamFUbUsrd1RicGN0K1px
            NXFJWG5URVYyQnZtN291VVZrVXBlRUEKb8Flm3fjroVCTXF3L2+cU8VGzjbW5riA
            +uc61OAvUVkdabrD/VAN5k+VdQtOhb17Dd3pPNAbHMwS4ckqHGwoSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONWZjaDZ4T3UxWUxibUl2
            M1lKVlVlRGpxOWwvT3EvMFZVdFZhaTBHRVNVClFzU21EMWhzV1BhenUyajhqY1pv
            YStWeHd6VFY4Q2kzeGE1NjBwbytQaVEKLS0tIEUzVjlxdXVaeUxSWVo2T3I0T1ln
            cXFpaHdzVHBTK1JiN3R4OG83SjNCeUkKpX2mbxTC7xGK+lusQG3pnLea00MAiQ1c
            ywCsyoTgCPf5o0JEf08KeQ1ONQfh6KFmEv9E7hF71W/WklIrha3eDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQnBYNE95NU1BZUdyUmwr
            NU12QzluS1E0ZTcrUGlhMUFPaDliSittU1c4CkFnNWpYSHUrRHhTaXZYeGF1MzI3
            ZXJVckg3MEtQYlo5L1krNkRMK2NoVWcKLS0tIFFBYzlOK2RjNEJLeUFMd09BV2dI
            R2hlN2J5UXpONVhLYXJhMVgwNHJQemsK++fipbNeDv1IZP0L7KKsQnGBqPuC7Efm
            PX4Jef7eVFszQmrQO1rGjc+UuelK69G4EIvB2iOMUyu/Kh/y+jWcYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WUh2dHBVTDNzZ3pNeFFl
            eWpZNGYybi9HblBySHNsUEs1UmdxaURGT1FFCm1RdCtwSnNTc0ZwSkJJdHI5eUZa
            VlUwWHEreXdESVQvRWNFZ1o3M2hQckkKLS0tIHV3aXJVVXdmdjg5Tkw5dU9wZU9D
            bkJCR1FYYnU1RUhFbTZFelNaTitkYTQK4H9A0yek3PWt0HVLqYmT7erSdrgwJEpf
            U5HhT/sdIByjdVbBPMzGKsfUKMNBSZNvGE/BgVooOR8yGikykD9nbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUzJ4QzUrV1BJakx1OGxU
            VUxCby9XdWRWZEhha2FjSVNJajBnci9WeDBNCnByS0tqS3BXOXRWMGpOZjFubmhP
            aXRFM011STlSclZYYW11N0hxZC9XcmMKLS0tIDdhaUhybnhtS1ZJRnhlSVlWM2g5
            d25VdGRLQWh4U0NDb2N5WlVyRG9TVzgKARlQJY6ocPZF6ch4da8F7f9c9mab3ML8
            lBW59LdwEXOS4AaO8FIf3ahEq4P2HiGZg+T/majmKXAYDK3IzQSSHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTU4wYjcvSXd4MFJITFpJ
            cGc4TW9EY3JKOG1tOXJmUUlRU1NONU00TUVBClNnY2hmZ2VQYXdwZm5JSTM2dEZv
            elNLQVRiUXlJdXJCb05pYzBrb0VCbUEKLS0tIFNjSEhPdWk1OTJldFJvS25rWVd1
            UmFzcVB5MUppdjhTWnFBY3FhV0N0aTQKTYo3g9AjCOGi7bvKtBNEIylFUfPVMBfV
            nwkOUn4/lGDT+l2yMTwBrTHc2Vi59wgddJ4PUi2LC0NSx6URHXxS+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUS9OMG5FejAzbkczOXlp
            eVI1djdEWjJQZHlzVzhkWXRJRGlwandQeGpnCkFqVEFKTVQwWThlK2VRVm1GbnFn
            a2ZhQmNRMDFaeU42VnhDdVpCMVZkenMKLS0tIFZHZ3hyUEZCRDVSY09MbDBUNmtY
            eDhiOFJqRFphVlZDRFQwb0xLbmZXMHMKVUxDjSBbL/h3774JH4Ktqdog+XdcVtSO
            ydtpa0lie4o6vLPA8I6gtrPHlC1Jn5Mhf+yT44olxBYU3LXyJzyPRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK1ZZNS83MkwrSGRSc3Zn
            SVpqRGVsTW5nNXhjRTVrYlNMc01oS1dXeENNCkxnSWVRWnRUeHV1dHpoSTdsOC9v
            dVRIWXRoa3Y1MlhDQk1RZVllK1I5d28KLS0tIEhiMDRNMjI2YXl4aEpKblBwNktB
            NGZOY2F5RUhkZExWL1hXbHU3SS9QaDQKhcQ4R8Rb9/A1c5vDPgB1HgrAUklwXFhI
            F3R0098DakK0pWVxtuvckkjazzp3LziLNLZfME5DJQXMxq+Ix3aQ2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTHd5K2NXVld3NkhYMHpo
            K0tvL2lzV1EzTEVhTnRLTEdUbnZ2SGt2YkVnCjBnZklGWXQ3elQ2cVNYdlFRdm90
            d21XNVpkSmpWajJWL1V1NXFKQ0RkSDgKLS0tIEpCZHZLT0ZSczBCWWZ6ZDlWcGpI
            c09VSGNVZTdoYVc3dU1QdE5QS0hUWkEKrNklI3HCkiTIbfl840yW4X3r6yHcoEyJ
            iuQ5CZi9dIT/18R4tEkIyZWQzq9QFztd86Sl7kWDwyYDGZM9PB5CfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bnZaVGUzclFOZGxUbmF1
            TWloZm8rK1J4M1JpTUM3NjdmVmkvck9mRUZjCnJSRGRjTm94YlBvbmNSSXZlNEUv
            Z2RTZkt4UTU5SHFBOXpMbTJNeXptVTgKLS0tIGJtbUlDWEx4amt5YU5WRXRGVkxv
            MllDWXE4THJUL1l2dzViMW1VeGJnSEkKosnWlkh70BTWqS/03BfZsKiLnK3MlxLO
            XO8k1JNDm7iT8i/ltA9Ojlxpy2vcF3lRg7FHQIpUo+G6+Hqe0bTsYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcmFOVFRkZ1pHT29aMVYw
            Ty9PTHJMYTIwQXZrUGhjOWdhVUg3VENsbW5VCjdEZjZuSW80RG02MzVaeldLYWlI
            cGphanFQRStZb21jWmF4UmhNL1ErdVUKLS0tIGJpZU1DaklYeHFJN0JpcGYwd2J1
            b3VvMCticXpCcGl0WlZpeWhxZGp3bFEKjy9dBNSbOrzCXxIzXtFV4laJYHL5cV+1
            XyEpFB6QkaLKbkeWiqs0a9lcdUFN7p5g9FlGyv6YggKpLF1l8UwEtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWjl2NnJFTWJpdGUxVUJY
            elptSlZGd1BYYmkvSXJlU1Nwd1ROb2F0KzNFCk5aSFkwR0RlNkM5d3dMa1pEUVpV
            VHhraG9OUGxSMnNkZC8vUXJUR2ZieWsKLS0tIDFxK0V4UHFZZlFHQ0gvNjU5MzdE
            dTBaeWhLbWR0YzdMOXNSVnJWS2hHQ2MKW3uiqwGGbf0WRIIwtVDNnNu5W5S4NMSB
            qlnwZo1q+L3BRBJOJCUFGYeTQR36z+4hVxfhlO4rk56D9XNHbDiP+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaVRIMFVPTVkzVDZ3VHJ2
            QWU5elc1Rkt2L3NRNzBGQXUvQlovY0hVZkZzCjA4TEZkK0M5WjgzQ0ZQQjFqYlRS
            NTRjc2ladUhEUnlUUnA2RmxFSUR2aDQKLS0tIDdjcG1za2RXbkNtQ1pjK3I4TEtq
            Ui9FRUpBSk54WUxtTDJuSllxMzIzVXMKeAe6ANQyKmC3U4bgvpL8RCzT1hOrW4i8
            aXW3mlmB5ouURCot0PXkEApQfSotxTHW+2fuDBqx5tpVI8GYoJbzWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:nFVEWUTj3PqbEpTmeF5kU8kL5+Y2BxwIXzH4IopHgFwl6kMt+0WIRzNwuJ3ronmQUhJyyZOpcmet6MdDI3ybtjFcqQp2KUB8FaInbt94SLR45CgeG/Wen/CQbis8YOFQNpzBEZMHkoCWxM260cHD47XNaAJDJlQPX5gbVcUIFsU=,iv:ei+NNap//JljamcvU+jT7H7vjbzh68QF+v8iJDQLJyU=,tag:NL2GLN1Yzl8rvX6k5Itulw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
