apiVersion: ENC[AES256_GCM,data:p2M=,iv:yV/4O3g44Rghn6rTuzjF+uOS6gzCd9aBAP27Mea1Tvg=,tag:w1/mjpNDG9jpDDG4JnQcEQ==,type:str]
data:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:7fU6RXwNYIuFoNmQKlaWVpdvWBD+ezuQGVyTfggoWtfqarxHouqecoNtCb4=,iv:SbY5Se0nRKbzbGQEZVJp7slwWaTB9DzIRWUG5n+sXvI=,tag:PU+zP5IwFi4lDauuf4eT/Q==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:QLF0Su6GnQyrBkhXt7UiZrL4+hUqwJ0NuNFTszMon178W6X8x6b9jqZoyTNAkaaSItJMV4Z232taB8GJ5jO0OZCPJV3MK7bqE2oRhBrKuClkJSLNCSPxMw==,iv:wQ7oWEoD/CP5BJPmN1oT78S7YsNH7eMPpEoGj/m/8PU=,tag:JI4CnkcSofeh/Yx1v61/kg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:114HMlGKrcP9WOswcv7S7tOBpstpNcXV1vwMxFsHNv0r5N4EpMLd4ZVrrQ6PZhPBxySd+a+bMalcDbnpuBA86StH63cmHxlMC8HpFb+X6FT+XhYpMA6xpg==,iv:kUrUOJ8is4WhSwPnQZLZGaWWVa1YqaU4BZvwxTpgz8M=,tag:O3ziMnInAiHVvCkgiqn00A==,type:str]
kind: ENC[AES256_GCM,data:lOm02YEk,iv:FWu+4JQ9zwgFdiHK+3fgVEArs7+57jcvfRNUsMVzxFA=,tag:Ix5bgpkG00UvNAYBO7RklQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SErDAnPOLBXENXt7Zg==,iv:M7liOnqUPgfXJT2dCD14Smjucwtx+UHIr3m2OFaS/RI=,tag:ck8O+6QHIyJHN22nLwCMcg==,type:str]
    namespace: ENC[AES256_GCM,data:v4SrjrzdaQ==,iv:m8ehQq9EjXtWsr2y6Mgs8Di92GJcxMlyFNmkGISwKBE=,tag:JFUwUAhgnrjxt7rM8XokqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVWZYK2RENnVhNGh1aDNQ
            dkZwZ2NVcERIenlUaVRGYWVUM3pUMzNrMG1RCmlGQk4rUkc4dUcvOUpCS3l6WVQ5
            Y096ZCtlVzU2eG1QQ2pSUkdmMVNxQlUKLS0tIDFnY3EwRDhGa0R6QUZqKzY0eHhn
            TTBPZjJvQVQvRFdLcWlnT0wvWi90UzAKTV+aNE4mEJKYem/GI7/UXVqS9ajUN0Tg
            dmJYtIvbk+lk781Ylzf4bn+7AfOCaSoCfSFLgLuW8trL0nuLcAo/Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdkpuR2dIT3RjRHN5YkxZ
            aUwxTjRWSXpQVGpUTXd0SnJxWFcxUllUc1NFCnd6NnMvb1FXTHB3VnJnL0R3UzJu
            MXkyNnNSaFE3eDAweHpBQnNLdmFPQ1UKLS0tIDF6ek9FdXVCU1J0RXA5UURwa1du
            T2Y3MEpoTFl2Nm9kb0NDazdueEtYNUUKSyraLzCVzuhwcq1xLsSIFPaG5tDbwMUp
            N9/bStPYAQNXgrzfZRiqhwJwGWk1XrDPyZPTGK66xsGZb3pGhEydDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpcg5t420nf72k0c9rrx7amg0szch98uzqu273exj7lw3yu0j99q6vcckn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYzJzUFVLcU0zSFNSTVhN
            QW5YdjJQWWFvaVI0MVh6NUR1NVpVZ256Zm1BCnhpTDNsb2JBa1QrUHQyVU55eTlw
            NGtacnhpRERyUG9RUzF2RldZUUJNdncKLS0tIElNd1YrSnNxYjcybjNOQ3dyRkkx
            emhUalBUc1N4bUI2SG8zWFo4ZFFWQW8K7S2tfbtcDsMBVG99V+/uQ+ZMLqEVnvV0
            EZlGsDUr7C/l/lFxPLeDVWifcssAfXIU/zQX5T57RQ8AYL7SCBs/zQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4mzwe89aqgs56mn8zg7dd2l623kwmw80k90wr2sa6dnlcdmhcnsp4kt54
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNkUzSDRNd0hPOUdPczZD
            SzYybkgxUUVKajZqQzNqek9FMzZhMkNITDBNCmY2cXM1bVFYT0w3endYeU1aZVli
            bUtSYzFDRU1nYWNFZ0doS2FQQWN0bTQKLS0tIGlBZ3huZUpiZjdta2Jsa2Ixc3FF
            S3FvRVQ5a0l0dTJHL25kSW52c1YwNmMKR6fX9fB0bb41Hv+1UB9l2pmktFFFNqOW
            tymiDylGfJShGf9ZFeOZBTlLAUJNEiIeP4kVJLE8/Cb/HLKlyuj4eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMmVoRVJWU0UvQXcydERR
            emNHTEtLem9xTHZadWJLKytLWXlBNU41enpNClAyNXNHQzdDYUl0MlVFaFI2N0U2
            L1A2ejBNeDNkSk5EcCtvRVVYMmQ5aDQKLS0tIGJLVnYvaGFjeTNCUE5MV3BoZExs
            UlI2dkgvSVJVS1dNNmlUMkdMaDdXY0kKdb2r//5kLvwCzxFSBosG2ioyHs6cd+Y/
            48lVDcpJRTrey0PWUIujwWimUq4NTC0abhxt+VDkp8IymMAqEFhnSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUVZPc1FzZUZPQkxldFRN
            Q0swcXNWZVpFaUlMeWI0dlgzTFJCdkdFdlcwCm54SHFDOHY4UlBnRFhUKzJkcEVT
            cjQxaE5QMlVNVnhwUGZySDdIQnAzZ0kKLS0tIGtwWkZ3aUR1Q3k1M1pueFlTT2JE
            RnB5UklYWHUwM3g1S00zeGJYQ1lQWEUK5fp1PnZa9A+qr1AIMJ8Rk7XRgTk8pMHB
            QexKHD4hQ3u4LoHmycvKhwffSx6AlWzrAtPnN+Zr03GupWcFdzakbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNFFmMnEyWkw1cDRRRVRP
            SGpoa1N3OTU0bDNkVGFNeXhISEZreGpzTWxnCnlrYk1qZTk5SXRPRlQ1dGFld0JP
            NHdmdE9EOE9jM2xNLzZ6SnFDbWZFM3MKLS0tIEtjWTY3SFNSRktGLzVQbnU3ck5Z
            UU9wSXU3ODBpNXliQnB4M2pvcUl2TEkKBhwch5U49RDbL30kMpJ3ZoPGvGIFwQjr
            ecblFDelAGlr4fmuuwbIlPVlVVarxcutMiK+NQMHzpvD8Q9azRpKKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWm4xamI4TTFHeTE5ekg3
            U09PTzltM1hXSnNYT3dYODBzb0xVQWVIbm1jCkEzRElYdmsxaE5VZEpXOGZ2L3lz
            V0lPdzRjRGtSZjd6UXc2WWxIRmordEEKLS0tIG1sWmplVzFJVTdDeHhzT05FUnMw
            NlIzaGgxL1M2RGo1MGZhOG96TUlqeG8Kj04r3Q1BxMLmDNi4KDGUQK4FjbOGoD6p
            wHu9ZNQPMzMIpxzI+eCsvlxJHtzCMyseI9YItbmcYazNX9E93dtuqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpcyeqjcl8j0dd4sj6f0vufs2vpus3xn4dvxe3cr8g8rgcm0nfxq03ds4y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTm5OMFowb084dUlQbHJI
            VFhrR25SK2xHdHNFNXl0dDRDdXQ5OXlTL1ZjCkVNZkdxQmhTY2RTUVI0bmxkdTky
            MEVlUkRmVjhZVDF6aDhRZ2I4Q2JJamcKLS0tIFpERjVCTlpYYWpUUnJ4WjArNTd5
            d3EyYm83THJKTmlxWUJnYjRIWU9YWUkKIM0eP+xBAhJL0KsRYgHBzS1fFYELy9K8
            dS8q4/X0SJk4QjI42qZlCcpPcUwKRxZhIdpwiDr8mBRNx7NUNu94TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NjVlWDhtZGU5amczSFlY
            bTQ1ZzFUR2Q5ODV6UldLS3N6THNkdlBJcGtJClpweTkzV05nNDRFQTdjRWlZM1JG
            cGQ5YXVja2RFL2lrSllrYmhtRXMrWVEKLS0tIHdsWmpnT3VEdzNxblZkZmFUN2dY
            NitwZGNSUEV0TFhuTXByWEdGNVN3ZVkK+pMs7ubs+ZM0UZ24wIbt4/DhP6YQq8pM
            k3R+4KrDt7aa8mRLmzsXeH81+sQN7k8CP+2UQsZAUkrGJE297zflXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd09QbVcwVGxxVFUxWFJ3
            czZLSHNBWXE1OW9lU3NMWkd4TDRmMEFjTTB3CkcyMW1xckVER0o4VzlFVFdXNDV2
            WmRCc3cyLzRqOUJnYkcwVFhvQ2Q3bFEKLS0tIEFDdTZnNm9OYWh6M2VJc2taNUV4
            czVHV1R5cUZ5dVlKbVBGOHZveHByQ00K9Mj93JLKakvrHP1gWiplUOV/SBxm5Oy5
            u8ORixBBaoE+SDX4iqa2Jq4GLMMGEHNWxlpFFPYSTH1YO2g9EkL6Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mhrzghrmprq387xqsln6996yx3ja2e2zpamh9mtuu9zqmxahunqg9qugw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYTBjU2lUdWRWQVVFN3FW
            NExIb0xNSnN6M2JXWjJKRnFzeDFiNW9ieUZJCjlaYVdWY2Ixb01WNW9yNlN4MzNN
            d2Y5Q083OUZQNHNXU3ZjT0xHYmdsTFEKLS0tIDNOUkVaa3dmZzkzUHBWQStBR3pL
            TW4rcE14aEY3S3BSNFFsWG5oQ1lNNGcKjVzGnlkQxOAIU5vs7cQ+sYJKvMkN8Or/
            HJWmFhu1E9VTt4auU1ocxqqN8X66wbPi/16eLe459iYLILD7ckfysQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLa3VQOTNNd2pXLzd6NVc3
            dmEzMTI1ZWdMOEJGTzJHTXdTUkJiekdWMVRrCmlwaVFQdU96TXg3clYvYjlGS0JJ
            UHFYemttU2JaM3dQWjlJWTVkdk9uN3cKLS0tIFhKc045MTc0NjZsWEoyd29TalQ2
            UnlpZDVkWHlrb0M1SFlMVFpvUEdnRjQKeJLUTZ2Wcrsy1YW6NBVMtg1fzguTpXDl
            O3FeGzmcudHsFQRssTJLEsW32Z6BqubOhXuv7ehAb6mI9LBB2m52/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVUNFRUtDQTNuYjYvNWpK
            ZW9qaTczWWdlRHAydElOeDVDOGtlUGpaQ3dBCkg2NnRqSEFXSVdGNllnODhPQ1FE
            WFJucVYveFFYSEpXR1BReDFrbE9vMTAKLS0tIFl5UHVKY2RGTjk3Tm41WTMxQ0Rm
            QlIvRFdydEtwR1ZYY1VzRmpmUnh1TEUKNO2EhaLoiL3EzSS4SQ0ll//JO0lode31
            IXcV7xa2jjxY9xF2+nIkeK65VGneTCHUN1NhhmMguFqGW1i/HcppBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f9hd8fu0694rc3tr6hwxz3ldfpepref937rmvqdxvvsr0kfcjdxswyzvw3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbFFHWWxMUXNnMXlteHVW
            aFIwS252WFJHSXQ3RmhGZXd1NStZd1JiSVFrCkVKTnBJR3UyQk43VnVLY3psd0Fq
            dnZra3hxY0c0cVFKUncvZjdkK0NkZTgKLS0tIEYzTTkwUGM2MXM3azlISTVSYWQ3
            V0JSczA4NjJkSGc3cm41c0ZrS2ZlYTgKnB8vCEsFaGJaRdTlr3xLar/CtVjcKVgX
            eX5+mgHjEKF/dwzeya96LUAdisO0PzG/msqZKrYvd3EYtpX6ILY1Kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMFE3SDZ1WjdmVy9rSGxv
            ZmFFU1ZkN0xNcG1xckhFMGVHMkl2MjVIWlJRCnN5VGR1WnlXNzhUdlRIZEpycWhX
            MmxPb1BiOFZCZ2hpTHdXenFoUkRDdmMKLS0tIGxpQml2c0R6SUFxQXk0NGZTZmNz
            QUhYQ0V2M1JaT201ZUR6MVBIdm1pSmcKF4Ez2nCuCHtta7Ef71OABBLRNgG8QKV0
            pRKjygW9Qa5aqaWlmzQhsyFWOikxQCEgBAZDxtwWZViU6pacLbsb6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTXZOUnluaWRndjQxVkpq
            NUUxVVJweU1FNE5QRWtxTkhEaEdGelZnVlNRCjVjZDRDcGh2Ni9WbDVYWGUxam9T
            TFNjeEtOZlJPdFBGTngwazhMNjBkM2cKLS0tIGdranpCQStBMlZldnVQZ01BL2tp
            S0JSODFKQWhTclNSMVB0RHVSZXpqSncK11Xi1WM8edhjI1rxI0k/YrLqrjJpyVX+
            Zdkhrgh1PAS7uwk7JblIytmmCQ4MVJeHKjrppY3f8mJOaI1ON0Jd0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpclRuM2RNR25sUDI3L1pi
            Ky96cFdoQjRNR1htMitxQ0UzQmhYT0ZNQlNrCitKUWw1WFgzd2l4TXJDOWtTdTNR
            V0RJOUxud3NmQllVR29oOWcvVzZLZkEKLS0tIHpYL3VoK2NrMjY4V3lUYVk5K3JT
            L05UL0FWWUxQRzZ5ZC94VWFNc2dhTW8KqJ8rIwtguK6EZsTlOsaXe0Js7H0Zt16+
            gpn1ahcAiLYozrKFjE4n8xHVv2W5JuQqA1y2/tPNdxAPwxSsEpw3EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdDgyWTFmdXN2S2lQL25v
            aHFVZjBoOXhDNDFFTzQzMFZqWEFLTjQ1OERVCkFRYkFHcjJXVWtiaklyTElxUXlY
            YmRzNXMvVVVXZ1dJVjl4WTdVa01JZFEKLS0tIEMxR1Y4R0hwY1duVXRkTWhHTWFI
            NlRKU2o3MFhVWW1xOTdnRnU4RVUyV0kKC970p8v6zg2joK3w/eMp9dBbkxMC9hOx
            p/VizMlaRxMD4sRMqtF8RruzI7bjsFbEUOR8r2zq1r/bNraSjVwg6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sukfru07msq8fm5ddgym23yal9lfm99090p999p09mxgrrwh9aqs6zp4fy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVDFzU0RIcTdydnlsazE0
            RDFOMkRkWHF1WjVYRDNVeXlod3UySmZ4Z3dnCmtyVTdYR3dOSzlRQlZDYXBkMFcy
            eXRSdHUxMGthSHhCUWhFYWJSOUZRcEkKLS0tIHlBWnVhN2YzekdqOXU4cmNlcVBD
            RjdMYjVOaG8xWjlrc3RsVCtvdVVmbDQKHlWAYTMieJ9oEvKGvyasYfQo2ijXI6Vi
            hHUtuWaCjEbJm2IIqmBVoNwy3V3iQYaO5sTOs67/a/aZoEPzuZrIEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ephzrpgftmvq4cul9766q2r3mss38xu6un74ryfmw0729afysghsh0a3qg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYkdVZm9MZXMyeVlLcTNl
            c1d5ZUhtci9SNHE2SnIwbEhvZGhEcThUOGtJCm42aDljc1YvOXZaazRWTWdYYTYz
            bGVoWDQrZytvbVFmY0xQUm1GWEZTMUUKLS0tIFZkSnJhemNEdk1GZTFwK1oreWJH
            L3lMeHVHQ1ZTNlZlaElveXN0aG4yckUKh61bWbZshO0a7lIEGdF3QYqtJR458RvQ
            V6orjdNj4vaMAQAvlfkGMBVdmmPafXHTPgGtckitmYvG7nvPkdlEag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUThDMGNzQ3NvTVhTaFVX
            QTQ0VHZNM09FaGhQZXNIdSs1MG5oeFlObzAwCkVoaC9lQ2hINFVydktQUDhRWUIv
            ZS9meGFKbEtxMzZjR3ZBTkVhRkNTM0UKLS0tIEc5RkoydGVEcWpWMGpzeWVmS2R1
            bDAzVzY0b252NFdnT3hWa0ROOW14K1kKMLtgJ2ydxqPofKYNooTqwgS9BipkqGHM
            sINh6HktxlF+mXg64dqK7O9LsPMSBUrg5HVjNvk8gIihTceNv/A7ZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7ecrfntus8rvyprzhffjpqk2tmrc259knf9xqajlrqvewfp8d6svwp9pp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSUxxMVN5L3N6dlVRWTdL
            RWJQcnlUSkg0cy85bUYvOTlxZzhKZlpLeGh3Ck5MRWRNeW9KbWhOc3dDVEZLVWxC
            NzdHOVRIZlZRR3puQlNmN2ZHZ1NkdncKLS0tIHVuMmR5K3h1cTZMY0RpbHRxdjBn
            eFA5MFExTzl1R2JWWGZKdE5EeDJJQjgKgo6ifbxjcKiYz7tIgMPDbmj4xANju9ti
            cyL04NXbbvuKC6lJKNObE14P4mRGreTkYzlwKkv6i1XlX2KF134z9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:nFVEWUTj3PqbEpTmeF5kU8kL5+Y2BxwIXzH4IopHgFwl6kMt+0WIRzNwuJ3ronmQUhJyyZOpcmet6MdDI3ybtjFcqQp2KUB8FaInbt94SLR45CgeG/Wen/CQbis8YOFQNpzBEZMHkoCWxM260cHD47XNaAJDJlQPX5gbVcUIFsU=,iv:ei+NNap//JljamcvU+jT7H7vjbzh68QF+v8iJDQLJyU=,tag:NL2GLN1Yzl8rvX6k5Itulw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
