apiVersion: ENC[AES256_GCM,data:K0U=,iv:sw9KbFAMvPZSPN0Lqzp9YYFTBXBGBlEyOciLyczrcPg=,tag:vBzIYZYPnyuS3vn37/g74w==,type:str]
data:
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:STRjBHv5UTDCPzhmbyc7Y1fiFRDYQXok8xL0m4YfCYLuWXWjMhVaXkkctvaNBiKPEIvG/rX7ZPoJqxaysnqbti58pvFFMrIOr6TPIJMH+eaaBHqplltYlD8+9gqsGTxmcs/+4VxHzUCMSuCAX2gTy41dVE0D2lMFeCW5pA==,iv:qqohhgx7fv//gfJnmjjmiw+NBovwvland9Nw6ToRC1I=,tag:DUnEnrQYa/4THEhnzoX6uA==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:tfWbCD212rQcejJEDiF5nCZARHEpJSm9ziPppz24rzD6XUOH/af6Bo+J8sbDOFrE69oKv2dBXnI=,iv:qctsb1RhOcpcYtyCrGyLP/TEftRAc4qGkw+A9piD+VE=,tag:NOu9tpDYGnIAyRUwW+J0BA==,type:str]
kind: ENC[AES256_GCM,data:sLcRw3wb,iv:nv6eTe4nu+Y69c9Nt5vDfmz8T+WwrLJAoFA9URgUWtg=,tag:+QEvDf74W55rjZ069O03Tg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ltkeZVjl+y3BFC8gAA==,iv:rGiCSh7dP0uGUBWuZmPgZTCG0s/VB9Q03p1MVUMplw8=,tag:7n4rD35pb/XUFICKwUs1sw==,type:str]
    namespace: ENC[AES256_GCM,data:mK1RVxQ5VQ==,iv:0nAFwgHDQayPgnnH13ol9TGDzgvTwv3KoOLxHmniZts=,tag:zlKTIOXOqaq0ggl0sgdqUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaGlYSVFWTUJGR2MrejR2
            N1hsNkVXSUVpK2gzN2RRanFSQnYvdUdpZ1ZRCnA0eHUrdXNSb3pvTGFKUWdqSWRl
            T2toTm5LZExUak8vbFgyWTI1Z2RYYlkKLS0tIHkrNS9LVEF4OHhTK0RVZnRIZHlP
            VE1VRm8zL3I5Q0FGQ0J3NktSUHIrK00Kgcg0q18AJxs9Olajz0R21R3aELSIek12
            cTpNTWXYnVLRyrC/WihtcCJyWUbucIu/BkKx1XR7regPbN+UyA0j3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOC9EdVNiWHVoSmE4T3FJ
            M3RmcUk5T0l6VE1zSGd4cG5QVlZGNllUenk0CjJBdmxrV05WRE91YWJmVzdCbnpy
            a0Q1ZEVpL1luY0IwaGZ5VlNMZ2k4Zk0KLS0tIEUvTDZZbVMwZWxNTVlPbitZYklq
            QXV0SXhDQnZSZWdoWTRrdHg5RXBFcGsKoDMnib1NqPX6bhBE/dgY7puVlQgC7Cmo
            Yr9HURbGnVtCDheiPkaRoXMwQY2DI8sBZlJublH2Wl6+bdnhy1+Eaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpcg5t420nf72k0c9rrx7amg0szch98uzqu273exj7lw3yu0j99q6vcckn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaXQ3Slg2VDJzRFVOZ25h
            dGhQRFRmNVYyYVhJeFJ1TGhCSU51UWRGT2kwCjlaMU9naXFtdjBnOVpzdFd5QjRV
            cE4yZXpRYnVFOFJFZ000WXE0M0ZGUmsKLS0tIHBOcW5hUm16ZTc0RmExdnNaS1la
            ZVk3eTZrY01XZW1pblo3ZWdDNGhKb1UKU8xPHreqHjVplZG05tDk1BwKkSYJeaD9
            bI/0wxqCrR9vQr+rBIhA9K9UETQB3BXyhsSjyAuFO9qIAD547PSdxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4mzwe89aqgs56mn8zg7dd2l623kwmw80k90wr2sa6dnlcdmhcnsp4kt54
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOGN5cXFGNzVWdW1GU0NL
            K29ZNUVZQ1hheWtWNzRVanAyYkJaM2JWRlJrCnc4d1BTOHY2SGw1OTRua0s1K0lv
            cW1WUEFzN045SWFweXJ1WHVRWGZUYmMKLS0tIFRaM3ZSVjRta29SUThZQnlDOTlq
            ZVJCZTRrU2kxTlF1bUpoRnRsTlZjU2sK6qj4SHalJtxZwB2Mu+lKcQpzdILz+1JI
            MDJ+q5dvbpijbehET+AeHRIOye8smUH64kQ2eVkIyZOzj2k4Jmlkiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK0k5MlJ1dVg3ZVpLSHgw
            N2h5VDRiYUdha0YwVzlRWnIrVTRLV2ttQTFnCjRWaXcrN093ZkJIdlhSZnRsWEYr
            c1QwTURscCtmUEpFa2lLYVB3SWRHdHMKLS0tIGFNNUFOb3BtSFBraGpOZnpaYjll
            REVyRnhBUXRKdi9aSGN2L2FucUNqY3MKTcDEFAOxb2u4SWciit85cy4FH4x0mKDt
            VI1vKHjIj8xdu2HJnRaDxQhmB8T+ESjbjM0H2gqUZE63dE1bntxz7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MGEza3JiQlRtcjFqdU40
            TExOTGxJUGloaS9pK0VSOGFUbzFKalk2UFc0CkdmYlUxZ2paZnk1RWFNYXFXeVBs
            RmxaM0xVUU41RHV0cklid2tqMTE1VDQKLS0tIHpDUFVtRTV1MUNyUFBCdWNIYllv
            MVJ2R3hyN2ZpY0NLWlNna2V5ekdLVG8KSAaFzrmFK+4zeCjOwdGqXTawYwON1MEf
            hEKuiUa8Hapjf3YOpf8SwwWy/lgEw7ZZG25EI0UoXAJYEhJaXr02fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOTBSOUNNL0RyM2ErS2NT
            VlF0VFNKWkRZdyt0UVQ1YlZxYXpSYlFYUzBVCjhGZEhBR1hMbWdraUF1NW1lc3F4
            QUJua0RiMlB4RzJiZVF2THdaUUc3RDAKLS0tIEVoMGUyQ2w0bkp4TUlZRXFoZTgx
            OHhrT2pSNVVtYzJwcE1RczM1RXhOYzQKGG1dSjAf6maLkupQ66Bf838ulf+t+T5B
            iIS10dFQxKE0KV5wza7DiRtYrsQkENG33zWos1OcROj96GgiP7380w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNXhST243TWZ6U09aazdW
            MWZNOUFyWXowYkN0ckVsNXh0SnhOTTM3SmdRCkcvVnBHNy9PclNCZ3pxMWpnUWtx
            SU5SeDA1KzIyME9TRnlUWTM3d2t6cE0KLS0tIG1CcFRGazdOb0s0S1F4dGNMU2Rr
            SVdaelFWeUU2bDMvTHdxbkV0d1ZNdTQKNkmytMUQTa5c47IUTc4JZ1SAG+Yux4TG
            Y/BLU01iYjguHuJ82q202ekjKKuB5Vemi9ubYhmJxNS4Hi7C2ZhvLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpcyeqjcl8j0dd4sj6f0vufs2vpus3xn4dvxe3cr8g8rgcm0nfxq03ds4y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcGVpcTdwYUFUdDg2eG5P
            VG9DcVBJaTZBN05ZR200a1Y4UExoL2hQY21FCko1NTAvTVRiNFc5M25XMEx4WlNm
            eUp1TUllUUFtRlh5T21odzg3dTN5S00KLS0tIGVlZXJJdC9jSlNkZ09lSlVjRExT
            Y3ViR1FhOVVJSDBOZDg4Y3lYWVNyeFEKU3+0FzIUz9s2kyighf43tox0BFNWVGQK
            2rDOxyxcn0nONHRHQkfPI4EYxAgdEjnE4RqVSkiVXp5wmiQeDJOeNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSXlYZ3RENEVlR29XbXNC
            VmhYdjFmemlEWTlCMFdINjkzUzEremM5MFdNCjN1NldJMUJnT0xTS2kxMHQ0Y3dh
            Zi9yM3pjaFJTbHlpQzM3eWdUbEJidXcKLS0tIEkvUUUzanJSMFhra05DQXR2U1hi
            Znk5OEtHSG1oZ3k4emxNd0czaE5NOEkKy+DDz/qm5QkMfzJ1y0Ldn1m22UBqw5VT
            W/p6wLTooQDPVZ5iAWPTodCsPiwNennBXnb1/BQQOlr7c6yU8w6ZTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWtJU2h2TzBtS1BzOUEr
            RDVPSDg3ZVpSb0NTcmRKS2NhT1RqeG1ReGkwCnVvUzR0TVljZytTa2lIQUkwOFRC
            dU9WbnRybEY1Wm5zS3VWZ3BuM3dYaWMKLS0tIHFLTENCYjRuZnlqWGYzdGI5S1JY
            Qi9DOTFJbi8zOVc1NDh0UURQcGRyQW8KVtDMDXJ/afSfnTCjoWXDDFCfOzG+e92q
            Cm4k6Ybezf/SDdswj9TPDjKghoDTXNkITVM4miwJIN8KXw2TtfTOJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mhrzghrmprq387xqsln6996yx3ja2e2zpamh9mtuu9zqmxahunqg9qugw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MTllVlFvUXJXUlFDSkcy
            Z1Z6M3JOZkJLMVByNk5xeW9HdU1CLzh6SkhRCktJWEZTWFRjanVPZEk2S0M3SzNM
            cmhTandJTHUzRzVucGs1S0hQdlJsWncKLS0tIGRtc1JsRHdQK2ZheWw2QXlBTGdq
            S2ZGbkdNVXNSdWxNUWxpRDRPNisveWsKJEoyjUacbNMHRyBFVoEDiXij4PaL5Ett
            CZUqw1fd33hU9Xpa5SxBZjo3BEBFIVqhga24aMopfQ1krR7wPKWMbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNHRNcFdJd2E0NnRYc1E1
            bXJETFpvTHNQWEVrRktnS2dsdndMa2s2QUY0CjJrUXQ5TE85NE50c0tlWTJvaDFJ
            aHZrbzJwYUZQODN6L2FkZHAyRmo2MkUKLS0tIGQwMVV5NGpncDlKejhsSjRVc2xI
            bWdPZVA4bmpnVDRrc3dnWkM3cTJCYmsKie8gu4ABfyOYqCF5RhqmiAajdtpH3UGq
            4IBSYjgf03+1xGj8EiVxHnIP4eypjjbooRmShgy2Ag3UBQ5x4o4Kog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOE02L0Nsblg3UWcvbnJE
            ak5GdG5mWHN1Yms5cTF2RU43Y1QvZzkwdzJFCkhKWFdMaUlSMTFEOTJKaUQ3clR0
            TUVrUTd6VzlZeS9FSFh4Q1ZmYTgreEEKLS0tIFNzcWQ2QVhGY2VPL2l4SXdSNFpy
            TE5DZWorWFZFKy9xNTk3MjhDcWhTRGsKgS+pwLRdC3GuJi7HJpOu0TxKEi/LbM+7
            btk+9iAryqdXPalSapd6Bcb32SkDfje/STSQaf7WWKyPz9L3tmL/Zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f9hd8fu0694rc3tr6hwxz3ldfpepref937rmvqdxvvsr0kfcjdxswyzvw3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdVAvVHVENGo0WFpHdUpr
            UlBCZDBBYUtwS3A4MnF3czYvbFV1OEpWaFJrCkpjVFRNUHZreW9nVkx6QjZ4dkth
            OTlUOVZaTWI2cGNtakpJQk43UWFyckEKLS0tIEtsMlJ5S0krUnRIdGV5VkNCY0dh
            NE80S2ExLzdHbEtjaHhLY1hVc1Y3SW8Kra+uK/T92mTNY7XATjIi5fOk3YxaBiFy
            5s8avyflNow/5+PsJ9WD9wbLFtugiBQTiWfTqF3bGdNu//r6Hx5QtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bHNoZTNIZVVqRldSanU1
            eGJhdU50R1pPcTY4UlY4ZDJwa3dTTFR4NTNnCk0vbituUjF0aEFjZUlTOHN1Vm1H
            VUJ6MEdVYlQzV3ZpRm5GNFhoMnI2NFEKLS0tIHdQdnRlc1NQS1RuMnQ5c2E0ZjIv
            U3IrTHYrZkFmbnFxUlYzcGgveFlrV1UKovsQb5MMCYsQm2pwpRLWWLd7ogGWQk1B
            QzatXYwqktdnBfCaq0uDcggTrY7ARiqxisFcNxfisUpoV+x+RsmFLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QjRUbm1xQTJicHpBSXo0
            RkdrRjhwaXp1NGJkbUtIR0hXRjNJcWY3NFRnClIzcVp1WUNBL3g4SmFEdm92U0F2
            UndQdktwSjZtVkhpMEtPSm5zbFJMMEkKLS0tIDNIdHg5T3RMaE5PQnVPUks3dWZu
            dkRmUWVBOElOQ2J2aFBPeGxkN0ZqbkkK1tl1Yk8apPHDY5C3xzC0mchjY48b8Xcc
            8J5VTH3fVHtB4TFlr4Lb35L4bCNv1BI/mjftoYtuVkhgKO9gq4OX2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S3d1c09YR3dmTWIvcTVr
            cmNEell1Z3hjMEVKcFNGSjV6RVJMTVpMdGhvCjRpNUdDTWNXZUQ3ZTZOMTVVV1E2
            UTdJMU4xUDBOZlY0K3BEMHBvcUN4c3MKLS0tIERPTnNMUDNRbFBZU1lRaTM3K0dl
            c3J6L0dXT285Yk02ZEsxNk91cWJZNXcKLHjkRKmi/oiHrsyjEz1LEnWWFdaIGDZq
            0Qs6HfhEl3CeG5RzbR11tIpUsPL73SBEmxowwbH63mXJa4M4xbaQxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUDFEY1JuN3JiNzcxcVJF
            QjVyZEZpTkYvMzQxZjdpWlkvdUlQamsrQldrCktTd00zREJkcmVQQW9tL2VJSi9P
            YlA5UFkyRVlDLzB6NGgrZ1JzbEhpUG8KLS0tIGVieGhFdXJEUVV1Vm9GOEFqdzB0
            Mit6SkZsb1FXQXdHZkpITE1QK2VFbVkKkYywJAxhkPsaCojv8nzstonj+cwzs02E
            HG+uEhjHo+3Adwfm91gzjWQmSmWIGZB79uQeGlen8zinqf9Qbiiftg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sukfru07msq8fm5ddgym23yal9lfm99090p999p09mxgrrwh9aqs6zp4fy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMzhKRHo1K3NEZU5HZEg0
            bldvbjFreFYvNXI2cFV0bERvQUJPV3p3TVNFClNqbFJlbUh5UTE2bGIzTlhSS0JE
            RzNBRkk1c2s2ci9FbkNaOS9UaGtMRFkKLS0tIExrK1E0R0F2WjBTY3ltYmxTNzAz
            bzloc1dWNkJCY043cGZJTGR3c0JXWEUKja3WCnIcC50DJ+PkbTlRoaxQEAeHp2kx
            eR662sDgX7CtS1lL9GxK4cqIqBkaXM2vIdT8O7pOghP/KTLEq6XIrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ephzrpgftmvq4cul9766q2r3mss38xu6un74ryfmw0729afysghsh0a3qg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS3pXaXNsSDAyczEwZGto
            ZUZ1QTdNMVh3Nml2anZ5WlBZK3Y4YTl6V2owCmFmeDJwU25oT3hVbU8veENlWWg3
            QjRrbVNxOThxWTBHazM1QW9Gd1hCTFUKLS0tIFpJdDNsRTdGSXZWVzJ6VWt1VFhQ
            dFJzTC9PeUFTdyswVGNza09uV0c3T0EKB2C2ZJT1i0VXLQqozo0JSo+LB3oP5W2c
            NaU/c/4FmOFlKQT33a89mQVmJ4jsD/DeGkLVJ927oszAg6NBt+uxYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSWd2cHdseUprekNuZTha
            NmdnbGN5dG1aM0J3QVgzTlJSbFRVMnVpL3lzClJ0VXRqeVJleGNWMHdjam5QYmhh
            ZTdJYzhVR3FieWFMSmtIaHhEenhBSzgKLS0tIERscHRtcGlqd1AyVUY5cEdNeWlY
            dkpXZm42bDdxRVFCWmZvUTdOT05IWW8K5ZgixOkiuMq0p8Bv/aKI9ifmd3I4e1uA
            CTWuzaJEC2eOSx9a5j+MpoQDNxZiEPhZ587evJO1tWpe+xO//m2JFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7ecrfntus8rvyprzhffjpqk2tmrc259knf9xqajlrqvewfp8d6svwp9pp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRkJJMUZqTWR1M2hQN1k5
            eG5nNVZLTlc2ak1tL0Q4V2kvSG12bkRSMUVRClF4SFJzSWgyNnMxS2pKN0RsOHpw
            dk0zNjVSdkEyNVB4RXhCOWZ2MEEzbTAKLS0tIGs3d0xOTGE1ejlhSExaa3pYby9v
            cG9DSnpIeGtyaTVkaEFOWE1JcDQyalUKT/J3l5YbJuvUYiB9lLPnw0CtoJKbyMmB
            CkGoIM1Ez3Hw7P/Lb0JpvKAP/HvkwVFctdvP/YS8Fa54SEBO8vdBow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:+41lK5FJuRHVHRH/QDls5kkZILiIfl4vKVLlEbj7SrsQ/MtWMJzlXKOcGq60o29lylEgSvuKf+Kfl5FQG/CHGjI2K3NxSYn8+YOOqYrcoeXHT6ywLXEBEXOJw6FQ4RkVAce4P0zkGiC34fzdew/OboBS0ltRJdmNHWWzG0ypPqI=,iv:KS1T6QQ63cqDxkhb6GFkYv0Kk7VEjm0YGcpvq3w6p+g=,tag:Aj65NcdCfxdzgoj1MepMBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
