apiVersion: ENC[AES256_GCM,data:2DA=,iv:BHk1XlKBcOkFMohLXSPoi1QNOw7PzWu+/D4PGdTEuyg=,tag:ms2vaJUbqLlCt0a01SswiQ==,type:str]
data:
    password: ENC[AES256_GCM,data:ZOG2Oc4Q6svK46fH8+dYwrSS8550VqEJiAiVbv0txmg5CZDc2NQ7QA0tZuM=,iv:+8hXcHtoQ8kUTQwWH0GEd1AxIdyE+l1zNQWzLo5EbOk=,tag:twtN3QCetBnhxFUc7kl55A==,type:str]
    username: ENC[AES256_GCM,data:k1NoHbIcxDrxUEG/,iv:wyDW/z0OQddvDpIh3uhE/8MRRSRRmsA35OJySgtielg=,tag:gapHg7ZE1WZS7ldyncSrqg==,type:str]
kind: ENC[AES256_GCM,data:cEOg/uHG,iv:1OXtPrRfpbw6UzDRx8bd67kuDbd159peVxHbk27hWkY=,tag:Ot/jiEynI2LTlOidiuNE1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8h9f87oo5oU8ejfy9+6lmgSz,iv:q1g+b4Qm0H447xxkqsT2zsbo87fqwMxybUizp146Lb8=,tag:3U170h03FomGa8SX2iF3KQ==,type:str]
    namespace: ENC[AES256_GCM,data:z+BQsQlm8x0=,iv:u36HpA90bWX6dkppXnfatcQsHiewylyqKLeLQAoJ+CA=,tag:87kJD2MqabX+e9q5qAB4Lg==,type:str]
type: ENC[AES256_GCM,data:ZHIkDzUiejlBpWd/9e/kGftfEDsbztXu,iv:f8X3EuQwTYldEC2Q/OEbHPyWsLH9IG261eh0AULvvUo=,tag:o6il+Tqaogki1ZUwMLCDbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERXg0cHdET0lPbmF6c3M4
            TzJ2MzAvaHFkWnVlUzRJNjNzWDhnUzVGOVRrCk1UZE9ZcjhkM2pnS1VSL1pqVVAy
            cmpjZjRBMlZ2YVZSS01MZXpFRUR0NUEKLS0tIGJLL2FjMlpCUExtTjBLTnlkMUFE
            bGlBVDRWM1F3ZmJDbmh6RFQrTkhEb2MKFI7bXUcs6bpckmlznLzQ+sx2f9g0OnTY
            94GZkt47AinSS9xFei8rjFpHDEoPObYg7Of1e5c+JvSupIbQp4NdXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ2RjNnEycFBlWlpFUDlt
            VEJLNXBSeW9KYTd0azloNFNheVhvK3J5Y0g0CkNmbHllUG5hcmxibmJuV0lITjFo
            aVhrUUwwNjdtMXlmdjQ5azVNT2YvSHMKLS0tIHVvS1JtUHp6TEVrS0hEZFI0Q1Rl
            V0Qwam1WZ3VGWDlHVEV4WmxFOGxOdUUKRzr9SXdANCVrymJOJMCV2ZpmqxxlMoM0
            nw2JmMNnFYWD4HA7hIN0/XxACB4LEl4pWsi5+iX/ffDukawnUWZSnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL3pOUDN1ZURiYm5OZ1VY
            aVYwaEdteGJpWDVWdkxKVlZSVFN2cXJHWUJnCm5WRWVocnJHOGlEV2pNdGVtam9Y
            aUtCa0NEdlNTcXhpU0QzajBWUTZBblEKLS0tIFZxdjVva0ROcjhNeldTdWtrcUdP
            WVU4NWo1Q1lkdnpsMCt6VlZzMHpZNjQK3WANdOTvuPY5Ut1lYJztfAteClzVKKzk
            xyJTaUQJhq8FR/1EF8DNmj0nJGYIIHytj5KyVlTI5aEVek0S9jvOVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1J3ZWtkUzhWY1ZmZzlX
            enhQeVBWbDBsTmtzcjVqNjBJTmFBaWpXWlFVCldoSjMyNEUvb2VwemYvZkl1Yk4v
            NUVnYStUMW44YlczeCsrb3ZLZ1RzWUEKLS0tIDRLQmhGMi9kSXNZSTNXQjh4N0xG
            U1UydHFtaVhFR20yYWkwcG4waVE0SG8K0rlpg3BfU+zXTqKWAdbJ2l/c3FbxL+FZ
            rE3AU8N0LNFGvZ8TB0hzBJxpjOPkyoe6V9g3vHhBn00ewApE9D5HHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVkpidXdpZTZqTVVCUzFx
            Y29TZytVNjZUQnRoUUc4MU9vQWY4TGVpcW44CkxXeGhIalNHUEpaVTRUOHY5Vmxy
            Y1paQndyYkxhU2dIbHBndGtHVktNajQKLS0tIHVXQlZMcVcvbmN2TlBEMVliMnRt
            cnZueUVXNEM4U21ONi85cHovemtFM1kK1dA9ies3OzdkWNIw66RRKpNTmzjC5Z0h
            uYpvPOrucv8H4FKXzWOOBIELZhofhD5q48w89xK6EqMBNRQK2/ezGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzV0pMblkyUzdIN2cyOEVW
            TkJlRjZYRGhRc0wvZXBYeWo2cEdTdEc1Um1jCkMwdHJnbnA4MVpSdUpicnFKTDhl
            TEdxZmJVZVIyWWJwS0dRdEZzblN4VVUKLS0tIEVuUHJZNmVYdFJuOGY1bWpHWGpZ
            eFo1elN1Y252V2NlWFNGeGZUS05MWkEKlt96bazbwEVdrHYga37Lz2TzvyAXRdjd
            19bJgN6TXfNA5a+t95ivO7hLn8blFBcxfVCFTWSSCnqRzbGkV+bSkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTnFaVlVGcnQvYllLN1kx
            MDJyKzllcDVKRGpSRVl3VmFESWZHY1k1OFJnClpCN1k2UlZNZWZoam9xVEVPS2g4
            UzFhMm02dVU4dnkxU3BrK04xWWxrRzgKLS0tIEs3MVNBQzAwNmVxT2loK1BmY3FU
            WDNkM1NPNEVZd0lrcVBQbldIZGdZNUkKe6QPmXKU4hVmu1gXZKMZEIqMYlElHY9p
            MV4qeAKi4pbybmhw81NR8m+J92IZJd7lsbJJYf73exmDmSAjNk2bag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNDduZHlJem9tU2VJNmdY
            bVprVDhyOFFNd0NzcDZYeUJzc2k2ZDZncjJJClh0dk8vYTdwaUlUZDV3OWZZRi9F
            S0VCd2VWREhnRktZaVhmcTlIZHNJdGMKLS0tIFp4dFVGT2Q0TUQxWCthMTYzV2lQ
            TDB5YjU0Q3FyYlBsSTdRcGVFejRVd28K09ws1a5XiXkt8jALN63ZHVA/26xx0B26
            d+lHjcX47UP9SgEvfunnN1cvJqyp3yvV5LF503fM85PIlmiwrPaaLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieStobU9QbjdGdU1nNVpT
            YzdJUmE2djV4NDBCVWVIMmRsNWJrbGdoK25zCjVpdWkzNWtCaDhTNlpSaVZrcmhO
            S3JTaDZjdFBKZ2EzcEV2eVBqeGZ5QzQKLS0tIGRWWlNXNnBaY2hVTUhNNFhFYVly
            UlNja0JWUnViNzgvUXZRTXBzRGMvZDgK5qZ94+06j+LGbkVuxHD8UdazypPGm1Jg
            bejYvXtKST7ZSW6ZZESnBkrGP54b9sazjenTclpbKDNyNFnVmYIsgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUM29ibUxCTkVBK1U5SlRo
            cms2MjVPanBtS0IzNkczNkZrSnBMMEtneGd3CmlVWWJoK1lnYjI5SWgzOHMwTS9w
            SDAxR3lMQVFRY3J5OTZnVXZMYmJGckUKLS0tIERQQ2VCWk9GWHArUnVIVmF6dHI1
            bE9NSTNjSDQrY0hXZGQ0b05rYzlqaDQKjK7M3NqHQQu5HSN77pJu7w9uZstgbity
            8JOOLAxcGeiJlb84u+k5Exi7vB2B4UQGeZ+pDbsDJFSbxVb8wVwkjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZGkxQldySklxQXpHTUwv
            aEhQOUMwU3pzSnh3NXFVMDZDTEQrVnFrMW5RCnAva2owbDBCMzJTTk5zRTd4TU9h
            RUxKQlNRQ004eWJuVG5ZWnVhUFArdEUKLS0tIENpU3A4R3R5ME95M3E0T0Y4bFps
            cDRDaHVpUWkwNUc4dCtpZi9ZdnB5N0UKuRu9UqL5lbINqc3Qpj9/EVZsN38JE3n2
            HKkTfIwDUESlaPo6XRctuqbsme7uHRV/jKwnpFfqXaS6z1MnAUotLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZytPOXplQmtvMFlWazR6
            dEtwamk4RmxvN05lN0tTVWFqeXZzRmduYldZCkJ2Y3lLcFhsak5MVUFXazF5YWhV
            clZaWUdzVElMUVdKT1JqVHdBSmR4bk0KLS0tIHRUcEdCaDkzY0V0VVROY1hyRDEv
            ZGtyYUJnVFAyY3hOcGw5SjF4VnE0WE0KHxaH7L+2NO3XESTwm0eeakR1Z1KqCTt+
            om5bJs9hphmtlyw/Oth9jRBkvnNhFtHmo18TXZIz6IHY6kZUTnVnxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-08-15T20:48:53Z"
    mac: ENC[AES256_GCM,data:5IyLSrDVxa4pXSZ6q4ZhfTH2P57P8HbxGejCfd4j5US5uxLRzy8MZ8/T84uuvZAYPmnHaiogBgLbmTy8N/HkpJ6rHqUF61D4yT+B4i3xRNYIaAg+yo9AZDoY+bNrMkBTjaGopjXxUYKC6lEH2S5AIefXNBoU0y+qj5gGsc90DPA=,iv:zYE9tdMTyAtwQ/gcgltQX82Z1mrC15YjPJh54VUwWKE=,tag:DoMrx9hlQCsO09f/+4JUJA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
