apiVersion: ENC[AES256_GCM,data:Lbo=,iv:t1l+duRsYL31m9Mc7XjzkWxQKVW8071iSBFx9aPxEz4=,tag:xPiDknsARJHMYe0ViFMFrA==,type:str]
kind: ENC[AES256_GCM,data:PNT+XwOb,iv:DwyN/kv+iyICgL4K8bQjJJeNYZOI6/uosVUlsSBIpbY=,tag:0vWcsxuS/FqHeTCPJSpRzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yoneMZ/WlpURIKD1RFY=,iv:jQRq1xAbjfCMfOR2TwIYARTY5DdZh3OXWQ7a2ecMVwQ=,tag:EbxrGRgOB5chFlYiOIWSeg==,type:str]
    namespace: ENC[AES256_GCM,data:GqEIFcXkVIztaBk=,iv:KoJupKwZOis8zdlqAK3PdBbQ9m7inz9CdsUcTYqRsG0=,tag:S0Q6VMMcjpiMnPjln9tS2w==,type:str]
type: ENC[AES256_GCM,data:6QmIh9T8,iv:klHp+TpViUcEFOEkCGvBDA+KDtxwYv/5GlgY8LiymU8=,tag:hzUZorMvYHI9qn6LxoYkgw==,type:str]
data:
    username: ENC[AES256_GCM,data:8ckqo4PJLwE=,iv:5gtBTsTeQdjtmij3gKAhO0lmRPeIIYrmj5U36hAPlzY=,tag:1n7p9KS0yfbPH3tdc4Or0g==,type:str]
    password: ENC[AES256_GCM,data:2vfiQEsd8P94b4pPEK3tqhegULkzuyLU6CO/fsd7zsLzyBLOiP3u9/UFgc2DyH4Y9mcDd0Zv94vCTHFCTvcchA6tVjzGmDAFKB0VacFhulhMR06tSuKvEw==,iv:q8I5l228GngendO4OnfkfN0OIicR5mFO/LOPO6lvTzI=,tag:p4ruLb1GgE5xaZKQGYNpSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK2MzajBJS1MzTXZvWjNP
            b3hGVUozUnBxODd0Vk5SQnhPVHJVTkVPL0Q4Cmd3MFVzSXdzSS9JWGk0b1F1VlF4
            TzN6dmowKzZGbFVFbWVncWNPNlVmWTQKLS0tIEpwS21LRzRWVjdoeUJtdEJSZ0Nh
            Y2x4bWtZSWQ0cHNYNGxDM0tqd01XME0KHnqruoGf+PFsUnRjaVsayMfMipXyVwox
            PqWN6QZByyrnFteCLIVDQY7dU3S2slBYxdnMVMG48mGfFcN3+/cmVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q1BFelY4S3JVODRTNDFk
            VjIxbWxrZFEzMlhPSmhPSFl0NER1TWFtRkFZCmtKMForckpGT3pQZnVHY3REZDVv
            aG4yZEdrRjVHQ3QxdlUvcU96N1A2RFUKLS0tIFh4Sjd2Q1ppM2JXUGluaVduc1VX
            eHJwdkh0NmpqSExibWZScWp4QjNBOFkK7Ks+4DGsj7llK7isfUIlgyGh2bQ8yA+9
            dBuVRdxycpB0+jFjvuOlIZmXuM6hztAjNhU4u6tMvP9PhAHtC7LPZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OVNCQzV3R2I4d05QZUh1
            ZTZvRXpHWCttNk8wb1RsRTVsRmtFRmVBYkUwCi95VUZZeWp5cnVXM0NURkhaMkw2
            bzE5aW9wWTRGSkZMb1Npc2JzWkw3NTAKLS0tIHlHQ1g5TjZlRVNOSk8vZitXSjkr
            THhUVUNzWFA4V1BBVXB4Z25KblR1R3MKIN0ssUy0Q7X9gY6Shbbdm8dim8fbFAyY
            QAG2Jl1T061D1kNE1hx7lBRoqnI0hvlHme6va+DlZphmXi5/qBQQnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUk1jMVA0d2xsdDZkYjdE
            ZUtMMTNpUGRXcXBKZXdnckxGUkc4QjhxMldrCnFXQ0dmYWlDdlR0ZGVRYzNJcVVt
            QytINXZmclpWRk9xNkV0eW5ZdTQvY0EKLS0tIERHdXJJTHJ6WGRvdWxTdGszMjR3
            QzMzNzE0eUtmVmMrOStuSlY2Tmt4RTgKHweFf5nquTXs3/RhmZOP/hLo3HOYY+Hi
            Ii0t35BwJxfOq+ypkUmQ+kQT8Zt9NiYj12qSIsBSVvbf/MTtczsYoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVVA4MnNhZmZDL1RFQTBO
            TWpybW9WdlNpT0YzRnEvbHdpSlV6enlhd25vCjBRa3gwWmZZbVBrZ1UrZDE3ZUha
            elEvNTV3Y3FZOHBIWktmeldUOHFkSHMKLS0tIGljT2dibE4xSjIrdUZFUnlJanpu
            aWc3WC9YWnpHNTcweVhQdDZrNnB0WjgKN0lIeCzVPhn/IFihEDtFSovtYhlwBHBb
            olzlffR/6rO7Rxl2ZnzDmW2KzYwVwUXq97bgAdbDR0FmZY9xTWwBRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcWRqRjdIK0c4c1Bwa3lY
            eFRrelYyc3M1WVBadU1yVU54bHgrQm5UQkZvClU5QXJIM3JtczlWYmVzbVpyNlFl
            OTBEZUNKUXFtUTErdGJoV21yZ0o0NTgKLS0tIERPK2oyUm9TL2lxNWRjWFFLdDMx
            V0gxQ1kyU3IrclJWbTBIeWg5bmU0L00K5FqehekR+cMzOXQEvu226LQK7kCGY8Gx
            0TvqXs+g/XdhUGGuLLHXPttxOBhGBkQrdasFNJ7VuYPfykSyzhOt7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6czJKa0Q5K2UxTUhKYXB3
            YjJON2Y2UFpwL1pHY3AyMnNaY3U3ODM4T1M0CklKbnJyM2g3RkNYVFNpQU1KVWdT
            SGs5ckVTMWw3RUhoU3Q3YStyWStwR0kKLS0tIG53ekhlbkFxdVFDSW9OZWlFdXVS
            dDdlRmVNT20zMGxvSXZmSHgrMU81V3cK0gphDZjBTyh+NYUSr0qIiba+cGfptN+j
            vLBKw1xl/nw7sjDHh2erL7whvZJrdSURy4YZTZ085dkJ+3Umf7srTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMHo5OU9BcWRUeE93cDJY
            c0gwYzVLYjU2cjJCOWxSUFRQVURyWE53ZTNrCjZOclJZTmdyaXhjQXd3blBUeG1Z
            RlAyYnZMWlZERjBqcmtJU2lOa05mRzQKLS0tIDlYRFYzYVcyd2xCVDdKMlkxY1Mz
            bW55bFF3K1pLbTVPSVhOd09YYmZ1cXMK3EM01NcNwiEtBCzXOSw4Vy1L59mlINKc
            iON8xNe7+7XHth3kUWUBHYZzhb9rrR6HTNC6/oT4RS+C/tWRX6iPvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK3FFOVU0WDJ2UHJBM2Fu
            azNGRitBTWV6ejJ0bHB6ZGxuZTUzRVRuN1FVCldad3JERUJtRHp3bjVNN1RMdmp0
            ck8wWmJmSzN0dGpHVUhFUERubnBQVEUKLS0tIDcvT1pacDN4WUFBeUV6dzd1emZP
            czlkd1MyS0txRlM3YU1UMWVDQ3NEc1UKuAkWaXdiQrzsbQZOsyxy0eAa/o+XCb9u
            Gw42eEgie1b+ntjnt7tlEbZvd5yWc2l+K4dzt4M7uXmWVo5aNBjmag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOUZVRi8vK1JHckl1aGd3
            NlNzblU3eGUycXFzYmZJbTVHVUd1VWJhMng4ClZRNXRodFV2a2NnZ3lxTWFBY1di
            emdZVEJWZWRKV0kwZHc4cTFOdjB3Yk0KLS0tIGg1blljT0JTSlhUQk1LMWNSVE1k
            OUh3K0EzeGhjcFRKLzdybUFoWGJNd0UKGDMXUhmIIHijeO6cRfEGr786++UfAoBF
            g3MZEA6aDvKSfRfpBY0BbZSSIhUez6BKvtkIWX4fmThXXRbM/s1LFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSG1BUXNPbDRWQUVWSkMw
            bnNwbzU4VUJhUlNZMEs0eUpRT05LMDJCNTNrCktieDVoQ1BIUFdrM244U1JISEZz
            R2RMOHMzRS9VZVZlV1pvbVo3d1ZDdEEKLS0tIG9xdVpwZUVKNU04cW1RZXZmOUY4
            bkNhb0FDaENiQmRBUnZFcktvbHM1d3cKZ256ClTV/3h7V+0ZzhVsvIBcTOz2d+Ir
            HHMW5favECtKeq69TgUlgyUSfb0GyLdedJIJDA4YGbJfqEJNY9eH1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNXVqWUdvVnZmY1hhcHFM
            OHBIbW1hQ2Vvd3c1TnBjZGVpQkRiZjduY3hrCmx2UHphVDYwcVJlRnBOZmsyNzgz
            KzBMdmhqbVloeGNjUVVZdE5ucFNEZzgKLS0tIHhiZVNKSjZyUkIrMGJDeUZheS8r
            bjlXRHFnV3hVaVJqa0pjNzBXZ2tpRjQKQArdetiR6/T+rcmPJQeWZOJl6FzQrzli
            KEkIDEcCO4MBQop0tgPa5lWLHTJTplJMSLQKOE52WrZ/fLl1uiPGSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-08-06T02:32:51Z"
    mac: ENC[AES256_GCM,data:HR3bbbhPMjZhaNshCaqiqArZnSi9ltcHXMfwEN7HM5OWhoOUYuyXPuwUOewmv56cHeDIflXG/8EuIkHoAHO7RZu4EY7+SVNL1DQGsQAr0F5x5GblnZDY8J8mFsAL7p1o2CKMjq5+V6GXA4AWNENr+DwyUHKNKAyeyODrxI5bLQA=,iv:lTWlHrQrFPyev4LMvLrswrkEFDuK+Gmz6TqTUc7fhc0=,tag:duRaygJ+4i/COpyBrpDoDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
