apiVersion: ENC[AES256_GCM,data:zZ4=,iv:4x2VMC3p9OunH5gm0/ALVmjbjYfgTrkN9D3vJNEkJxs=,tag:OjKStza2MM2k5/GmPFYGpA==,type:str]
data:
    ADMIN_TOKEN: ENC[AES256_GCM,data:yX3Ls47XjhIicQtwlJnzWe5SaMrCMuXIAugBo+B47xKFI4tuTowmNgmRhQw5vajDSnsq+1YmBHNnLBAuv3YkVHjWcBnlIsFEoEZVX1XVWdFHg47tlL+hw6QUqJjumNz0QtaG7WC1dQ/H9zP3uPd9BiPcOzgfVYCHhCGgS9LZwgs3gMzJ+zgjc86Vl56AC0frMNB6S6QQwc6iPHF8HZOZyw==,iv:wse+icmUldfWpJ+ldW8LQsbMdOybza32Vc4ebIcym5Q=,tag:ZLVA2WxKYkxFXzTYs3heuA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:q6cxDgIaJ3IDu6PLYks6Jxi2uwl9Nl3d,iv:lkCpLsU+Cj7fVrlMZ9eI+CGGQrgMS567K00CQKrP70A=,tag:ICTXdrawomJLe49ephJDhg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:bjhK+DnLCF5DQU4ErSoQX9Y3+/A=,iv:vyDpL7MsTynTQwi10iV7mp8YPuIVB3j7Gh1tiMTAO+0=,tag:zJvy8B2LgiKorE1F8twkdA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:tzQine5C6YYG83HKCqHAAnzcmmOQ8JZ6erE/6Luxe1hEV+BIRqoDkulk0duibuXs,iv:+jHTmk2bfssClBgfYAqfTbmZ8/zO464PXebc9LkliZU=,tag:EGB+o+oTdRdPUdsIc3qpCA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:E/luVA==,iv:xf8gh0M6ir0EU2uCu9YqVVSyF8K/FYEzAeKIzh7rNFA=,tag:WiH49XhYhs2hfgQQCyW45w==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:QkRbeUSei68OxzVW5Fv2T9sVBd1m8hxw,iv:52oK4YTriDDNfR8ZLCJd+vzeCTyBLS7B/MvjpOdMnT0=,tag:G/xYsK/bcVNUJO0UIA4iQQ==,type:str]
kind: ENC[AES256_GCM,data:9jNkJxza,iv:HgAoksFP/7PsSoR5M3d/7OVDwsgF7JYkNGhmvV4iNCM=,tag:hPq+sq7wF3SQaC1tTP5yiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pIr3/rWDEZkjTni7kSz1,iv:mstmJJL68dEG/1WTDeL/dbPBdwWEveMvBZybVxTNNmQ=,tag:9EIZBXvkhMJoM6mv3bX4HA==,type:str]
    namespace: ENC[AES256_GCM,data:SgOTH3kZYg==,iv:wD5ZnBYvAvh6NnuvrD95i3Pst6654jSEXSg9Cm2wvxc=,tag:7Q1Xs6/8O5KnRzQ64A1OkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVEZacURqMHBBMWN5QWxj
            SkJ2eW81MjV5UEkyT0F3OTk1aG5RaWJPK1RNCmxWL2QvaHdYWTMvaG1FbmlZRUFv
            RE81Umg1OGJyRXlXcGkxQkQ0WEZIc2MKLS0tIFdRaldtMXg3RmIzNWhZSzJYUWsy
            MW41UzJUekhSM0NhbmFwQWd2N2t2MDQKpTz5B4V+4PfP6kaT5zakCbOyTRC4Bsr/
            zfst1gSWuA26Bde4Fn8AaIkldt7ZUJKvf1HG9CLX3vuMaiYOFT9+Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ280bGNqOGhBZEROSlZr
            NitEUnNld25ONkJ3VWh4SkFCWUFTZWRRendVCkpmUXd1VTJzWHZTd1pzR3Z4VE5a
            NGZFMlBaTEVRbmFycWhSSXhXSU1RdjgKLS0tIDZUL3FtT3FTcHIzTlFodUd6aWx6
            bEVTT1kxbHg1bW1XRVNmRFBuSis2TTAKFfVLERrHZFWQeLGJNdKLF8AH4CUt8ZP9
            IfeegDtmPgkc7e6OrR6xAdNQFY2/5vjRYu6S9uM0xUfYkeschIkAnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpcg5t420nf72k0c9rrx7amg0szch98uzqu273exj7lw3yu0j99q6vcckn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYlVoOGM4TXZkRmQ2WHdL
            TEVGWmsrTEo4ZmlMR0w0elhySTlPdkxISG1rCitsNkZxblMxV2cxeXJZSHBVR3l6
            QU00VUN3YUhIK2Z4QWIzc1JVL2E0N3cKLS0tIG5XYnZWcUV3b3kxNWVaOGhhaVo4
            VVk3YUZNMEx4bnpmL0VPTnZuTExjazAK0DvaTSWWOFmLgNGHKiKinwbESAnC80QD
            zHScodwrjalF00PNaEqCfmjzLaHYHX0/iwlZS2kecy9DrTNMoQicIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4mzwe89aqgs56mn8zg7dd2l623kwmw80k90wr2sa6dnlcdmhcnsp4kt54
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaloxR0tuVnAzdnVKSkNQ
            TUVZS1o1dEtSeC9Jb1ZhakhvWWhJTXJPSndRClBpRm5wWEg4RjBXSHhaRUtMemxw
            SzNxWDNHeDMvcU8yNDVHeGh0NHlCOGsKLS0tIDdEdWxRNFBPOGFkazFPRVNrZGNi
            TWh3ZHM0R1A1VkpyT2I2SmJMdGtHeFUKB5gFCfSSfHT0XVCQOdAlaEI6na6CruXn
            EUefOmm9ZND4KoRQpt8rNv1ClKLbF1iGZKyrKHyN+mnmlsu8W974FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWem1ONng1WG5DR0tSNXRh
            OGEzaW9oNUpKc3V4RE84K3RVSXd2MXJ0R1NzCjJvRmVlOWpHVzhqaVNqR2h0bjg5
            WncvUGRTeGlxbmlQSlVtQmYvamJPd1EKLS0tIHVwZmhoT2J6Z0N1WGh2UGlGOVFB
            Y0dzQVdVTGJnZ095MllWRzZPdlkxdE0KIrMeDqJjV0gWgRRF/OmQFfYWF0MZ5erF
            Xho78/3/qKupSZ0ls0RIkT3WJnSpVhkknd3hoARvMlAnquifhcYO2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbWJ1WEtuNVhYS3oxT2hQ
            dkNVRlNCWFBwd2lUUzV1N1pHQnZWWlRHNG1zCktBN25uODdPTWhNWVZVZHZYeExX
            aHlRTi8rWVIyV01HM1c1WWtqMkdaeXcKLS0tIDNGK2VSai9nekMyRWZVN2FBR0wr
            YlJPTXRXWXVxYzYwM0xnd2xHcTQ0eE0K0c0sLlt1+9WuOU+qbDtw/6hN3QhcOoN/
            7EvUik9x6bjQQrmUhzLCjvdysLY/QZ9tOdFTCbhRjb7tgVB46UETrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNkYwTlhnVmZ2RGFNVmNT
            VUxvaHAxc283a0huNmJwcWNrQXg4ZGUwcEVFCnV3eXlRN0FqaEZTRCtvOGRFczhE
            c2hzSkdUZVhtWHJ1WWkxUlBwME5xaGcKLS0tIHNCVlUvbjhtdUViMFM1V0RndDlO
            eGwzT2hScGpGUzdrcGpPQTFSR1NUcDQKhWUkqXLdHrgne53S1NmRCSmyIDTrMrhb
            b7oBWP7cbz8nBucqNYLR5hI7xAu+3OWhOeqZIZQaqYv8ZnXQN4NfwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQXFKUTNXT3IxTlVPT3hI
            YWhvcS9hanJEOUtpSmpXR0VMTVowNnREcWxBCnJFamJmWndqZXhJUkdDQjZSUXZh
            QytlemZzcnFtRkhSV1dHQmJzNUpGSWMKLS0tIDFEcVRzWlEvR0pPeWtaLzlPQWU5
            alRweThYVlNTdGZZR1dmZnh6Wlp4UUEKoBHsM3FAk7B1mn/Nd7GGBdqlT40UBWgR
            hfV0C8DZ7QXtIEzKU46dPdEvG+AgavIig8eQDMM6kmGosxq+9leUCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpcyeqjcl8j0dd4sj6f0vufs2vpus3xn4dvxe3cr8g8rgcm0nfxq03ds4y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa3hoZTZ6Q1NCZWFGeVFO
            NXJweHBYT09QZUdjbmpBejY3Z3U4bFVCeERrCkdRaHNzM005bHBNNlJ6VUU4YWFE
            T0VpVWNhSTVxK2hJQUNUUGx5V3FYWlUKLS0tIFZMWkEyRTRVNEpNRi96ei9WNWhK
            MmV0a1RGSFNRUGJ0YUlPUFQ2MU9aTlUKuVqaJeOJuFdTZZNfmrQgUovs9p/nLp07
            +tJePelK33UxF/NFNoHQniBKine6r8v9uX3R7KFQY5xY1hra7qLfHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z0xETW1qQStsL21pVTh4
            dE1mZ3BLdnREa1dmWW1Ra1ltTnVKbFNlQVhvCnA4VkVteVZkUkozMCtuR3FIcHVy
            cWNFSVREdExOemprcTlJWjNwSFcwSjAKLS0tIHhiN3pIcWNuOXJoYThrSUxRY2JT
            TlFKYzRWbXEvcldhUk1ZdUNyOC9iZ1EKFYe5AEK9VV0zIoqjjKTRdgtBhcNhxB0H
            +ix8ZviJkhOQVqgkz6zEmJCsitffcoe1xzN1BSTQq99vC2J74k3tiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUXdsSjNiMjkyaGMvWFpz
            UEFaZmJzeWZ0MkNiK0JCaEdlQmV4MXR6VVhvCm0xWTJMZGNJMFViOE50akJ1MkxT
            bGRhSnJqZzc2L0NWVEU1dDBUcW8yaTQKLS0tIFJmS0sweTk4blJ2SmN5YWZDM1Nh
            V1JXQ2toMklhbit1NWNNM1Fad2lCdlkKXN4JOO7pIt9lyNDwGHmlRiEje3eNnVpw
            u0kGMW13tqkeK2iaTPUU3Twdl1rV0UwU0ChqcTFdg0WaSSr5lWDRnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mhrzghrmprq387xqsln6996yx3ja2e2zpamh9mtuu9zqmxahunqg9qugw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd200RmJRekYwMUNDazNi
            UkdYcUJxZC95NEVKMkpHL2l6K1ZoSHFrV1JjCmYyaklGemJnbEFySjd2dnhUaWNR
            TDBTTC8zK1ZETExjbFc4Nm54MkF2T2cKLS0tIDAvV1R0Vmw2aitlNEFISGIxc3NR
            TWNoRFk4TFZvVlRrUHBrWCt6S0RWOEUKlmZZpTDvopWmPvHccP2T+iWlmewmnYCV
            rhIPyNcVLUUsWoVakhP16f+4qZqenLdW9KUfIpWN3onO/xF6O1tDFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UzlWSlFqblZtVGZDYTJt
            UkVUeE9WMGFxUUl4NTJGR2c4Z09uQUdJcGh3CnJ0NGVFRTRSRkt5aUFhRkFzTzlS
            NW5Hckl6STA3azlrRU5rdzdyYmZrWDAKLS0tIHZOSDR6SHR2czBXSmdxTDhJQ2JY
            L09yeDRKazlBN2d0UU5ndnZqam16TTgKTsFJEB2QuXwoEDntx1DbtMwqaAIfMyxS
            08rb1qMioxB03TLV4AK3rLJ1Rgee+NvB9fr2OlVhVGyqVSzHVEKEqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOTR2b1dQSXBtZFhTNnF3
            c0lLR2JQSzVkbUszNE5zcFM1eEEzVGd1TUc4CnZqZlFocVRXY0JGOWNRNkRhN1JT
            OUtSMkQ4REtmQmpOS2JaVUUrbi9xV2MKLS0tIGpPUGI2UElHZVY2VGNSQTluclVr
            aFNsSDhhYlJrcm5JY3F3cjIrbEJRL28KsSpVlJlK/UwapGv2bGG4iklKI3Qx/YwF
            8ssY9a0QT/HU7A4DXQssuvtYgkoJwpCRJCXbueoEJzem9V+rrR9+mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f9hd8fu0694rc3tr6hwxz3ldfpepref937rmvqdxvvsr0kfcjdxswyzvw3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQ3dYclNxZUd4cFJZbHZE
            QXMzZmcyWHVvRzZXbTlBK2NBYmVlcHlRZkZjClYxL3RtVE4zeGxMYVM2eXJTRUtB
            aVQxcmtJTmRhOGxQMmd4c0ZFbmh2ZkEKLS0tIDJSR1JpUmh3cTlrT1FQTGxKV1hY
            djNLUGd3Z0MyaTlIOXVaWHliblZTM0UKbIZQsOhz8XYrE0IqRrUQdiu9cQdXcZIH
            TXbroMpDSlERZ9V7pfFzEpDvgtVkvFSbXCVy435HXDry756+LDUX2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIODdQYi81TnFKVVhrdG9P
            bXJwQXZEZFdMZGR3SHhyano5WmRvWmJNSlNnClM2dzRab1FyYmUxaC9jUFJTRFFw
            MlJTNjlNYytLMnlKL0xaUlBxWTZiUW8KLS0tIC83Wk9uRUMvY3RZVUtLYWlENldh
            UWNxaXZ1T2FkQVIvUFc0WVVTdDJaeWsKEoo3ALl/vySGtkbKICBg74Ry+YbvPP6s
            1p6X2JqGd7salxVynrVJrL/ew1w9pmq7stjETCZtRPJf9ghtjfNGcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSWVWTkxMRjg4TGYzMEtr
            UVVSUTNiZURha2lRVEQrOFl2MUJaQk9EclhRCjNLRHVUODFnOXBoYUJhTUVpdEVY
            STBBRDNHY3NxRkc2ekJsdlV0T21sd00KLS0tIFIvSWZ3U1hNSk9vM21qRHI3YWZ1
            TGhPUnNNb2hTY3lPMFFJUVNaMCtJUFkKWri+pryCNcuhR8fou/wXdMJVCFtyqXli
            iQ7vS7i/I6daBiKrQHthZZa8BqQMQkwn/YMe8slwzuKoQCPwS5Az4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbXFKc3BLZGtBMVJla2Zu
            RVZuS3IzME9WaWVvSXZ0cU1leWNKZ0duZHowCkNGY2xiUC82QTJxSlM5MWtpNDl3
            VFluTGRFdVYvY0VYM2VUUTl0eWdITUUKLS0tIFBRdkJtMXRBU3d2b1NYT3JLOTRN
            SWV3QjN2ejNNYnZZY1NialZFZklVTkUKUkIdvGEEnlIEhWWMO/DyDxs1zT22xFV7
            XZ76F7zEEVQS0MdZHzgKnIexDjWvfX/mfbEQqr2ipoIBzOvYjueX1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQWNERmVDbzBnUEpIUHlm
            TmdtNTYwVVFCc3NMelM4Uy9va21xMFEzVkJNCmxidGowcmRvdU1KRFJVQ1NMZlpK
            Y0pZUmhtWW1GZGFVTU9SOXBGa21raUUKLS0tIC9abUhndSt6UWhFM2lGZ2xTd1g5
            OHRONEx1b3pyNmJnWm0reGc5cmMrQXcK/8YHf5AnEWHy/+w4+A2cVPqJKa/lHf3w
            ckoz8Y7LzF54UczezJx8WlGn4NL7Y3+YNYu2n9BWnuuVwnz1i37FdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sukfru07msq8fm5ddgym23yal9lfm99090p999p09mxgrrwh9aqs6zp4fy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMkRHajdmY3JXOWlPeXBT
            SFVGZzdLYzFubUsyY0RYbWJra0tZUlBWS3pnCjI0eGV3dDR3dTZpRVRFUzk2SXdC
            T3RaUlNOT1MzaTQ1eFAwdEJwWEVGL3MKLS0tIENqRVRYMG9EMnAyRXpKRFRGQTFN
            a1ZiMnBqZ0N0YldyOUlKRm1ZNU82YjAKvmIUdy/AtAh/K/5CamilJ+M4H32jvrD5
            +jvZtkns/D1posr7bQq74tsbw96a7GcNdL9DT5RI8piO79fFht/nnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ephzrpgftmvq4cul9766q2r3mss38xu6un74ryfmw0729afysghsh0a3qg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONGRzSFBEaUxXKzNyMEor
            aEs4aGQySzN4UE90TXJUOGhlUXdoWkJoVEhzCmtaWitON3FtYXl4cGppU3RqNGdi
            MUFvTU5USlUrNUI0Ri81WldpR3JZUjgKLS0tIExmcXN3b0ZXUDRVUytLWWpuMjBy
            cHZXbFNySnRSSUFVRGIrWWI4ZlRsU1kKyH1mVGbaNsX1xNaaMyMu7pGeF5kMBpEj
            zgkMulow4BZTkzG4ZCTLcOTR+1RNNl9iHe3MRcrsEE8c6cqKccpMNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aEwycWN3UjR5TXRpN0pB
            M1h4SS93ejQvblZDc29QdnJlYXprSmtkOUFVCkdYNjdDeklSWCtGVWtuc09CVXRu
            THRVVFg4VWRWeVlTdDhNeEJORXNlNEEKLS0tIHlCcE14MWp4MTEzdVU2RFJ2cEQ3
            NmZmQm1lRzk4S0xQeGJuVTVsZFduR1UKoUnkSJayGYY12Ff9lPwWEQVQvthV7sWn
            2FLaKCz7j4yA50NgVBYEoNj3X8wSKiUkJyu0bBRzZD6kQd+LUwYPfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s7ecrfntus8rvyprzhffjpqk2tmrc259knf9xqajlrqvewfp8d6svwp9pp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZlM1VjBkR0NiME5UYmh5
            YmVTMXZmckdXeGl0enM3c0wxRXBNV3NkeXcwCktkRm5UK2tjMG90RVo2VWFpeVNq
            bkxIYVhjajFpRGJKWXFIYm95N21XMFEKLS0tICtMTG53NFNjZlpTSDZHMitoK0tS
            RFZkaUxrZWRDK3JQQ3hqNXdkSk53MGcKBi0l2acQXaTj6FRebUmBBLp+Pgyv1g/i
            vP+e6K1xsqqWPgrjuy4dPdkeXygC7eKMzq6JqLemnjWDTUyVqSuGTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:EbBpuzPHH5yzTPaKF6+jI4T2uEZziW8ylrmpmGbttGvrATbcbzzk0e95DnEjSOlFkf7sceu41AyYLvyG6flpaJUscdhIFs70jF7WAKIi2+hPQb5GK/O7kgf6Z1Y1WGiUTxtUy4exPfTlFA32DF6WuBK+BAVZWQ3hK1jWt1iPW5k=,iv:3uW1lXftUPIOqo1Xfby9ztuInPX23VuN5TB8+mCHgtc=,tag:JiiYcwAxarfyX6E7B//1UA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
