apiVersion: ENC[AES256_GCM,data:zZ4=,iv:4x2VMC3p9OunH5gm0/ALVmjbjYfgTrkN9D3vJNEkJxs=,tag:OjKStza2MM2k5/GmPFYGpA==,type:str]
data:
    ADMIN_TOKEN: ENC[AES256_GCM,data:yX3Ls47XjhIicQtwlJnzWe5SaMrCMuXIAugBo+B47xKFI4tuTowmNgmRhQw5vajDSnsq+1YmBHNnLBAuv3YkVHjWcBnlIsFEoEZVX1XVWdFHg47tlL+hw6QUqJjumNz0QtaG7WC1dQ/H9zP3uPd9BiPcOzgfVYCHhCGgS9LZwgs3gMzJ+zgjc86Vl56AC0frMNB6S6QQwc6iPHF8HZOZyw==,iv:wse+icmUldfWpJ+ldW8LQsbMdOybza32Vc4ebIcym5Q=,tag:ZLVA2WxKYkxFXzTYs3heuA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:q6cxDgIaJ3IDu6PLYks6Jxi2uwl9Nl3d,iv:lkCpLsU+Cj7fVrlMZ9eI+CGGQrgMS567K00CQKrP70A=,tag:ICTXdrawomJLe49ephJDhg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:bjhK+DnLCF5DQU4ErSoQX9Y3+/A=,iv:vyDpL7MsTynTQwi10iV7mp8YPuIVB3j7Gh1tiMTAO+0=,tag:zJvy8B2LgiKorE1F8twkdA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:tzQine5C6YYG83HKCqHAAnzcmmOQ8JZ6erE/6Luxe1hEV+BIRqoDkulk0duibuXs,iv:+jHTmk2bfssClBgfYAqfTbmZ8/zO464PXebc9LkliZU=,tag:EGB+o+oTdRdPUdsIc3qpCA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:E/luVA==,iv:xf8gh0M6ir0EU2uCu9YqVVSyF8K/FYEzAeKIzh7rNFA=,tag:WiH49XhYhs2hfgQQCyW45w==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:QkRbeUSei68OxzVW5Fv2T9sVBd1m8hxw,iv:52oK4YTriDDNfR8ZLCJd+vzeCTyBLS7B/MvjpOdMnT0=,tag:G/xYsK/bcVNUJO0UIA4iQQ==,type:str]
kind: ENC[AES256_GCM,data:9jNkJxza,iv:HgAoksFP/7PsSoR5M3d/7OVDwsgF7JYkNGhmvV4iNCM=,tag:hPq+sq7wF3SQaC1tTP5yiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pIr3/rWDEZkjTni7kSz1,iv:mstmJJL68dEG/1WTDeL/dbPBdwWEveMvBZybVxTNNmQ=,tag:9EIZBXvkhMJoM6mv3bX4HA==,type:str]
    namespace: ENC[AES256_GCM,data:SgOTH3kZYg==,iv:wD5ZnBYvAvh6NnuvrD95i3Pst6654jSEXSg9Cm2wvxc=,tag:7Q1Xs6/8O5KnRzQ64A1OkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObG1qSkMwT2pGck5mS2c2
            ZFZnd3JDQTlrWmdkdUNmVkRDUGJwckluSVhZCkRNS1RnTFhlUTl0TGFmaE9rcjRM
            ekJjaUM2ZGY5cHpoYld0aUxuNTN1TmcKLS0tIFBzNS9WV1ZRNHY2ei9KSXRTOVBE
            V3MyVHhzcVZhYXlKZHpaRDV3MHIzT2sKXVzoBE0AKgLMCUzRmKl77kZb509UiDlk
            +1nQU2ydlhM5izHfKA/fFUQGuQeS/nif0nHWARoF5F0wXvmMMIy/5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g79dfm0p44q5yxzhwd9syg965lupdu3n5lgyltdannmul5v5v5aszzz3gs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcVFmQVEzSklnelcvTWlp
            Y01MZldzUlJYQmtQZEhaa3pmaGNmWW1haWhJCk5ZbnlpNi83T1VYOEpMUkhocDQx
            VWRNbG9WV0hDRHB5R2lKeUxTRElobTQKLS0tIDhhV3JRbytndXhxNWU0djdmSkNk
            MWNhckpOMjdqZ0RvaTBhTmc1TWtKK0UKoNVpueD8BJCDp9MYDy05QNV//vboB1z5
            c3S7eBn3iKjUoN/uEHEWQPF+deaSRNyo/N+/Dc4qE3isk5+U6cvM1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpK3hFMzYzM1FSK0JqS0tI
            eS9FdDY4ckdtZXd0OVM3ZjN1S1BWUVA5WWlZCnROdUF1YlVUeUM2OFFNSHNwdEg3
            c3NkK0RabWxxZW93TlNibTVTZHNqWmMKLS0tIDZ2eGswang2blZIanZTQXFScEIw
            YTZUTWMrbmdCTEk5cjZkK2lCWDVKUzgKRyaNSaC91pGh2hRBlr4TNNxLTgZannrD
            PzV1v/JRcD2pys2Ia/r5NtloXuLDQa5xQDTKcVT/iI4iQnykYQxtRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN3l1L1F3OXFpK1AwdGhh
            T3N3anYwSHJQRXpIVkNyTGx2TlVVWWFsYnlNCkdQZzQrN01tVm5iYVRyVEVKZitl
            QVlZUjg2VEZLcVRqeG5pSmxSR0ZHRmsKLS0tIE5YKzBWMEJiWmc0ZW4yS3pxdVlU
            eHplQWZPdnhDaUZyUVZIRG4zVCtBTEkKhyNT3QUKlIWzOEH/hJJBNwMpDmakmmef
            uzrGuTYCC0rzK96pX0ZLQ1iCaJGbYXqadpAP4W3GOFkWosFAeeeYEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZGdtTk9oNjZyOG9QU1dn
            K2kyVElmUUdvWmQ3L0dmRk9Qa3lIeVg1YnlBCnRwTGxYME9RVml5WEFyS2l4MDQ2
            TUFlbDZFMTNUZFFDTGhTSXQvcHZwdkUKLS0tIHBxalhrTlExWDNNNTFrcW5kZ1Vo
            WGl6dXNZck83YURDZnAxMFZFbGtWL3MKrAr+Z6ns48gJk2IGCkvu8xG/FjA/1YNu
            lSqxaBaMYSV36DkvJ1v0AEwfhxA1tuN8pIgtsNRmhivI5+98cX6+sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVjFKRCtDNWw4Z2V2LzMv
            SHRsRlo5NWY5b0k2WTJ2di9SdVg4bitMKzM4CnBWVkFjZnUyakVDMUhpSDFWR3B2
            Sm43UnVaR1kyQmFGeDRkTWUreGdSdjgKLS0tIEdKOFEzMVJhUnZueXJpWHdDNVdj
            ZnhZNlQ3SG1LSTdvMEhBV2FRVTB4cGcKFrOQBgI9CSnp/RXhM5E2+xUTMgZkoJlq
            DXBzQ+9rMC1QNtJ1qO9Zit3BqgdBIagL9w76nB0XiZ3r7b3jj+ZkIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcjJ6dE5hSU12dnZLQS9W
            YTNaUzZwVUp0ekdFK0EzanlmYTJuUVpUTnpjCnhCOFh0RktqdGMzRzNBcmxSVGRj
            c3kwT25DbmUzbXZFZmYwSW1ZRkhOa0EKLS0tICtlVys1VDl0bmJtTzh4SFZXeGxJ
            SzQ0a054WHdoQ2RNa1N3MHJzUUpBZXcKXFs+LV4I6aJreRXfUTAMuAEODTjjETcd
            QipAaKkvzn+QF+UclL63wMcqQ5mr+eqv/a+14c0YYRq7LHYdUhrRlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOXQxTXdKa3R6dmR0dWl3
            aXI0WHFrV3Y3KzE5US9zcEsxL2YwRy9FL1VFCmZiWFVJclBIYW9Kdm5zTnh3a2Jn
            aHY1QXl0dndDRFdsKzBkSUxPYkhPRnMKLS0tIHlzRXFpRmoyMDNyS0V0WU9HSDIx
            V2hSOWxXNWJOdWtiZHBaT3pJd210T2sKNuygVI5uUCkxjiTUOMNd5H+/q7w0+mVW
            D6un4+HL4FuYG0fuXKax7tZ4orYN1brYhibkxUSYERVEJ9A9oLUo3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKM3BucG84MlFlbURjSWVK
            YzVPQjVPTkdoQ3BOaHRKY0t5MUhxbXZYQ1hBCll0eXZWcGhTSENybHNuQTk0VlVO
            TVJKY0tEWUQ2b2pVaUxwa0ZkWTZYVnMKLS0tIERYT2JCSDk4Zks0ZDFyYnRxam9J
            OFdMWG42TExwS3FJT1lSSWFYekIveFkKEy7W2aDJvbUhGABaZl+vPnIEPET3XIyj
            1j9JU1AwstU0upLgnFDh4huLFezE7g1QPMxukrlS/0+YKSsH+QVQxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaisxNVJmQkljOW5IUW85
            YTl4cXpVSHQwSGl1azlnOUcxUkZKZmdGblNRCmM0NTAwZzlHejluTW9BQ1lqT3lt
            MytJTk9BN1ZTQUlDMkdSUHBuRGcvQnMKLS0tIDdHcE9JS3dOUHZJZDBMaTN6eWdV
            a2xvUE93L2xtenVqVU5VUGNKSVI2VUkKmF3SZaroLk2CYZULjkIE4KjbbnEkWSfb
            NXoONk5zXv3zoJwyrB0kC5d0pEMRIKEKqC4R57TTUAdpBidIUSWkbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbUZ4alNUOENRdjd5ZG4z
            RVRiUmRmOGhPTnE1SjhIYi9TVEtTdnR4djBRCndVOUJnaS9tM2g4MC9aWWtDZ0hL
            M0orbXpHT2JSQlhwTWg2SHdOWmNlMjgKLS0tIHk0SU1XaW94QVl0UlgwVlBlaVVG
            RDVwMjA4Z0ZkN2xYR0UxNTB3cnlvOXMK2TMY37Da0pJVgRH1hHk1Dhfldyf+UKoT
            c6YKgy4u+wLHhlDpIGVYjUde/G77bKksVgy0AdTaXTRHgoA3Z8Fjdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNktOYVRSK3JXWmhoTkdh
            aUorRkIzU1poRkRaTXF1N1ptVWNmdmtvSEQ0Cm5uRGNjcHp1bzBLaE1hOXdmUXZi
            eWZLbTFKWU94aThvQnFldDRrMTdaUHMKLS0tIEFwQ2JnOGV3WkZFY0I4R083d3dM
            bHNsSjdyaVo2NFBHdGkvTWZENDJnbFkKY7V5Yosd8HgVTdukUeH4YIAGFHFf28X1
            FgqDOaa76t11+4sQYriomrnTophT+zul0m++A7Fq1fFNAMizLD4+hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscEU0L0c2RUY0TWsrNmxu
            SkJQWXZRSTVFWUo3cm0yRXNCbi9kWVVBcTFjCjlSRXdEcXNMNjJPZlBCQ2xyZEhW
            Z0k3WERQREF3Qm9XYmhxU2hxZ3gxSmcKLS0tIE9Ja2FVUjQwQUxVc25EVkRJVldn
            TUlkeW1YVWxhTGpaS1JMMC9nazdUR3MKjuA9iMZqsPvkG+KzxPKpKQQIIslpAvqW
            hGV6Q/0jIJCwoUTvsOA8gL3pNPK0SzDtrbnjhvPkieEW7jpPul17oA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMzFITndXTUFaVThRejRo
            S1BzV3VadDFQZWF4V01KTnRMaVRNUFRldWpzCkRia21VRXpldzRXanZwbks5ci9N
            UVFaanE3b1AxRHJZRG5qK21pd0w4ODAKLS0tIFNTWUQwTmI0UHdPVUFZdTVqTmds
            cFl6SWQyMVE5bUpzRzJna1ZSVGxVclUK08xL2Jiz0gOGH3RiogehIi+wrIGJ4i4/
            0mwR6T96NOSCuFTlbn+H503NJJvFQ+uqgyCUDW3zbNVrJnAL1WqYKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:EbBpuzPHH5yzTPaKF6+jI4T2uEZziW8ylrmpmGbttGvrATbcbzzk0e95DnEjSOlFkf7sceu41AyYLvyG6flpaJUscdhIFs70jF7WAKIi2+hPQb5GK/O7kgf6Z1Y1WGiUTxtUy4exPfTlFA32DF6WuBK+BAVZWQ3hK1jWt1iPW5k=,iv:3uW1lXftUPIOqo1Xfby9ztuInPX23VuN5TB8+mCHgtc=,tag:JiiYcwAxarfyX6E7B//1UA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
