apiVersion: ENC[AES256_GCM,data:zZ4=,iv:4x2VMC3p9OunH5gm0/ALVmjbjYfgTrkN9D3vJNEkJxs=,tag:OjKStza2MM2k5/GmPFYGpA==,type:str]
data:
    ADMIN_TOKEN: ENC[AES256_GCM,data:yX3Ls47XjhIicQtwlJnzWe5SaMrCMuXIAugBo+B47xKFI4tuTowmNgmRhQw5vajDSnsq+1YmBHNnLBAuv3YkVHjWcBnlIsFEoEZVX1XVWdFHg47tlL+hw6QUqJjumNz0QtaG7WC1dQ/H9zP3uPd9BiPcOzgfVYCHhCGgS9LZwgs3gMzJ+zgjc86Vl56AC0frMNB6S6QQwc6iPHF8HZOZyw==,iv:wse+icmUldfWpJ+ldW8LQsbMdOybza32Vc4ebIcym5Q=,tag:ZLVA2WxKYkxFXzTYs3heuA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:q6cxDgIaJ3IDu6PLYks6Jxi2uwl9Nl3d,iv:lkCpLsU+Cj7fVrlMZ9eI+CGGQrgMS567K00CQKrP70A=,tag:ICTXdrawomJLe49ephJDhg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:bjhK+DnLCF5DQU4ErSoQX9Y3+/A=,iv:vyDpL7MsTynTQwi10iV7mp8YPuIVB3j7Gh1tiMTAO+0=,tag:zJvy8B2LgiKorE1F8twkdA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:tzQine5C6YYG83HKCqHAAnzcmmOQ8JZ6erE/6Luxe1hEV+BIRqoDkulk0duibuXs,iv:+jHTmk2bfssClBgfYAqfTbmZ8/zO464PXebc9LkliZU=,tag:EGB+o+oTdRdPUdsIc3qpCA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:E/luVA==,iv:xf8gh0M6ir0EU2uCu9YqVVSyF8K/FYEzAeKIzh7rNFA=,tag:WiH49XhYhs2hfgQQCyW45w==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:QkRbeUSei68OxzVW5Fv2T9sVBd1m8hxw,iv:52oK4YTriDDNfR8ZLCJd+vzeCTyBLS7B/MvjpOdMnT0=,tag:G/xYsK/bcVNUJO0UIA4iQQ==,type:str]
kind: ENC[AES256_GCM,data:9jNkJxza,iv:HgAoksFP/7PsSoR5M3d/7OVDwsgF7JYkNGhmvV4iNCM=,tag:hPq+sq7wF3SQaC1tTP5yiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pIr3/rWDEZkjTni7kSz1,iv:mstmJJL68dEG/1WTDeL/dbPBdwWEveMvBZybVxTNNmQ=,tag:9EIZBXvkhMJoM6mv3bX4HA==,type:str]
    namespace: ENC[AES256_GCM,data:SgOTH3kZYg==,iv:wD5ZnBYvAvh6NnuvrD95i3Pst6654jSEXSg9Cm2wvxc=,tag:7Q1Xs6/8O5KnRzQ64A1OkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeW5BTVdxTHpGMDhJM3Ar
            QmhVMGh0RnIwOEwzUjJGUWZQSHlPV29WM3lRClVwOVJwUE9VaGJ1RWd0ZnpRZ2Zw
            YzNjeXBZNHpjYStub25JdGlEeG43NzQKLS0tIDBqT01qOVlLNlVhS0lybnJhR25O
            S0M0K1ZqQjh0MVgwSmZveGNNdDQwRlkK4HpBaDib3F9cUWaRaO/gWcAd5RSphvSj
            nlqOsTnsgMKcGAZlXGeN4payxkolQhnhWT01RWpX8u1ND0LEPweBNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQkQrb2dlVXJUMnFNTzlH
            cDc5VVlQZjJrWWNMSFd1cXFyaXZVcnhzNFJBClRyK3JUSDlCd3ZaSUQxWVZxK3px
            TVozUmZBSXByTERmT0c5SjJicjdjUGsKLS0tIGdkTXgvMFdrOTIzQm9iMnVnOWNJ
            NzZueTU2eG5IWWVUcGdJWjNDUUo5ckUKN129T0BeV9pszxj8VYKYkhLv3GTpXbvq
            KGaArtdRsanKyYpIza03t6JJC6ZiJIKpr6Bo+1fZag69r2B+571+9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cDY0WGluSHhCSVFzOS9q
            QmQwOGRFMXlxVDZUL0dwSHpReWYrVEVvT1JFCmlsdlQxMStvM3JkcjVRaEphM3hB
            eWF1Mmk3Y29pTTUxYktOYWpweXdIYlEKLS0tIDRtOGE5dzZTR1V4bCtxQlpqNjA1
            bTVBVjU1SFhUYUxzUDVxYXFoNDBCZzQKsGCh8XBJKMC9Vh8C2bCFPL4IrsWm2fQu
            wmxXvfexwLsfP1uWTInzdHJRCpsSrKj4YPjpWOfjYbEZG25wV8wqIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dkxpaW1aVTVrOUJ6NkZy
            Y2QvU2pVSEEyMDc2T3NQeUVyM3E3TEo5MUhjCkxHNXQvYTVHejlVUUJUNGRkUWJD
            cXI4VWNidSs4bXgvUmFSVERBd3M5dTQKLS0tIHErM3ZYNGR2WGRqSFZZUDhJK1Mx
            WENPVmFhM1BLN2lPQ2FuZDc1UFJqOVEKdJtTOQpRkYQBwbeJ0s7dB2HPpCth+wQT
            J7czWxV6E0KPkhlK04e8kC9lQ/7Lw1tRvKc4TauvMpBlUYVvDp6ILQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bEdJQngyN284NVowZE9W
            RSt4c29BSGNCMUd0dEMrMnNWdFk5TklYbFh3CkNEYmFPVHlxY1lQZnUyYTNsdHdv
            RDdyb3pIMllicWsyeGZoZEUxZm9BaXMKLS0tIEQzdUtUeHgyQ2FMNTQyMGhoZVEz
            QWFPTHluNkxEYmtqQms0UlU1RDBwUHMKbJBnjC6oIpXnKRYZHmXrSuhrYwe4CMWA
            P1SyBDJGx+TwsxXeVvKDNlP17UuenqsYWgAAXinHszcBFX7nqB4fng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOWZhZUJvMHdkR3AwZG1m
            SVZ1V0NrRlhCWmxEQWd1eHNEbG1zVW1icmw0CjhETmVqd3RXaGlzbFFoSmRVWlAz
            SUpHYTRCcUxPZ0psV2pQR3JmY211Y1EKLS0tIHJiOEd0VFNCS1czNDJOa1RrcVVC
            WWhxOFFqQko3THh1aVVjMFo2ZnNPUzgKBTxJ/fr8+ixegpr0W2nIWPrUstl09hrS
            JM5zKE9sLyX4KSBfiM7K4+dElo6PqTMttfYBQoaRquWvfDWiNSes4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUGpBQmh0YlRReXVsVGRK
            bzNVTjZ5ZzVPSEhWSUF5WE5tQitnZTB1QVRVCnRaTFpNRzNHRzNraDMrK3g0MDU3
            WEFoRjkzbm1EY2xPNTR5ZHhSdjFXQ2MKLS0tIDkwY0tXa01PdVJHSTVyaFl0bmZv
            N1JoaVdjb3NLczZuV0M2MEhGc2t3QlkKfYnnxIxd9mP3mOWOktp+P3npQH8Eail3
            Eo0Tw9l3AoSncgkXheJEdHaWIC9L7Ms+G4JMyqu/pNGVT/zhm4KsgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSGQwQXBTTTZrZEI5bHZ2
            Y3IvNFZ2M0JGR2pQWm9YWnJsNHJxVENHUFdzCitNV3Vyb1V0K0t4MFlWYldkMGV5
            SmQ4S3U1TnFvWGIxWFdwMFk2SWljRkEKLS0tIHlQdzhOM0RMRkNUeHZHRDJLeFpm
            NG9VQnlBU0Erem1Qb3d5MmJuVE1vT0EKZgPOM4c3HydgLUwodpUMKMyGnlEpS6AW
            kpyJl714KS2uNJfhqfqyrHcPUEwKZEB48NxO7vpWpkhxie37daRn7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbjB0cGlxNEdVZzYrc3h2
            QVFMajRLUCtjZkI4cXk3N3hkbzE3K2NMeWlJClZhbWJjT09NYWhVMHlrU0xtSVB5
            cHF3MWlOOE5Kc003UkR0R2ZtWmhKN2sKLS0tIG1DRUZBRzlialFZbnlJUCtOMXJp
            NlhVMkpTMTdySHlUMHBYOG5ab2ZyNXMKhzb2s1s4S5AUNwpDGVlx9IVY8lXJuRi+
            GMJqJmsZvI+DkhE8a8zb7qakWmwY8qCCgsIjN1XBM0TEugj7B1ix/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xwlrtfu3du4jxg2l6eemzqeed8tflhdkjn0q5j9pzpecshtp3cpsh60l4j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MStRa1dwMTVSOTdFM09U
            aXBZbGxyMTNqbnlrNmwvOUFZaEtEeFI4N0ZnClFtQ0pYSzJTaHpHWnYwV21ZZUlD
            NmhKZ2JwenFrVGxZbjBhaHpkVzRhSDAKLS0tIERzVDhFcDRob2dPNnhsT2EzZmZu
            TVlOU1RvMVk5M1ZMcVYyejJSdG5lSmsKPJWUvYbmE8LFM8XYG25IbRiLGMIKL1Lk
            EghCte/rYUuPF9Oj+q2SCWXgksk4wqIYr6ztFL26uc1WH91F/2sCtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR2NXRXY3aUE4eEVMblEv
            WHR0ai85S3lVYjNQUnpLeVd0c1VrQ0p2eDAwClpUTzdnbVErSjJ1YTdSYjlNNUJx
            bmNRNnhjeXg1TkJma2huOUR5c3UydkEKLS0tIGgxNWJpcTF5QmRINW1mV3NESVNR
            aDE2Y05HdElpcU93WHljT3FlNXF5VnMKaIMDSi49EzF5sw3397FT0AnHNTJEvVNn
            9y+cE5vmkb+A8zzD1LfntUv2flOMVQXAQMbozMC6UhMLxXYVVchaKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1stsuakfyj3gkee4sm328ky2crmymyuzwjjmxrpvnm754sdt2zvnshf68jx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYldwOGM0ZkhwNHFHL0hP
            MEtGeCswYU5lanNsRXdVM0pvNnBpT0dsNENFCm5JMWRJTTlZV3pWaXEyZDZaZjFC
            cU1qTHZ3TnhhSzJxcVBiTFArUHk1QjQKLS0tIGlEQmNZaVhzc0FKR2llSnFNczBl
            WnNpdU9vSlMzV0YzMFhMQjJ1ZlJyTzAKke7tkoPXMZGfDTgG0tmoyGkuSU/s/uXy
            RtmqIgJKUB2jWcm6QzvlJYtcmDLDRA68Ixi8jGRDyj7UcFrNHtFGcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yq47x0cyf95jg372v84ttptgnppsrfmxshsua6p58ecmgzxc5c0s5stfth
    lastmodified: "2026-07-01T19:42:05Z"
    mac: ENC[AES256_GCM,data:EbBpuzPHH5yzTPaKF6+jI4T2uEZziW8ylrmpmGbttGvrATbcbzzk0e95DnEjSOlFkf7sceu41AyYLvyG6flpaJUscdhIFs70jF7WAKIi2+hPQb5GK/O7kgf6Z1Y1WGiUTxtUy4exPfTlFA32DF6WuBK+BAVZWQ3hK1jWt1iPW5k=,iv:3uW1lXftUPIOqo1Xfby9ztuInPX23VuN5TB8+mCHgtc=,tag:JiiYcwAxarfyX6E7B//1UA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
