apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: gotenberg
spec:
  type: ClusterIP
  selector:
    app: gotenberg
  ports:
    - name: http
      port: 3000
      targetPort: 3000
