---
- ansible.builtin.include_tasks: _write-secret-and-restart.yml
  vars:
    secret_name: nextcloud-sso-env
    secret_data:
      OIDC_CLIENT_ID: "{{ client_credentials_by_slug[client_spec.slug].client_id }}"
      OIDC_CLIENT_SECRET: "{{ client_credentials_by_slug[client_spec.slug].client_secret }}"
    deployment_name: nextcloud
