---
- ansible.builtin.include_tasks: _write-secret-and-restart.yml
  vars:
    secret_name: nextcloud-sso-env
    secret_data:
      OIDC_CLIENT_ID: "{{ oidc_client_credentials.client_id }}"
      OIDC_CLIENT_SECRET: "{{ oidc_client_credentials.client_secret }}"
    deployment_name: nextcloud
