apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aly-codes.yaml
  - collabora.yaml
  - error-pages.yaml
  - forward-auth.yaml
  - immich.yaml
  - morsels.yaml
  - navidrome.yaml
  - nextcloud.yaml
  - ombi.yaml
  - paperless.yaml
  - plex.yaml
  - pocket-id.yaml
  - seerr.yaml
  - slingshot.yaml
  - switchyard.yaml
  - tranquil-pds.yaml
  - uptime-kuma.yaml
  - vaultwarden.yaml
  - watsup.yaml
