apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aly-codes
  - collabora
  - error-pages
  - forward-auth.yaml
  - morsels.yaml
  - navidrome.yaml
  - ombi.yaml
  - paperless.yaml
  - pocket-id
  - seerr.yaml
  - switchyard
  - tranquil-pds
  - uptime-kuma.yaml
  - vaultwarden.yaml
  - watsup
