apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: flux-system
spec:
  dependsOn:
    - name: pg-shared
  interval: 15m
  releaseName: pocket-id
  targetNamespace: default
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  chart:
    spec:
      chart: ./k8s/charts/pocket-id
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        { kind: GitRepository, name: flux-system, namespace: flux-system }
  valuesFrom:
    - { kind: ConfigMap, name: cute-haus-global, valuesKey: values.yaml }
