apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  suspend: true
  interval: 15m
  releaseName: uptime-kuma
  targetNamespace: default
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  chart:
    spec:
      chart: ./k8s/charts/uptime-kuma
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        { kind: GitRepository, name: flux-system, namespace: flux-system }
  valuesFrom:
    - { kind: ConfigMap, name: cute-haus-global, valuesKey: values.yaml }
