apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: watsup
  namespace: flux-system
spec:
  interval: 15m
  releaseName: watsup
  targetNamespace: default
  chart:
    spec:
      chart: ./k8s/charts/watsup
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: cute-haus
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cute-haus-global
      valuesKey: values.yaml
