apiVersion: v1
kind: Secret
metadata:
  name: bluesky-pds-env
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  PDS_ADMIN_PASSWORD: {{ .Values.secret.PDS_ADMIN_PASSWORD | quote }}
  PDS_EMAIL_FROM_ADDRESS: {{ .Values.secret.PDS_EMAIL_FROM_ADDRESS | quote }}
  PDS_EMAIL_SMTP_URL: {{ .Values.secret.PDS_EMAIL_SMTP_URL | quote }}
  PDS_JWT_SECRET: {{ .Values.secret.PDS_JWT_SECRET | quote }}
  PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: {{ .Values.secret.PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX | quote }}
