apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 60
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 60
      containers:
        - name: {{ .Chart.Name }}
          image: vaultwarden/server:latest@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
          imagePullPolicy: IfNotPresent
          env:
            - name: DOMAIN
              value: "https://vault.cute.haus"
            - name: ROCKET_ADDRESS
              value: "0.0.0.0"
            - name: ROCKET_PORT
              value: "8222"
            - name: ROCKET_LOG
              value: "critical"
            - name: SIGNUPS_ALLOWED
              value: "false"
          envFrom:
            - secretRef:
                name: vaultwarden-env
          ports:
            - name: http
              containerPort: 8222
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /data
          startupProbe:
            httpGet:
              path: /alive
              port: http
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            periodSeconds: 60
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /alive
              port: http
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 2
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-data
