apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-env
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  ADMIN_TOKEN: {{ .Values.secret.ADMIN_TOKEN | quote }}
  SMTP_FROM: {{ .Values.secret.SMTP_FROM | quote }}
  SMTP_HOST: {{ .Values.secret.SMTP_HOST | quote }}
  SMTP_PASSWORD: {{ .Values.secret.SMTP_PASSWORD | quote }}
  SMTP_PORT: {{ .Values.secret.SMTP_PORT | quote }}
  SMTP_USERNAME: {{ .Values.secret.SMTP_USERNAME | quote }}
