apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: longhorn-creds
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.keyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.appKey | quote }}
  AWS_ENDPOINTS: {{ .Values.secret.endpoint | quote }}
  VIRTUAL_HOSTED_STYLE: {{ .Values.secret.virtualHostedStyle | quote }}
