{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-env
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_PASSWORD: {{ .Values.secret.NEXTCLOUD_ADMIN_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  OBJECTSTORE_S3_KEY: {{ .Values.secret.OBJECTSTORE_S3_KEY | quote }}
  OBJECTSTORE_S3_SECRET: {{ .Values.secret.OBJECTSTORE_S3_SECRET | quote }}
  SMTP_PASSWORD: {{ .Values.secret.SMTP_PASSWORD | quote }}
{{- end }}
