apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: slingshot
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: slingshot
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: slingshot
