apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-routes
  namespace: flux-system
spec:
  interval: 15m
  releaseName: external-routes
  targetNamespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./k8s/charts/external-routes
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cute-haus-global
      valuesKey: values.yaml
  values:
    routes:
      - name: plex
        host: plex.cute.haus
        target:
          ip: 10.254.0.1
          port: 32400
        tls:
          secretName: cute-haus-tls
      - name: slingshot
        host: slingshot.cute.haus
        target:
          ip: 10.254.0.1
          port: 8765
        tls:
          secretName: cute-haus-tls
