secret:
  NEXTCLOUD_ADMIN_PASSWORD: ref+sops://../secrets/nextcloud.yaml#/admin_password
  POSTGRES_PASSWORD: ref+sops://../secrets/pg-roles.yaml#/roles/nextcloud/password
  OBJECTSTORE_S3_KEY: ref+sops://../secrets/b2.yaml#/B2_KEY_ID
  OBJECTSTORE_S3_SECRET: ref+sops://../secrets/b2.yaml#/B2_APP_KEY
  SMTP_PASSWORD: ref+sops://../secrets/tranquil-pds.yaml#/secret/MAIL_SMARTHOST_PASSWORD
