secret:
  PAPERLESS_SECRET_KEY: ref+sops://../secrets/paperless.yaml#/secret_key
  PAPERLESS_DBPASS: ref+sops://../secrets/pg-roles.yaml#/roles/paperless/password
  PAPERLESS_ADMIN_PASSWORD: ref+sops://../secrets/paperless.yaml#/admin_password
