backup:
  enabled: true
  b2:
    keyId: ref+sops://../secrets/b2.yaml#/B2_KEY_ID
    appKey: ref+sops://../secrets/b2.yaml#/B2_APP_KEY

roles:
  forgejo:
    database: forgejo
    password: ref+sops://../secrets/pg-roles.yaml#/roles/forgejo/password
  tranquil:
    database: tranquil
    password: ref+sops://../secrets/pg-roles.yaml#/roles/tranquil/password
  pocket-id:
    database: pocket-id
    password: ref+sops://../secrets/pg-roles.yaml#/roles/pocket-id/password
