apiVersion: v1
kind: Service
metadata:
  name: aly-codes
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: aly-codes
spec:
  type: ClusterIP
  selector:
    app: aly-codes
  ports:
    - name: http
      port: 80
