apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages
  labels:
    app: error-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error-pages
  template:
    metadata:
      labels:
        app: error-pages
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: {{ $.Values.global.failover.fastTolerationSeconds | default 60 }}
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: {{ $.Values.global.failover.fastTolerationSeconds | default 60 }}
      containers:
        - name: error-pages
          image: ghcr.io/tarampampam/error-pages:4@sha256:f23f8042a2804669315fd232281d0ccecf1959332314a46e02ca2482064064a6
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPLATE_NAME
              value: "app-down"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
