apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: error-pages
  namespace: default
spec:
  errors:
    status:
      - "500-599"
    service:
      name: error-pages
      port: 80
    query: "/{status}.html"
