apiVersion: v1
kind: Service
metadata:
  name: error-pages
  labels:
    app: error-pages
spec:
  type: ClusterIP
  selector:
    app: error-pages
  ports:
    - name: http
      port: 80
      targetPort: 8080
