apiVersion: v1
kind: Service
metadata:
  name: aly-codes-svc
  labels:
    app: aly-codes
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: aly-codes
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
