apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  labels:
    app: navidrome
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-media
  labels:
    app: navidrome
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - hard
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime
  nfs:
    server: 100.81.61.31
    path: /mnt/Media
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-media
  labels:
    app: navidrome
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: navidrome-media
  resources:
    requests:
      storage: 1Ti
