apiVersion: v1
kind: Service
metadata:
  name: navidrome
  labels:
    app: navidrome
spec:
  type: ClusterIP
  selector:
    app: navidrome
  ports:
    - name: http
      port: 80
      targetPort: 4533
