apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-prometheus
  namespace: flux-system
spec:
  interval: 15m
  releaseName: kubernetes-prometheus
  targetNamespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: prometheus
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 29.13.1
  values:
    alertmanager:
      enabled: false
    prometheus-pushgateway:
      enabled: false
    server:
      global:
        scrape_interval: 30s
        evaluation_interval: 30s
      persistentVolume:
        storageClass: longhorn
        size: 40Gi
      retention: 30d
      retentionSize: 18GB
      service:
        type: NodePort
        nodePort: 30220
    kube-state-metrics:
      prometheusScrape: true
    prometheus-node-exporter:
      prometheus:
        monitor:
          enabled: false
