apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotenberg.yaml
  - kubernetes-alloy.yaml
  - kubernetes-prometheus.yaml
  - pg-shared.yaml
  - tika.yaml
  - valkey.yaml
  - valkey-nextcloud.yaml
